---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: template
spec:
  secretStoreRef:
    name: vault-backend-cluster
    kind: ClusterSecretStore
  target:
    name: kubeconfig
    template:
      type: Opaque
      engineVersion: v2
      data:
        value.yaml: |
          ---
          apiVersion: v1
          kind: Config
          current-context: worker01
          clusters:
            - cluster:
                certificate-authority-data: "{{ .ca }}"
                server: https://api.worker01.kms20.shoot.canary.k8s-hana.ondemand.com
              name: worker01
          contexts:
            - context:
                cluster: worker01
                namespace: default
                user: default
              name: worker01
          users:
            - name: default
              user:
                exec:
                  apiVersion: "client.authentication.k8s.io/v1"
                  interactiveMode: Never
                  command: "sh"
                  args:
                    - "-c"
                    - |
                      #set -e -o pipefail
                      # return token back to the credential plugin
                      cat << EOF
                      {
                      "apiVersion": "client.authentication.k8s.io/v1",
                      "kind": "ExecCredential",
                      "status": {
                          "token": "$(cat /var/run/secrets/tokens/federated-token)"
                      }
                      }
                      EOF
  data:
  - secretKey: ca
    remoteRef:
      key: certificates/kubeconfigs
      property: ca_worker01
