apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:7Mw2yrVFGSLKQx2YFSL/e9s0yl5qu6vE2g6MvO8NhM75WsSF2Q==,iv:qOp07PiQrldOftQYo8RXohiJZGCvBZtFjqt56imWyTk=,tag:age4S7u+Va1X2ZO4IOMNig==,type:comment]
    token: ENC[AES256_GCM,data:gXYYTqxTLwY8,iv:7A+PA8duKnlSh13LorhH7Plm/M98i5QJe8bU03eixbw=,tag:91GimPmQD0NpLrHib2BpIw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdnJ3Y3ZUeHVPRVJlWUVD
            QnVKVzBTbU82cm5PT0VCY2tiUllwdlVzclEwCms3Rko3Mkl1Z01UVTRaWXJoRHh5
            RjFnMGdYOHlKWDY2RlVxUmJZT3JLR3MKLS0tIHh3OFl6c24vSkJFTFB4KzQ0OGcy
            NGExTlp3YXpOc3dsT0R3L1RoQUo2bGcKeh+ieDif9OINM2W0fzXoAbyhcvpJhd7M
            vWSQewRgnN/M2C5Y9QRw7Ans0evQy1cm350Ch0W4ZTABjQTn3BWSIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T07:10:27Z"
    mac: ENC[AES256_GCM,data:+ikSlK7J+tLmgSjnsKQyAKWcQzG4m3ypEgoFynLHxm+MG1+0m4gvhd9/Qsqk17kFx5IXN9ldP9ggZUINkmFp+uOibQE4Sw7WBfk4fali4JRuckasVmow8p2YT31qHUkFLkjQYmg2E+u7ABScKgYYq56pgDmXHpFdyKcfIkHnavM=,iv:ilfRCfoKOHIED4rcxM25U9KoLtwN7zpGTCK90CeMNhE=,tag:UZNAGVMo8b5lI6a4cNXAcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
