apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:l2K/yLIXZY10JtvatPHzZn9bvIsXdDEsnT/wOdj0bJHpjcJWlQ==,iv:InJD1lpfjhBcnoEDQiYpARxPZnDDbLPLydltanK16Fc=,tag:Q4lUnevhPoVAOK52+4AvXg==,type:comment]
    token: ENC[AES256_GCM,data:WE6KWc1QrOZR,iv:tO3FbNCp+hXp/acRO4BNtkvip6bFHlTmjbV1gFYDB5g=,tag:hiHYJpdd+fWimqtkdu34Qw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eTVFdFFEMklBWXdYZlN2
            cWJvZko1dnprVFJFNThXRjFKUnFPbWpseldVCkZlSXlJMmpabXBZcnpDK0dPOVBq
            R0laRDZhMEh5RTVJTVVyOCs2UEt1UVkKLS0tIGtHQmc0Z1I5L3FWdWxKYnVFTnRk
            RWpKaGZkSFdOTDRVQVk2TW00OTdZMnMK3fGMXeD1pocW2EjGaxfGrD1j9LqJhGZ/
            RD9/WHgKpq9sRqAOSWk3mp75YEWAeJEsVcQ67cxzGrzrcQJJ2WAdNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQVF1NjJxZGtrWHZsUUVt
            VDV3U1BYblIxbitzbVdCZlYzOWUvL1Vnc1hvCjZVQ0JYZExRWnY1bzI5S3QxUTdr
            Q0VQTjNFYzM0R0p4dWZCaHYwTDlMSWsKLS0tIFZZYlF4STJyMlJmVWJNR2FKRXdx
            Y2NzTnY4Qkw3SUMrN1owblhWK05nSE0KDwGapHJMxS/Utv0TZMpPU+rXZ4IEZ4zu
            uah/mb6V2xpJND3Vl2dBJJ2wxzqKLeDJ23h9zRlL5qQd7F7eOdo1YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tqkl3fq2rf73g07e8s2falaw8cuself395ev7u0mj8s02tpdsa5shfjt92
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVHh0ZXpvOUd0Sk1jTksv
            Mmh6c1lnaUlVb1JaeXJ5UW12bXhQM2IxbmxvCkNUUnVxV0dPd1lCS0tLdFlteGwy
            VStzdFdVSFdBaGE5alVnaTVBalYrRFEKLS0tIE0wWEE3ci92ckxTL243TE1ka0Zk
            ZWZSZlBlQWdrQVMxYlhZTDB1UU5BRGsKUl9EQn7sCyuF64SJ+qUSC0AeZCeHUohO
            J8uqEB4NEIc183bkg66lcqmNA2WABgeitdlaoVOIb/cSbJBytHNKfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T14:25:04Z"
    mac: ENC[AES256_GCM,data:Z/zoZMRJGESEUgLiwTPW5kP2c3I6ValXes2BO/evUTTgFDPmwD8UuqT7Z5fDtgnCRrfLPUvvQqLw+GUocNhkde+K7O8/iBdRN7AadIOneWXPSXRo+7M4xSRVJhUy/n6YiwVRsV8hqh1e7ZXOIjRxM7KP9taUgzroKg7iwHABu2s=,iv:w+99w++chgg5M0gdFQEVWiver5v4kcmRsMCg7/k3ekU=,tag:aQAQyqGJVotxwC11gpNApA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
