apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:Hbcpby3Fq2RPJ1o7/j+xUOiDqiiKz8U1bSacop94EKWqKRX/Vw==,iv:uc4SqEZGeONt33tBcqvA0Fpw5f6mCWoa70yLDtpcm7I=,tag:viL2JnigUCWiAiQE2fiKoA==,type:comment]
    token: ENC[AES256_GCM,data:vtzwm+SaYWJz,iv:aZubcthKARW8M4YObZMrkfSNQ6jTfLuePRdF+cexenI=,tag:P5CWf3Su1NNqZc2Ssz2ZQg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dWk5NG4wTFI0MTE2dmlp
            QjQzWDN0bDBZYm9tRnNJTGRmZ0VFcStMc2p3CmZIeEFabTF5SWxZOExwUVlrcDNW
            N1hyTXdlTWphUGgxZlhEaW1STWNrRjQKLS0tIERCMGF2ZTNjZzlWRmhZTEd0VGpT
            d0E3bEJCeVlWVE9BRkpOYnlYelQ3OFkK2nu7uGVzXzgcyzHbIglSt5C2y8clR0Ak
            2lys9pUCHktyo3VFdkrK3GYFHHUMQ92e0xj2m2J4mC45DVJem6vHAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXFXSHlZc242SDdVTlJo
            a0FrWmk4aGNCTndHOURIWWhPU0hzRERMUGxrCjJZdGZFM2FISEtiR3ozTVZiMmNl
            WlVMU3FjNDlrQlhKTXFadnp2UEViaUEKLS0tIFBibmxlMFRYSVN1cElYN0M1QXZT
            ZzhSbEE3TmtLbVFtamVCUkQzcVVmb00KLXwlvbXBfSYnNZui6tppnK6RPAyNADXB
            sn4s3NkQXBHwq8lpCRj6A7uEQ5r6HlxcsgsHOgRDAcoDUAxgq7nSOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSzhmb1BmdC9pSXV4eUQr
            OFZxU0hrWFgvcGwrK0VrZ0gwMUR4UVIrMFhFCm53ekloK0N5UTVCUGZucHVTVWF4
            TDk1T2pZTXpiL3VldVpQRjhpYThTdzAKLS0tIHFUNFpUYS80OE5IVXdpNWJtSHJk
            cjExNDE4Y3lVc1NKN1d0bjFsZGlzcncKJ2Eh347G0GfI6ELkXNf/x5icWjVpHc3V
            eIwH6428IVwqIlcUYziQJST0mnCDrPt5esrzvhZZxrPsZqQBamCdqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T10:51:47Z"
    mac: ENC[AES256_GCM,data:RUQwU+y1Hthpo5EhY2Emxynq65wt21CmbiV1GBJOV423Wapj7gUYzDLAVOsQQtxXTFN3F/8jCpsbqj3maGJ4AeEuDRZghWlsxz6ka/cGYDRe12AsgWcsL/SRjnVfm5XANNFvp3aysShHh0iew8zzyuKlYLbZ0kZ9kmd0M0DB/Nk=,iv:Uj4ZGPMID1tRLQA0g41WSTVblT+DkRk/t1SeRStByIg=,tag:jYkVC4530obtlHtyaqFOmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
