apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:95RouxWHMrZ6JeOT9k9APr/cGqzDDwWd99N1LkIF4Qdwn00uGA==,iv:u9es4ZyOz2SemvzY79OO5AedFG6nFExYOSxTPRVmzYk=,tag:ZQlvbzjuM1z9vA8uf6Cv/A==,type:comment]
    token: ENC[AES256_GCM,data:DLOuQrAXb0Mt,iv:xtbTagwqHCOMWouNM3Dm9NuCCBoGXKmQPeyHDB4MBNw=,tag:cJw+/YGpxvtGiqjqF7IPtQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVNNMHc5YXRiQmhoa29S
            VThsa0ZPVjRTTDNMUHJpTG1BL003R3RLSURJCkNEMUlLUk85RGtVRGV2QWxkT2RD
            dGRSQWdtV1FsaU5IaUt4ZDkySWQ3dm8KLS0tIFoxN05tZWI2ZUxyUWV1aUdhSXov
            c0luNEdoZ0hCblVVQW9XaWl5UEFrMXMK32jA3219GCvu25MnPwHxx5HJVaXilDos
            cvty2iCogMNYzUJR5JAZr4WnLVpDCc9lopig5KqTzLv8mL6B/+Pjpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZU05M2hiK1V5MDkxM0lu
            MUxpUUUyK0E3UjJPblFhK0pmSHQyZ2lJZjFjCkp0OE5OWk9JRXZGOU45YnJmQ1ZF
            Vk1oWmdnQ3ZPRmIxWXVGY1RPVVQvV2MKLS0tIG1sODA0RlpDaTg1OTFiQU9IM2tO
            M3QxeWc0R1NuNjZ5QVg2R3FtRSt6MTQKbSpntRckZRwponVfWrTqrIAzKAeTyf72
            TEsR5kuCbJN45qSJWF50PcfBrqRI70/ydfUJH6TKzSJ92eWWu2ENEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaU9iUjhJZEN1c2ZFVnpD
            VklwUS8rSGZrRTBuR2dnYVlDS2hsaHExdkRzCk9tZCtTeVFEQlZkcGRLYXJFYVZC
            U2p5dk1HMWxkRFVGdEl5QVkyTjhINmcKLS0tIG41V1BkZUpnMmh6ZDNlK0g2Z2dn
            L1FhdEpEd0I3V0haRk9JaUNNcHR6R3MKzvpAhwlUVN+AbYXWatqq3OazOCd3QBas
            r4Xz7GwUFOEgRWTEn4YyYXPQ1Tc5MWrcL3DF7EQ8oVD0tcEvdD1UrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUG4wdGdyQzhFWGcrRDI3
            SEZDa1lGeUs1U3RoczFCRGdsek5SOS9PS0NJClFJWGsrNUZ0akxhZElRWjJSNWlZ
            M0FaNlF1RDMzN2ZpeWh2ZE9hd2lGRTQKLS0tIFkxS0p5NXFEa3hBUGdCZ1BYRU9T
            MXY5WHhIaVRIOFVqNlN2UzBaWlk5ZkUKXgBIvnb8xUKuQikTb6E9tsaYKW7uKioj
            o0t6HWF0e6ETPet2BqXCSBswUR7JpXUu8sft1yub3bGY8JMjZwEzGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:17:30Z"
    mac: ENC[AES256_GCM,data:4BcBAs8f504ctNMtT1Ch1rsB0t33nSZZrlMgej/OIDEWBzpMVvl4tGO71Qe751KCVW3xqFWjmZdq9sinBHAlikjgzmbWT02QdtccVdlkYQQhwP2fhEocJPoltn/45RJ9s8JnOhCtb0e4diH5ts4mnBkiN/+i0A0Y3dMlxZGww7w=,iv:dp6e0bF848I1AUnxFOeuxRb8uZhOTD5Aozh6KJhJ9HM=,tag:xadmg6KdhhnEZkIlF8tbDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
