apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:1YQkBLwgH0YXiNAoCK0m8lLWCpibGJSdX+UYrsb8NPmF2gGrsQ==,iv:FuSzNW/OnWi8CAO+oJA/ddHmCoxsCP1LWHJXthyS59U=,tag:R651BNT2aVcALcuIw94WJA==,type:comment]
    token: ENC[AES256_GCM,data:GApjwAVh256N,iv:CJZ4SDhmk/+KZ+XDJj7ZPW2F70FyXlXFp3+8z8Gg0kc=,tag:WOORRQT8r/GZyzYNz1N1fg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdWlHQmxwNnRFczQ3ak9R
            eXg1TmFmSnp6cWExWVRQWmhRcmZxQ0RjYlM0Cm5BYldtNjJhRVdXbjRyV3dnNVVT
            M2tzZlg2bGdQdUNrdklEcUxvNFExWE0KLS0tIHdVU3VwcUFZZFVDR1lLNjQ0TTFN
            RHBQTUtiTkI3VTN5WmdISmVqc0FCc0kKHY4xJ/gCbDRq0HOXsKO5pyeZX9jXUXUr
            NC9sCMi/J64Q8SNM8BEp0pMk6W+Io/2E7Gc8B5qqLtkQQS5SkZ+bJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQVd1Y3FiU0JyS2JrelM2
            QkE4ZGFhNVFLMWdDMHdtcEd2Snd2Vnpnd0NZClpHMkhmWm5rcHlic2VxUGx5OWU0
            Z05FZjFFZFhubmczcTRjOEN6bXVVSmsKLS0tIE9QTDdKYzBVd1BIYXQrZVRTakpT
            dXVQMFUvTDVzS3pFTkh3ZzdUNDdKKzQK5WLCoL+buXlcWmZ6a8BswFNoaqRrZEl7
            BcEEwICQuHsMBKps8Gu+WQZWlDTHL6tqMSrqstbjUukISD7sQV4kuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQTloS3RpUnEyK1ZRSlpQ
            QnFNLzR3TjdhK2h1aFZqN2hkdVBSUW1uNlg4CjF4M2lkTHlCUVA1MkZkNVkyZUFl
            elcvZDdQS2g1NjJ3Q0NLK240OU1GcXcKLS0tIDFrZFRXQngyS0dIcFhOQXFzcXd2
            azNiSE9YTTRXQU9OR09QVjZiQlFJRGcK3llSXF6R0qDMsucQga8vSU4ySjr8qfka
            4XuvsVF8yQBDMDJrCGb3nboZtsZyHtsLkx+XeyZo4ueuQq3TYzz2AQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQzNtTHBEUVZQdmxIaHk5
            cDBQY2F3MzFKRG13ZktCcjlOY2dDNzRLdlJvCllxbVdEaDNsZWNWbUFDY1FjNHFz
            aHpVTU02QW9tbVp1TStJQnh2aUdCaEEKLS0tIE1sMGZGTVFxcUdldWl6djA3NnVR
            by9yR2pCaXhjL2tBWVFMS1pNMzIrVWcK9UQ8IPvnzH5e99jSzlL1b3V+ZxAEuHyW
            ZJbx1Ml4V9ZVoRtnWv0ENXKxsO7BJuSFPSXv0SsWpqRE0XbExf37Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMUhnSDdmWk9CV0c3b2dV
            SmFBUG1wNUZLM1F6U2ZNMDdtdWIyUGc1ZXlZCldIWGRqNVBaWU5uUDlTS3ArM24z
            VmtaU3I1cFVIUmI2NDg3K1pjSFFzZWsKLS0tIGtSVS9qK3hiSjhwZFpJcmxjRjJq
            MVFNeXpoU0V1SFVZM2pLTy9SR0RZN2cKcPWVzMH8kP08J5XarGhkgix6NtbWNGE+
            r9tOW22xBsVoHBV+kFOuyGe5KqRgV9RmfUkKn+mlf1wNFzAH3JZ+sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T12:48:13Z"
    mac: ENC[AES256_GCM,data:EbSssz8/HX49qKjSMivloevTerPfbOBeJD1UrofvBnXI6vzpKsdMuVWeDI5BYFZ6z0XltK2eAbroFxCD+y8eEX3/0FrfZuTqH32xtGt+pvE0aME4w6osuzMaypoHff8e0S7Yl0naqk0LcfxkPXIBWCNq/1gK4oIrpSm0fQglHjw=,iv:aIRTDzrukJonCTet0LY7ac8rIusHKDo9AR2Uqz1/2Qs=,tag:WnGGTxv6uKOr7Xgo2zcnYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
