apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:XTnXiU9c8GJgWHxY6eYvT7DK4P6+yJbberbiXvN8eNSzvrQv1g==,iv:G08aRfYWasnKv/9OtpYoRKxrdkSC7cr/qR2Ez2vYXMQ=,tag:PPylUTO5uiu4op8MTphQ6w==,type:comment]
    token: ENC[AES256_GCM,data:uUtPzUVVyWp1,iv:h0c1DMJHjVcbe0SM5/EQplzZH9WJllWyKvVVqD/G0Zo=,tag:EvwaiOSYZzArK6Ak/BELLQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMktEZWQ1RTgyL1JaNFpz
            dVZ2cXlQemlCb3Q2RHlUMEg4N2hsMHMyN1VBCjU0Ym5SQlhRSU04WEdOZ3piUzlC
            aWFnNER0KzdZN2ZUM2IvaDZtL2ZmbVkKLS0tIERra0VjODJZdW9Gb09CQ3lMWmFX
            UVlaYlpwWGZROUU4STB4VytyM01KYncKcyd7DLggSzR32/gE/n+ndCUu8nZXZ5vp
            bHB/Ie2Q+43qNRIXOb5Z+AcYCOEKBBVupeIgidQosWgoljUFLIjCGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZWszdkVicXI2TnppWlZz
            U3k5Q3Q4T0E1bEMrZEtZbWx2Tkc4ZGl5VVVvCkhMVjZVWlFtNzFSSzgzWjJGVWdB
            MTJkTTFOMVNLTVJ4MXZXQ1FQbzRwaWcKLS0tIGxmZTRVVGE4QVhQT3NQNHBJeXFT
            RE4zTTFUWm92QVlDdHhIb0JIeVhwdE0Kpo4s5QBTZrsC8TJndhtXFTdpdLxqlR06
            +uphCnXU1PqKJGAKoX43AgE95sDfp1mq5xmSQfjxTxCtGyDjtzoMFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRTdrUllqZllKdEF5aFFP
            V2hRMld0cVlvM2tqWEtielhQTDdpQUJrVXdjCktrYjMvVXQ4dGlsOWhjNkhnQ01h
            QW9UODlLNDQ4RXFlK2twc0tGcnQ5U3MKLS0tIHNvRVBrdkRIeFI2bU9ad2ZiaHZy
            L0VPU1dDSEZxeUlMYXUydVhLMU1hNHMK2+m9QwxdLKm7tJzViD1xZB7bkLSR6DEJ
            ISJ5PGzek5lDcTg5nReRZLNwSuHnLwOZRyHTG8kiX6X0viMiJH6GLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByLzNSb1pmNTJMQlgzQStC
            TjBicE9ySERmSlJkd1VzWW5ZQ1I3K1FGaUIwCmVoaVBrelZ5bGk5QWR2Q0hZam9R
            Y0hJdVBmM1FSVEp5aC92Vy93WFhiRDQKLS0tIFQyVmdIQXB4VkN0VjdhdVNVZWdT
            TVZrUjFpUUJXYkRqNytiUE8zVnFmekEK5EqJSFB4VaCVNUQR5IBIMND3Rq23cSC2
            1zfE2ORHmcis9/CLczdKwYvND15/nP+ijTfN97r62KLeB/4UG0rNUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T13:30:35Z"
    mac: ENC[AES256_GCM,data:TgYyidfolxwT1KTGlnU7Vd4gazbC0qtvKixTSPyXhzY8DQ5t6mHK1w7KxSeEmbqlYSdj/8SHzw1b7vRcz5QFUB+eHwiNu6nnydZsCV8nfxfI9wHgwwisnPC6cJodD0ZZfoXTy900D16ydjkItIg8UvXld0R3e5mJTXK7t0B0E4I=,iv:ZkHQIH3F5gWeFaFd79KqaYN0ejkSNgm9ncJqktYIyxM=,tag:ZbSgKr3EGffdX+eH+EJ7Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
