apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-app
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:YpPorZjx68dgpQhclMCAMJ4zv0FG+qXCMbqMcQXbg6/3h8K2uQ==,iv:fRe6tGAYiidUI9VRvhsTSXQhSjlRfOblt+bzk7OKoa4=,tag:qOsgHxa/Jx3uFrd6FnQU7w==,type:comment]
    token: ENC[AES256_GCM,data:a7BrDnpSCMDW,iv:k5tr7uxqXwMcfiNwsjM1DXGDlaEZLypTUqS5s85K16I=,tag:c1jWQSxJSKh0tB0aztSLSg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRit1OXZIZ3ppdVYzVHZo
            QmZsZ21DbExkVVFnYkNPRmFOVVRkekRxeHhzCk84MXkyVTVxLzkyQnZTUlE5Tlk2
            ak1YbWhVa1RGRXdORkYzNmprUHE2eTQKLS0tIEg5Wm5VTHUrbWJEMXpwMXMzeHJa
            TzMxSytZMnpucFBtUlVsMHRPcW9KUDgKUZeXeJlKTFFE6lOh8S3Ts10nncqpjS2y
            KA8Y2Td00x9E2QtOi2Dn2izoh5u9mJRGSgslrmnFaftPt0lQnNfVKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUCs4YndCTDdoZk1lVmNl
            T3hJbWtuSmY5eHNFQUZ5NytIRVNYcTh1UDNrCmhWQzVSM1BvNlFYRHcyemc2Y3lv
            TTFSMTJuNW0ydFdPUTkwRjNjd1J0elEKLS0tIC9QeWc0bXVzb2JVL2ZRWmk0M2tv
            c2xWUGY1TGY2eEltblI0TEdBUlVINlkKVHfRWsxK1lTOHhY5eCFbKswfU39y6lOv
            My000t+Ijw4T3jRo5HPerVVe7GvW9b6dgHUBn3M8G6JRxSjbjmEfeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnT2FOYTVUa2duR0xYcmpv
            T1dzNTBtbDFBTDZyNkZOYk5IY1pPUXM1ZWtBCkdBYnpHUlBreklsVm5kNXM0TmZH
            YllEdThVajF3UWlsSllvOENheC9XdE0KLS0tIEh5MjhIM1ZRWHc3bWFXam01M1By
            d2ZwWExoNldpTDErTmlGa2liMlpUSmsKA1siSOJhF5XLhZh7vUoN9qwfjdSs74Pp
            RyoB4WyFRcP32kjTUvhCIbXTir1Gcy7oypSTnoehoH2vd8kYC7WOTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONWlOa2cvVWYwSndBRU5N
            d3FUWXpZUDFHS2R5RzlKWTNVUERDUmJuMWw4Ckc4UGNIUkFSeUZES1VPcml4UjRu
            SThBeDhlOFJaU3pLVXErbDdxNTJnc1UKLS0tIGZSR0ZZbXZVVXhIS09GV0Q5d3la
            RStON0NDeUpHQmZEaFF0U3RXQzNnMlUKQxuZ/5QWrsEXgdn+MZB9dIj3SiQG71hH
            8Hw7vksZ+YeKGkrNspJR6CDl28njDcJmgWVCS3dcdTXCjMja9B1ybg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T11:38:39Z"
    mac: ENC[AES256_GCM,data:7DCqoXcLuC4jloaZDxkGMe8YNMcu6cyvBihXjS75Bwr8AjqkR2Bmm5BncacKrrIxRMF7d0nqGI1XjMkXHh/DXittBgkD/lFdQTxEXuF+6Ph3nxtud66pRGpdNApUiPslBGLqloj4d3r5/fb1e2SFsqI4i+4v4h6XDD2wJ1tc50Q=,iv:5sNINeiZxhshZYRywWhgqMAxCnNcl7fA05Q/60LetqU=,tag:laHxdNNqEwJOqVPf9okwmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
