apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  chart:
    spec:
      chart: openbao
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openbao
      version: 0.19.1
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: openbao
  values:
    server:
      logLevel: debug
      volumes:
        - name: userconfig-openbao-storage-config
          secret:
            secretName: openbao-postgres-storage
            defaultMode: 420
      volumeMounts:
        - name: userconfig-openbao-storage-config
          mountPath: /openbao/userconfig/openbao-storage-config
          readOnly: true
      extraArgs: "-config=/openbao/userconfig/openbao-storage-config/config.hcl"
