apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  chart:
    spec:
      chart: openbao
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openbao
      version: 0.19.1
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: openbao
  values:
    server:
      logLevel: debug
      volumes:
        - name: userconfig-openbao-storage-config
          secret:
            secretName: openbao-postgres-storage
            defaultMode: 420
        - name: unseal-keys
          secret:
            secretName: openbao-unseal-keys
      volumeMounts:
        - name: userconfig-openbao-storage-config
          mountPath: /openbao/userconfig/openbao-storage-config
          readOnly: true
      extraArgs: "-config=/openbao/userconfig/openbao-storage-config/config.hcl"
      extraContainers:
        - name: unseal-sidecar
          image: curlimages/curl:8.5.0
          command: ["sh","-c"]
          args:
            - |
              set -e
              echo "Listing mounted unseal keys directory..."
              ls -al /unseal || true
              echo "Waiting for OpenBao port..."
              until curl -s http://127.0.0.1:8200/v1/sys/health >/dev/null 2>&1; do
                sleep 2
              done
              if curl -s http://127.0.0.1:8200/v1/sys/seal-status | grep '"sealed":false' >/dev/null; then
                echo "Already unsealed."
                sleep 3600
              fi
              FOUND=0
              for f in /unseal/*; do
                [ -f "$f" ] || continue
                FOUND=1
                KEY=$(cat "$f")
                echo "Submitting unseal key file $f"
                curl -s -X POST -H "Content-Type: application/json" -d "{\"key\":\"$KEY\"}" http://127.0.0.1:8200/v1/sys/unseal >/dev/null
                if curl -s http://127.0.0.1:8200/v1/sys/seal-status | grep '"sealed":false' >/dev/null; then
                  echo "Unsealed."
                  break
                fi
              done
              if [ $FOUND -eq 0 ]; then
                echo "No unseal key files found in /unseal (check Secret openbao-unseal-keys)."
              fi
              sleep 3600
          volumeMounts:
            - name: unseal-keys
              mountPath: /unseal
              readOnly: true
