apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  chart:
    spec:
      chart: openbao
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openbao
      version: 0.4.0
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: openbao
