resources:
  als-config-map:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: als-config
    data:
      relay: |       
        receivers:
          als3receiver:
            logs_address: "localhost:4317"
            log_endpoint: "/logs"

        exporters:
          als3exporter:
            endpoint: https://canary.als.services.cloud.sap/ingestion/v1/event
            cert_file: certs/certificate-chain.pem
            key_file: certs/private-key.pem

        extensions:
          file_storage:
            directory: /var/lib/otlp-collector
            timeout: 1s
            create_directory: true
          health_check:
            endpoint: "0.0.0.0:13133"

        service:
          extensions: ["file_storage", "health_check"]
          pipelines:
            logs:
              receivers:
                - als3receiver
              exporters:
                - als3exporter
