apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql--post-release
spec:
  interval: 1m
  releaseName: postgresql--post-release
  storageNamespace: services
  targetNamespace: services
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  dependsOn:
    - name: postgres-infra-config
  values:
    resources:
      openbao-postgresql:
        apiVersion: "acid.zalan.do/v1"
        kind: postgresql
        metadata:
          name: openbao-postgresql
          namespace: openbao
        spec:
          teamId: "acid"
          volume:
            size: 10Gi
          numberOfInstances: 1
          users:
            zalando:
            - superuser
            - createdb
            openbao: []
          databases:
            openbao: openbao
          postgresql:
            version: "16"
      kms-postgresql:
        apiVersion: "acid.zalan.do/v1"
        kind: postgresql
        metadata:
          name: kms-postgresql
          namespace: services
        spec:

          teamId: "acid"
          volume:
            size: 10Gi
          numberOfInstances: 1
          users:
            zalando:
            - superuser
            - createdb
            kms_user:
            - superuser
            - createdb
          databases:
            kms: kms_user
            registry: kms_user
            session_manager: kms_user
            cmk: kms_user
          patroni:
            pg_hba:
              - local   all             all                                     trust
              - host    all             all             127.0.0.1/32            md5
              - host    all             all             ::1/128                 md5
              - host    all             all             0.0.0.0/0               md5
              - host    all             all             ::0/0                   md5
          postgresql:
            version: "16"
      keycloak-postgresql:
        apiVersion: "acid.zalan.do/v1"
        kind: postgresql
        metadata:
          name: keycloak-postgresql
          namespace: keycloak
        spec:
          teamId: "acid"
          volume:
            size: 10Gi
          numberOfInstances: 1
          users:
            keycloak:
            - superuser
            - createdb
          databases:
            keycloak: keycloak
          postgresql:
            version: "16"
