apiVersion: v1
kind: Secret
metadata:
    name: cmk-krypton-bridge-db
    namespace: services
type: Opaque
stringData:
    DATABASE_DSN: ENC[AES256_GCM,data:3NcGnG1wfDugGc54+VUC3pmbZ2NpNF3t+yHEk5YRe0I3dAMj9G4vjoeOc7DVICr/6I9Z5jKpZWMfBQRK16OmLK8kcvMeKCJv1HwO9K4PMFEkpWQVt/seoVZoSPRDMeQ5XjjK4nI3FVeP+ZKMrt4=,iv:iLFOdVftQzV3U4zxTZJpw5aEYsIsfN2wr2w0dZLw+B8=,tag:xsZ6b4NeCdncnHjwYq5H4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMlBsdjg1WlpjcnFtVUxU
            MExNeHpFRk1HOHF1NE9obGhRVTZWZGh4YXhVCjBBTWpRQWdzWDNFb01vMzFTbTd0
            M0tFWWlSbVpHK3FPNENFN0hxZTVOWHMKLS0tIEp5aHJPcFJ0L0NsRnB1VjVjVkFr
            YnhxL01aclowSVlmYzE2MVllQzVUVTQKRrUZxM01iIE6819WrzLADsR/4uo5Bi74
            7zSTH9mhZ6BCW77oSDX/ElaF9eceDQb3D87LVxDME6E1mqSTZqGTaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU1ZOeGlNQkk3LzJuWjNR
            aysyUjZTSUdZQUc0TXdPOGxUckdicEUrdXd3CmFmdVdLSW1SWmp6SVBBWW1vL1kr
            ZFdvYnJidWtsS0tXUUdudVBRUUdKajgKLS0tIEMxY3BnU2xOSlFMemNhNE9od1VF
            dG9uMmliTDB6eFYrYTRieGFrZ3VkbTgKe2S8R9DJ9ayxbtA1t8G1xFbRtjzl61dn
            WYtofuQDPnMhzfHIwQo2SNr4e5m8XYjyQ11zWBWOhMM27O1SbU0tHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcS9NaU1OZ0xVZitLTHNW
            TXFwSURxM1N3emFUb1dRbTBFVko0L1ErbXhnCnFYUUVtQzFkdnMwYmxOcStKcHhi
            eU9lUlFkdzhMSEREcjNDOXl6RVU4SWMKLS0tIEgwU1dxTkJ6RHNRSGRsWEdqbkFm
            ekt6NEtySll1aHBLd0lvenorWDVMeVUKyWsKTHUUEhpsKE7gLrvDr1QihspCPCkp
            aVXIhMXnabpoC3j4Ntvzlav48pdvv1VLGNNOJqfec7sg7t9yl55YaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OVdKN1lYNkhBWHpma1pK
            ZXk2MkgwSmYvNnkwVzRzaGdNL0dzdmFhNzNBCnVReVhydW1lUkRnaG5QOFRlOGFJ
            TDRGaDBhckozcUgwc0ZaRWpxOUZXaDAKLS0tIDg2bHlKMnllNmhmVm8ycGZrMXpR
            MytaMUpCNDIxaXFjUVNqME5MV3k3N00KN9F+qEYnYHopL6dtEAqrj7SheeoNT1Ut
            hCXOBdHMsnHNTk2P8pKKweVzkE7c0U62cny0h9sFmL95PZtIjpIUqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd2s2UkdtMitBKzMxSmdF
            Z3BBTWcxOFB1T0hoVjhidjFtUFMzS2ExYmxvCkEwZ1A2Y2FMdExaVkFlZTN2WlUr
            QmV6Q3BuME1TakR6Z1pSbnhWa2dmbWsKLS0tIEFHTHE3cHBIdnhONUJRR1dXV3c2
            MlUvd1BhWmVwNjdHeWNkYVlsTW11SzAK9eatDrmyvjve12VHmkQcx6NCZWPMIGCh
            2pCTznPvhvdwJkmEUtmlpiZ/rutepOcEDzGOhUNh9L/lDRGxiYWNyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T06:39:11Z"
    mac: ENC[AES256_GCM,data:RChpDHMg/Z8LWAG3ht2biTy1ySnwXRkJZLtj7AjcBn2HAK31QzC85daXd8mu4eyJcCZvgbLEFevvmU/bE9eQwCaYONS/2nkEPEjvtN+pJtEHdNMQWjDxhRenwz1bNdg6xCPx78GUrDpnCbkMQCuHGuetjT0TnB3w0MYR1wtL5pQ=,iv:pWhdd6WT5q9jCUheWaJOP4NoPpmnn6AwfHiC3GkhBco=,tag:0wTPavdyrIeYO+AzeYUyiw==,type:str]
    version: 3.13.3
