apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ui
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cmk-ui
  targetNamespace: services
  values:
    fullnameOverride: ui
    imagePullSecrets: []
    extraContainers:
      - name: envoy
        image: "envoyproxy/envoy:v1.36.4"
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "60"]
        volumeMounts:
          - name: envoy-config
            mountPath: /envoy/config
            readOnly: true
          - name: server-certificates
            mountPath: "/etc/server/certificates"
            readOnly: true
        args:
          - "envoy"
          - "--config-path"
          - "/envoy/config/envoy.yaml"
          - "--log-level"
          - "info"
        env:
          - name: ENVOY_UID
            value: "1111"
        ports:
          - containerPort: 8443
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 300m
            memory: 100Mi
    ui:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      image:
        registry: ghcr.io/openkcm
        repository: cmk-ui/images/cmk-ui
        digest: sha256:26d7af9d9857023a33a33c7b2b42a1e0c5bf73f24610a7b196595e98e4296425
        tag: v0.5.0
      service:
        type: LoadBalancer
        port: 443
        targetPort: 8443
        annotations:
          cert.gardener.cloud/purpose: managed
          cert.gardener.cloud/secretname: ui-tls-secret
          dns.gardener.cloud/class: garden
          dns.gardener.cloud/ttl: "500"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ui-app
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ui-app
    global:
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
      volumes:
        - name: envoy-config
          configMap:
            name: ui-envoy-config
        - name: backend-config
          configMap:
            name: backend-config
        - name: backend-config-yaml
          configMap:
            name: backend-config-yaml
        - name: server-certificates
          secret:
            secretName: ui-tls-secret
            item:
              - key: tls.crt
                path: tls.cert
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
      volumeMounts:
        - name: backend-config
          mountPath: /usr/share/nginx/html/config/config.json
          subPath: config.json
          readOnly: true
        - name: backend-config-yaml
          mountPath: /usr/share/nginx/html/config/config.yaml
          readOnly: true
          subPath: config.yaml
