apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:xGx19eZCKBQ=,iv:arI1nemXz7Co0Cf4FYMDXFJKv+JiX6OEguQdG/w77FQ=,tag:VAt3RbP1WgbjaTGdkfwh/w==,type:str]
    postgres-password: ENC[AES256_GCM,data:JPn7eU4ATZuXpFjiV+3y2tB2jrs=,iv:Hck628/yt04qLHdvJpm0EVQUIsl2Xq6qthtIQWPuwic=,tag:N+ZL+S/96R+JiJDaM/Mm9Q==,type:str]
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bTZwMFdpby9Sb0lLbStF
            N1FsRDM0WGpXVGpWSEgvcjMzZ3F3MVkvZUJFCnpNUFJKSERNa1lnVmd6TUtiZ3ZO
            VFVMbC9mV0paYVBzUTJCTmVUSHVlU28KLS0tIE1YSjJDSkpzekczdnJxdHJ6OThx
            VjhyZHR2NTJUQ1p6aDAxRW5vc3ZGWW8KCwqEcCOfl6iyqEIbjmof3ekSv75RLcBx
            XYJk+n3tSUZiuw0iP4Ic2chncLQthLnPAs/djamwgY9lnJySdpwWEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c0h6RzlEbzU3SkhhQzNN
            aW9xZEZRdW9tZ0xwTzR2cmhRZ3RmRVhwQ0Z3ClpidEx4ZEVZWGZXVElSVndkRWRm
            dTFVdW9GZkdmVk9zMFlQTUN6RDZJM3cKLS0tIG5OcEw0dStyeE5QcjJtYnFHTERh
            cnlsVUNZVGUwcDc2cnpZK3RicjQzWW8KmbjNgyq5w1YdQgaOS0wJTF78DhdXizl2
            hT4sUWWO7C4PqpCHtuD8sEQ7OPiaK1Ub7R3dmMwPquPt0P8XT6diXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR3pQOWhLdjN6cEtyVTVD
            cWh5ZzN2N2pIdVVlZm5PVTQxUk5EWEU1Z21FCktWRmsxeVN0M1dxKzFYcjF0V0Zr
            RFNtTFJ1SlBlRzFKMmJTZG5CakJ6NlkKLS0tIDVYVzVydVlVWGo1UTFlZTR5QmN2
            ZFRiUlpUMjBuQjhHTTVSbDVsR2p0UkkKcapAnWVcQ3iEuOvyZux9CI7EkKbIYouU
            N4Jw/GzKVpv12+yMmR4jRW6D+/TdxdObVthUXbRo4Y5wP3OnoctBfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbm15SjNIbGZUZGo5a1BS
            L2E4T0VFcmY1WjVyOW1QdWdkUElnbWlKckc4CklOOEVuNXFKTitQSHNWbUJja004
            ZjdlazJGcmZyVjcrT24xSkN1YlVEQzAKLS0tIFRRVEsvL1h4TlJUSFBwZUViU21l
            NExQenlYbjNMWUNjei9POFdzUjRxZjQK7kH4XJ0vDA6ov8Gid8z0TQzw2b1aFwsX
            UJMtpYNa0uAYuU0koGmaXAvo4fBresZ4OzYpOy6QtCptoI9CC32hrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T14:13:00Z"
    mac: ENC[AES256_GCM,data:CzkhzZiCZHquyiJcO2bzB7mviylWjvgbVWAMsuVd78WlvMSL2dKo6msF7+p/rhVlU3AOUuL+nXvujTZRSypVG+hl72Z4d3D3CmXA0hoGXXzeMe5yPldkCtphsMXqrU6glgy3Wba3JdF40EpEWg46nyC/fGhcWlfLkRu5wh+VLrA=,iv:Sb+5BsqgvNYtqgORQBuzvL6FQPaNX+8wltlsL9lz/JU=,tag:FgV9aAkfPADx17xHtnIZ4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
