apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:2nb4aqePxKKXAxlwveo=,iv:ki4TFn6/NdxI2XJSKBdtLmYgLTGXIWEhY38SpbHP/sY=,tag:t3r83ivDnQMhnHZPmEGJ6Q==,type:str]
kind: Secret
metadata:
    name: keycloak-credentials
    namespace: keycloak
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTTdrNy9SRkFVYm5PeWw4
            bTV5ZW1wYlMrb3ZsbkZqSi9yMHRnVjVOaGxRCmczQ28yUktvMWJXb3BpQzdqWUNQ
            M2lwS2xrdmE0VEpPZENRbG96cTNha2cKLS0tIDNPa0xmYjY2bERVNDNSOEk4RmpD
            a0ZMejd5V1RLVlVETjFlVlBQR1NtNzQKGdbP/NTqQhWxzrRjsRDoRNdLMNThYon8
            WY9BROn175xN9ht+xbWmJdJgLtyVC2NSMsK+lLAP9rnib1v0G9AGLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNnJ2ODBDcWNOOGVmdnVk
            b2lteWhyY1lrVitBTTlOTHBkV2tFUllIWTNjCk11eU9UTExZcGJtMWZpVVZEQy9Z
            UWRrNEtSYjFwUExhb3RXRE8vRVp6WE0KLS0tIEg1Qnl3WXZlVkYvMHhwWmZ0dTdD
            d3orOHpNbkJvYVhLWEh0T0NBT3RlV2MKRwM7B1RsDIgtoRfzll7W68foDxT6Sf9A
            nRHwu5GvO1QZ/TlDBeZfLm2k3bpRdmRB/W/m+ZPjD1X/Aj//zifPig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUlVGZ0lKSmFjcmFhU3lN
            OE9URktsdHdoeWpkbzdGZnZBN0J5WEZtTFE0CnBiTU9SUVZNL3YvWEtBV3p4RG5V
            Z25DbEsrSHI2UzBOVkZkTUdNT0RkYU0KLS0tIHhRT21oWDVocFNkWHNQcDluWW5D
            czk3UFNBRWUvbERMYmsrenZWR05rQjAKamFTXXhXsB8UCtGeDeesfZGeNOHOyf2y
            01+URGKF4oQ/JfVjT/w2pFx4yhRYvluoyxgAEPJP6qxGJiv+KJ32ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcCtudEg2c3htNFJNUzgw
            NWZDRnNyVWZHWmZYamNsWk5jZ3VCbzR1Nm40CkxXMzVob1dpVFF6WGFSVmYzUDdQ
            cDNOWHBCRk85WFI2RkhFTVFoRzZGKzQKLS0tIENrMEpDZFNOdVdoNitjejlvQVZ2
            V3U0eDJ1ZmZQVGNUYTB3L055UTVOMU0KN5LUzytfOSkRtxeAlt3Qe6lAhyIvrQJK
            kCGy8Pp/D9f/LJYuWw5WihkrhkFMKiRfwPjTjCBUfo4kR3Kbd4h9Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T13:11:18Z"
    mac: ENC[AES256_GCM,data:pScmRl0fXDU+FUuljo7qRnbef73LXi8NGGSdVtr/qawT+n8SPqPJ21fhp4KiaoY2p+kgBvYyMHJkQzRliGx3rjRAlWnj0owdefMq315j6wlPx5/wXzK/ZdS+2M3Jfhq1rz2MDqyHW5rmF3ji4toYfIrKTbCp+zjX0kPeC2REDE0=,iv:XUKzGxFMhaZO/vAF8QWjlkjJPnlTTB1/5SkkCr1nXdU=,tag:qtaRupXWiuLL5U92BkqUtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
