apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:kurKGTIEZ4laagnH/QWPOgtNcrICgzAiYL3Cdg==,iv:Il1dHniFkhy1cJ3g3I18Acdxk3R2R1ET9Ov9ryCVdd4=,tag:lTRUhLe2b0KS4VCb+56PEg==,type:str]
    postgres-password: ENC[AES256_GCM,data:c+gztjGXiiPVMRZ7DLtHIGSK3yQ=,iv:yZ4D6u7IV6cc3OSf8U/93sEBJsWIJG4jxttyiD1ao8g=,tag:aC91EiSaHapjrz9y8eCXqg==,type:str]
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUjMrYnRuOEFvS012Ykdh
            NmgvNXBiZHZ4VHB1eklyQWhsZjdpd1puQ0ZrCjZWR3haUE51TGhJZjBQL3FJL2FP
            UHdVdnN2OFFCejVKYXRtMFd1R0ZjOHMKLS0tIG11SnVtYUhoRWFLSTF4QldSZmNW
            QTdUT3BmZDFLUDMzNmVhVkEyL0tIbWcKJqr7ock5YdZuzMcifzTNtG1ISUoobuXr
            D6ZFU0hPqP+b7klv9ykNiKrNJYwtgBGhbUZIFsU65vSHTII610H1sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUGlyU0FNZ1UxMVFiVkcy
            andwRjg4VWIrclVYdTNNVmpiT01EVFJtQ2dJCnNMT1ZaUERvOXJMNTdiSGtoWE5V
            NytyTVVrc25VZldkMVJEV3BXbFdsRDgKLS0tIEhOWTRqOU14Tkwzd3JmMzV3bytk
            RWphWExSUTZPSFcraTBCSTRFY1crbjQKsD/Me7lgGCSbN94kcGsrajQ0AqMD+PZe
            u1K2KdZ4oaa/TbHga/67vtGTbChDSDyWOHFV8Ixs49Zygmm80OZKNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL1Ayc2dHZTRnOXVrNXBp
            YVZjdFJVcmhjTWFWNmlvaGxHamJxdGxkRldRCmZNNkY1RGRhSnhxWDJ0cUZFY1Y4
            T3c4N3lyWUlLS3lsVlVpUDBHbHZWZDQKLS0tIHcvSEZFQVpsenJzNEV4SWx2b044
            YWoyYUlobUZWTko5bXcrTThRdzd6SmcKdrvka3fqv5t5WjAQbiqYV+t+GoLz8hmL
            2x9En/WCAG8PjHbUkAQjf/5R4HIelVdJfZygP7EIhUms7vHWRx4HYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOWlhaHRsdEdmd3JuTENq
            ZjBkTnNuNEFsNU9Wd1VGRUJlL3M5Qy95T1hFClhpVDdGZjR5ait3aDBvdWh5NWFT
            NUhFZGgvU25kSm41WUNjOURnZVFkZm8KLS0tIGNqaEdaRDNmYnpGT3EvZGE3WVN1
            TFdJREFmbjVOb2F1Umk3UWlGbXA3c0UKcf5bTOCgloPYe1sjnQ4FHdGOHoKPV2YG
            ZqWbvfk74nxn+Ie5VQTpKnTJaDdZ2KjAF9xXE+rLGRG8+j7lkBBXqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T07:29:10Z"
    mac: ENC[AES256_GCM,data:nRE9htJmOBN7CFfK8wJgAWEgEBtmqKzXDN5qNzeJG/x0MP5+dKUw39h5qbPzAui6SPnbtRU9fI//YmMuxSsbH4KEeU/BHK78TKp6dICfD0/xPlLg+IU2GGFRe+tbd6DcaS8Y/4uKX+nxd0a2UqlROxraOxNYHrpcetbLUc/1WE8=,iv:PbxPz3DCmfWVsiFLFxilewgIwqF7b5C3cCSn46phpCo=,tag:vyar6W1t+Nyqq/J2ykMMdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
