apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: linkerd-control-plane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd
      version: 2025.4.2
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  releaseName: linkerd-control-plane
  valuesFrom:
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
  values:
    identity:
      issuer:
        scheme: "kubernetes.io/tls"
    proxyInjector:
      # -- Namespace selector used by admission webhook.
      namespaceSelector:
        matchExpressions:
          - key: config.linkerd.io/admission-webhooks
            operator: NotIn
            values:
              - disabled
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kube-system
              - cert-manager
              - default
          - key: gardener.cloud/purpose
            operator: NotIn
            values:
              - kube-system
    # -- Create PodDisruptionBudget resources for each control plane workload
    enablePodDisruptionBudget: true
    controller:
      # -- sets pod disruption budget parameter for all deployments
      podDisruptionBudget:
        # -- Maximum number of pods that can be unavailable during disruption
        maxUnavailable: 1
    # -- Specify a deployment strategy for each control plane workload
    deploymentStrategy:
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 25%
    # -- add PodAntiAffinity to each control plane workload
    enablePodAntiAffinity: true
    # nodeAffinity:

    # proxy configuration
    proxy:
      resources:
        cpu:
          request: 100m
        memory:
          limit: 250Mi
          request: 20Mi
    # controller configuration
    controllerReplicas: 2
    controllerResources: &controller_resources
      cpu: &controller_resources_cpu
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    destinationResources: *controller_resources
    # identity configuration
    identityResources:
      cpu: *controller_resources_cpu
      memory:
        limit: 250Mi
        request: 10Mi
    # heartbeat configuration
    heartbeatResources: *controller_resources
    # proxy injector configuration
    proxyInjectorResources: *controller_resources
    webhookFailurePolicy: Fail
    # service profile validator configuration
    spValidatorResources: *controller_resources
    # flag for linkerd check
    highAvailability: true
