apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: btp-system
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/canary/infra/btp-system/
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  dependsOn:
    - name: external-secret
    - name: cert-manager
    - name: namespaces
