apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd-identity-issuer-syncer
  namespace: flux-system
spec:
  dependsOn:
  - name: namespaces
  force: true
  interval: 10m0s
  path: ./apps/production/infra/linkerd/identity-issuer-syncer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
