apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  force: true
  interval: 10m
  path: ./apps/canary/infra/namespaces/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
  wait: true
