apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  storageNamespace: envoy-gateway-system
  targetNamespace: envoy-gateway-system
  values:
    global:
      images:
        envoyGateway:
          image: "envoyproxy/gateway:v1.5.0"
    podDisruptionBudget:
      minAvailable: 1
      # maxUnavailable: 1
    hpa:
      enabled: true
      minReplicas: 3
      maxReplicas: 5
    deployment:
      replicas: 3
      pod:
        labels:
          ingress-gateway.cmk.kms.cloud.sap/instance: envoy-gateway
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: ingress-gateway.cmk.kms.cloud.sap/instance
                        operator: In
                        values:
                          - envoy-gateway
                  topologyKey: kubernetes.io/hostname
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchExpressions:
                - key: ingress-gateway.cmk.kms.cloud.sap/instance
                  operator: In
                  values:
                    - envoy-gateway
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchExpressions:
                - key: ingress-gateway.cmk.kms.cloud.sap/instance
                  operator: In
                  values:
                    - envoy-gateway
