creation_rules:
  # Encrypt only Secret manifests placed under environments/<env>/<layer>/secrets/
  - path_regex:  ^environments/[^/]+/.+/secrets/.*\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age:
      - age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq #flux
      - age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52 #ph
      - age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq #jp
  # Encrypt Secret manifests under apps/*/.../secrets/ if you introduce per-app secrets folders.
  - path_regex: ^apps/.*/secrets/.*\.ya?ml$
    encrypted_regex: '^(data|stringData)$'
    age:
      - age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq #flux
      - age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52 #ph
      - age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq #jp
  # Add more rules (e.g. ExternalSecret) with a different encrypted_regex if needed.
