apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: extauthz-base-pre-release-values
    files:
      - ./resources/extauthz-system-policies.yaml
      - ./resources/extauthz-trusted-subjects.yaml
      - ./resources/extauthz-user-policies.yaml
