apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:hftC/594eYXSiiLccmlXyqOmGWHMr9QE6zLe/aQnbA/j7CqS1OPnqwsXVNs7WK5E6zXxUwfCbm7K31uz,iv:4THBuOYu5pTfUjpiA+3+KzFRjMNihqq8Ifk74LAgyYw=,tag:umgs6jUfP0q6TGAxn4QzTw==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:081a6W/cYqi7YV8ue0yU/t/Rw7g0wm3YtHEjZC5krk/0HFpVKIIF4eSl5+autlctJiYdTS3gzqn8F6Xs,iv:1VNQfa6Puy3p5x1hdkRvEjqy+gpVvjgJPPw7VpNTchw=,tag:g5TyNiiCZi8oWpz2/vUZNQ==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:B/5UKykEkq7ZdI/cquhHTE2UHST4J0tZuBZaa8vpAoJtVG9p7tcBYDk4DERkpLGW0oHR2k6Phc7OJKlw,iv:DnzYAuab6ViP6KgjZHahcPy3srFdy90TOQk+S898Z/o=,tag:Td7oNU/mI3SSEXjydOFrmQ==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:ibexa5b5l9US2vwxHkD6akYE2fivIEEyGwybWN7TFcinNdHhKk674rNtLRzz7zM52ZSYAV3HdxPuopMo,iv:SSNe0o+JE4+Xn7VPgoa45ai9ASKxSuVH9Ckugg9vlT4=,tag:mHgUmjA1a1M4NrNdpvF7zg==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:bg4w6D1pgcsz8JA8ynzP7QSANTYb/rvptIPbJWbH2gmLi6MSTIucnW3CrmjFT5gZL9U1dwydKa34+CKq,iv:HqFvgZfb1aGwTM2wpM3iFxMyxBHPEaMDkyUNvHXtY8w=,tag:gXKmpk4Vrd7kdmOR5Vc58g==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:On7KkuetfHhZOOhKTmCmmGvHsbGMfWdAQuDQIiScW5dz9VQU,iv:G/3NwBe6Z1KszFEZ+VTQbVOPQ8nad8Cj8J6XAi1Imww=,tag:PM/HaGlUW0F+l4H6rBavpQ==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdnIyYXRDT1oxMTBleGZR
            MFZLOElxTkpVVmtXWDJDVElsNzVHTUhPOUJnCkxNNTBHZXhqR3NVTUZ4NlljZHpk
            Sm9QSHdIK3ErZklURWpXZW02R0NoeXcKLS0tIDg0VHBhMDZ5Q3ZpcFhRK3FMZzV3
            OUpZYVZuUEN0TUVLYkRrTTA3aGpDYU0KE6Mmt4kL9nAMdRkG4CsyxUvCwKGYMCwq
            m3zPBC22iLXvDXAtjzyTXJvnzw9JbhCC8Zdcd/I1dpHKLyPt7aUnww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSGM0bUNvNlNNZ3kwM3Fv
            R2NITkZFSGxTY1hRdHRqdmFobWxsa1krclNBClU1bjdpTEc2RXNsWTBUaEVBYXpn
            NXA3UDhhbEgzdmNSZkpnNUhlRmlpK1kKLS0tIDlvaE1semgwQUhrWWJ1ZzUwcXlH
            MnVYb0pxMDVEMjc1dmVSNndnNWRYMU0KcyetqxywO9qhV16Y6xWb6jrrPIt1KTl8
            3/by3QXwg0RI4ipjkFfKVXnufd83DdGbqYf9UDnu7fVXCT5ZEt7kLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNVdGQVNqZUF1amZjQmYz
            TTN4UUVqN09xK2hKaWtqUk85b1prWTVQVHp3Cm82SUFHcnhLMEZSbVpERmhySDd4
            WHBkU2d1bUhRemVXMWYwTDBEYitWSHcKLS0tIHJQTElmNmh3ZnFMaGY5TXVLaFlr
            bi9LaElzaENSN0xLRVBEZktoRU1Ea1EKVVFD+/pW/O3XGWCukLBb10a09HxdjyKx
            JZ0BgazjJP5CQ1AXhwd8sLLStaGzYJNcE0bBLqX40AFMNIWzbgmE/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0FvME5ld1RzRlYvcjFD
            dU1Wa1E0ZjJnYlhWWEw0QmpWMXMxZFd2cERrCkU2MEN0ZElkc3ROVndneDRBaEc1
            ekZ6RzNlU0R3OC9Gbm5QVWhmc1Y2aG8KLS0tIFA3aXBWdDBZaFNNWThKcnkzWmR6
            dXZJeEI2TW5HaU11QUNzSkpuSDE4bjgKAYeZSz/LbM3DVrqEP7YtO+VqsPnewfq7
            QkiOoH3y6qqVpLqZ2kxH0v2abD0ATE9G+JdymoEijGokHr4CEEsPvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:03:14Z"
    mac: ENC[AES256_GCM,data:fFVZBkGB9e21VT1yxb+kpao5Ssop2eCpGvTAjfZaaG6UQLBtJsvGABrRkohrbq+U7cuTtU1UrvpxyP92VbBW1e5eAWVezHo44WBd8GAykGMhCsOk9eY/DgpNMT93PaKUr3FIk3kA2ryW+drEFqiB/H/Rjrx3+4la/v7o4wFoZek=,iv:g5oJUOGyyZyGMgP0a9MgvurltYt6eDRosMRI+2SQ4tk=,tag:4Z72fkN7tGctOHUBmFC4eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
