apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:67VkqtC0O2+lFRmd0alORfNsrLXBJ5iVrdA2N2cRP5vBkEe0lFKPjW5z33XkWLlf9lWZCv6NXAPcxyPh,iv:IE/59/kbV73Kecd4dgqwJXNfTCMo3GIcuGlfdgv6KNM=,tag:mbiQPF3yHDHS1K3h8wOlYQ==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:cTDA2thmczAhpGMPazJkar5j6OVB+h8tWLtrFOtG/Ly+h8iI85l3rRlMBhJdumaJQNQ7yYq9Fb+MlCXl,iv:QHPQrXI9iO/qjYyvHptPA8lqOzhxip7mdo98L3pYl3Y=,tag:yr8UHVDyBtut0BqS481UoQ==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:b9Anr5tteInQMeoujmcDoGR5J2CrbeuoXA83e1dnc9ZmpUMRP3KBPieqRB0nt4N47/BJBh5UO0q/V1M+,iv:YjCPm540vPq/CUgEb11gUuAJkdoV7mBhUte1kKEM6l8=,tag:oSXw9lTw0Plm5unXguiX7g==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:wPngL61cvBTfXMKl3nLZFhBGmobNzk29/dMrVtmpd1WPfKRuLLzTeMaBOWv/sUZy8gTF3Oy3HoZqvt8R,iv:1XTewXovnSCFDQVcjWP+dhP25dFEPdip2gVSvGf6Pdc=,tag:wPS0YqOlApITVOdbUjdVhA==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:cBTJeVOxG4j+D+xV94ExJTnry1RSTxC4CxEiKI4WQvGqg3FuDOVb340/96HCSlonzoFiijKsFH83ZybA,iv:gZaupQSQlAx1rsEmYigP6OlQG6IKIp++YkrwVVPsEP4=,tag:5xD9d8v0nJcFJgpafsJt9Q==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:ADNdx/SC1Wb/1TfHjE5QgNPdBw67OVGdnG9TyoARN3nY5ibM,iv:Q20rzX3eXqyU5+bXyXKhuXOuNSGzDV4PrvHyz/aAwAs=,tag:s3pADTnslVqlpRl9KbCLfA==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWV1U2Z6NG53bUo5d0ZB
            ZFlpUGxqZk9EZWpUVjN3WnF1UVNyY2gzcTNzCjRkc3R4aW0zYjRJU1EvN2pxUW45
            ek1kOFZLMEJnU1I0M3UyZjhYRUtLMGsKLS0tIEJGeHFqOVUwREsrNzg0ZXFRQyt3
            MjBvZnZNd1d1cm5saTVsZXptWG9KWWsKYOSc9qdErsV5zRyo33ATslcRNRWxD1so
            uvqkZkDRQoRUgyxKSrGpDPay6pzCLEzfjmwj9oM1Ud4P0OF0JiJ8Jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU0ZVOCtjSjFJWk9UakJL
            eENqT0pGbXBNclRDNDU0eTBUc0ZhQmNQblZ3CkVNU2JPaGZxMCtqSXQrWVVrR2JN
            dTVUSldlS3Nrd1BxMGVrR01IRXlaS0kKLS0tIHJSeThtWUVaUTladHZBRlpIZEQx
            T1BIWVoxYlRyWHRXWVdQemtRU0Iwd0EKbidjoctC8aq0Y+PVABEDi8KHJPAkPRX2
            qD8cvTUhYEeyVkPh11vICVwcrko6f3b0iauWbx8qesHmwgmGRU/ORA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZW92eFBWRDRGZURvYWp0
            c0ZTb1hmeE5KREdiUkorRzhDM2tmOFFpVnljCmhuei9jYTU1Z2lqeGpFakVlaHdi
            VU11cFhGa3JtRStPczhzdFl1aWcrcm8KLS0tIEsyTEJGRDNyQmVuWHhWdjVZbzVu
            cXBuTUVSU0s0eHh5OEg1UTl4clBNbFUKUTrEUlLV4k2mwrCFCyrd7OPHudhemwMV
            REO3VoEHuE4ibmU2wp25lmgUmM1u2L/HVdSVbDvrnacFyUHZaT8wIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd2tRd0NuOHErYWVISVZt
            Z2FMbUlWKzk3alpsaE5vVmk4RmJSbjcrQmxFCkVHVXY0ZjNiQ0RoVXZCMG8xc1Bi
            L2ZMZFlaZmZ1RWtadytvWTg0YjNSYVEKLS0tIEtDTERTTEVQWGJJalhaY3d4bDND
            L3dqSmtoVkNlV1J2R3VWQ2ZIYWRwazAKWduHH4nWK2qpujgRaEjaBiD32za81k6l
            PmJ4yR5awQwgvG8Slslq4uIzbQS5hOkt5Vb28zVAH236v2p5jUNMGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T12:26:30Z"
    mac: ENC[AES256_GCM,data:ovvqZHo70nq3ZZTQHMdz1tayUcYijNppqP7muzmLTIj3zVoZ8ADaw7WKqrAoJVrvd0K2oXFTvpb28rq/pfS9gTKrGaRBHnRxlVAh8RLGJGwSYw4AwGwU4/haa+2vWH0qGfhC4R/tB4idlQu5C/0pQeO0OxzbbN4acvbZ2Lxv4bQ=,iv:rxydhHfCG8tNGbeNyyQz2605WwFYaEY3PjYHtqsiPDI=,tag:FwJ5sq6YKS4YSJPa7ExSOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
