apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:DP2cVLP+1pQaIOt7QC43bDVQHoTtkIkA7RLEgi0YMxZ49T+2lwJg5qEZ7XpIQvwLbHqU8AhcOCrbQbmx,iv:g4FeGkZt/EM+53jyQznelCnOTZYwa+Om93BX8t71lhw=,tag:/sa5rF3U55Ec7mjDC2ZzBA==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:jHfIevkmSyM43GPbETVOv+aPztiWnn4jrZdYMBqGIi3lMIaWDELP9Pc74f8u/fyPN+/zBYhBckKOFiYV,iv:gPu1ppQ7EVRJ6s+i2ZS+UniCBu5NrFLGjUVHyzSN6Vw=,tag:GCEgDOLQ7/q43pb8/mliCg==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:dDpTDsbD9TO2TkVp1UXrYcXVFxkyU0cg4By/vOnXpTtFIm8N9gcunDLS8FCixVWeHIV81bJCUUTbbLb3,iv:PyKqPXH88oPQko0Yw2tHQZ8FUdWlojbrIhrw/KmywNo=,tag:VN0CqKC/lkIOzEJotQjKJg==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:k1gQu5ZNUv4S43dyYUuFG7HjsN7b4N89fRtaKx/KBLFbrgbZJMfnA4gclIa873Zdg+HsYT/gOWpiENF4,iv:4Zr6INRpu2mHscZkjS59IYZWncLPDkKAmRGlqaI6hOs=,tag:s8od5PiFlcqlzmoLjdhAyA==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:6Brm3lBn+ASCffnkSkgtrlZdXTHejoJhy+PXWLHaBii5KNUY85qGS9Azi291xvoZCb6YmrptmTqyDO43,iv:gv0omc2/k5GPK/5UFhGHYpH/t5BDQWGiGN2bIo6ySpI=,tag:5mpZ4v4DUggE+UhL0kUwzQ==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:7jXOg609ZWiuOlP4h8/i90iMrkTdEdjWD9PQrHeJZVqZKA1Z,iv:D5V9b8kqv4jdtvT8TQ2rA1aq4Aa4+tXw3a/u2K4Zvvo=,tag:vxGOW0EV7s0Ql4odyaNBaA==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU1MxYW1sa2RGSWpUMkI3
            b1k4dlRUSkZNWXJ2VmtkQ08xUmNmcXQ4MDBJCmhSTklQeWl1OUJkTnorM095WmVE
            emRvYlowTTZrL1VXMTk4Rk4xK1JmVFkKLS0tIEIwYiswaDRITVdCOHdRTXgwcHhD
            Yi9ianp5Qm5TM1JSWGdXMlFEdWUwbWcKhxDY4NVnMPl7xKEm4ZY4imc62jWZ2I2X
            CDtxu/Yq3qrqJvJ97wi7sRy7Fml00PP8rP+uIELvlUvJEOuzIM18/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZkk5M2VVRHF4VmEwRWFp
            UWMrZk1nSzh0bDltWTRFQzlFazR1TmpGUHc4CktvdWN1N0RacXBwK1lCYTBhMVl4
            ZmJSV1FsN1FESmpqZk9DcGpETTBGYzQKLS0tIEVQUDNJRGRJaWJpS1lvVUVTWDVh
            L3dBWGZtWGdaaVZ1Ulo0RDhrTHR4YTAKCZqkBBLi42CTtDjYgsJPJQy9aTFPzfnI
            mDswAmA8r7gVn0Fv/kb/zDAxSRAHxYwODnI6doMP+QXZsRm75WsFKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRnkyQTFJeGp5TEYvTVBx
            TkxObXZvMDIvdlZzWXg4VFJRM2wxMjhCblhvCm5pUW55OUNmdlF6MUUwWmtDODla
            Q1J4NW4vWDZHZmRnZGxEMGt5clVFVFkKLS0tIDVEZkgzTlo4bnNTckVtbGhzUmNH
            TGY1M3NnN0xJdnZOSThBQVZmRHVXejAKiUaQHMP+ry20lGQjq6xD1tBxZ3dFVPgs
            I1pwdjbYUYfHJGVA5jY3FtuqVQUyHatpMB3FGxQ42UnY6bVGXb2OEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtazh0TUQ5aUVmQUNJNXc1
            N1ZzaHluZWpJNDF3cHlpMExLcWFaUjl3Q2tFCjFZZmxaUTlhM2NDS0s4NDh5MGNG
            Z3kwM1hkL0grMkpFakhTWnNOOXczZ28KLS0tIDVHcmJqZ0hsQXp4R2o0RFhyenQ5
            R3ZYMnp4RU96MjJENmpLdU9vbnc1aWMKD4H7ljHM6zC2wKj/UtELW94lo9yd1N87
            nFjTuFt35bkHqfYcq4HpC1GcMeFBN/TeirKvnGoFThaNM1AipB5rew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T14:13:00Z"
    mac: ENC[AES256_GCM,data:t4FVwO3Z6nM75xkGW7AHLCEvuEQuK263l4+bMmRi59slU78T7pfAmWY81yckMG9bYtc/G81aa4E2VkmQLht/WKWby0ZJkvxsxmLsDMxH5XnBTv6nXQcVQ0xVxhgEbbhw2W7sV5X/LmH1nFud1yYc3uyP1CqdA66D0zBley+1sxs=,iv:Dl0vq0mYaJXu8IS/fqyE9m8xD1bTcbROFQYfMOJ7+lA=,tag:0LaOzDx/Ik3eWnxClzlvbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
