apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:8+0qYLcf+UVC1jyWkpO5i6Go7bnQ3ejicmBlAGLzo2MA2KS15+w0jcH/7GDXhjfcVZaWBM9MKivwjiNh,iv:5G+g+imvB/qoelAl7vlqt7dgxpd799Vnfx+a7brg42Y=,tag:IFg6rx99q5xsPeV8itY+CQ==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:/O1J8OFPXOX1kHtTaEDIJDrPGxVO/4MRCm9NqLVSgr+yL1pc0qLR+hbt/jua6vIBzUynjZBNLn0W0u8c,iv:Dov780JPz39A2+ZB9n4uAH9/1qrqcsbS8yPuG/vcTXw=,tag:BsKs8c7ZywyWulwlI7rB+A==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:L0v1c9LuEse9HuyEpoAE1fFr8Ln6MYC6wvAeUIeEv6kxPzU0sONp3xn2WU5vt1QBRKICSq7SE9pk6ARf,iv:igBPmDkgaXEwwJr8dtWVEXWD0J5SpB4uOmFBKKmIvIQ=,tag:dndi+808J1D7lKgHr8muHg==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:/IqrbnPSB5HiJS1l041fVTL8HYoaVTt9usYFW0GnBc8C6ByArUCl6vZADqfXYVBKAaVuaCLblsIaopuV,iv:ap9wvFIKDEWdFkeilse4LFBhCZQ/Vlgs3i3PaW00+Vc=,tag:sS7H/a4AtVGd5/Us5uizSw==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:AJnIZZg4cnFTb/OHMw7+uw8AAS2AimS2qMR5a26wDT0f/X0WYHU7xqPStSUAvn76HnJCFH9Tccu8NYfh,iv:2Sif0ilmHGp4gJVApKiXqk5ENLM+SPW0LuSs3OC+x6Q=,tag:JOp/K7xxcRe1XThlJbe73A==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:xh0F2BXQpnn3LKU193X/qEmPezq7vidcDfRuTvaNrAg1XuKF,iv:81DZ20nIH1blT4xxFjpgoUgHXEnfrpZr0pmy2XzPOfc=,tag:7HO1cLSio175GRJ6VpfwBg==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTajJ6S2UyZFpvVlU0Q2w1
            M2s1TVZzMDJyUElxTjZrRHFHNWtBUmhnUzN3Cm04Qk1CZndRNVIvcStpczdyYzZF
            RlA0d2M1SGorZW9jUUhCYkRmN1R4Q2sKLS0tIFRVOXl1ZVJ1UmNVZ1U3OVFyYXFj
            MzI0M1Zwbms2USs1bDN4WGhIaFdHTjQKXF49cq82OLYI9LwsLzmaJoQH2PXnq0Cl
            t0DXVoqcbUnwaklZtwuU/C6ObXChuFv7oXpKY4ZlO17GeT13eAnpAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QUpRSEw4YWRnbGkyYXlV
            akwzeXZvbEtBdCtxODdvS21yM3NpZXVicW1RCnRaZGVPMCtHdnZFN2E4Uzd0aDQ1
            VkwxMWg1K0s5dHk3ZHVBSlNLVGwrU0UKLS0tIHJjT2VoU3ZZY3JjeVpVZktySUV0
            VDhVSEI3WDM2dDlwdnU0YUQyS2E0UlkKvK3Cv6LPU6XnZP1TwKTjNHemCiRuZRsK
            Oy1pwWp9Hqw6L4a1lqbGcRnwHwtvJsRKx7scwsW+AjaRzk2A66bDpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJemdSUm4zY3NlcmZaZGsy
            SkF0MVdsc2ZZZ2NDeVV0aGFtNFZ0bXFXMlRvCnJ3SXI1WVJZNXY1WlU5YWpjL1dY
            cFA4Z0hMNkFOQkpTTUJFaWVmWjBqTE0KLS0tIFcxemVoL20xcXdOUVlrQmRaMlE3
            VTkvdUNRQUQrbHZINzBrQ3dNb1hWZFEK6hYwFkLwTP5XI1m3W+s4swy0YcitDGB8
            /Wclpfa4L4y3l2/jxsm7tif/mnsEa+yHA6JOMxqrUTKEqWKln9sVeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUnNieUFLZkNLRHJwcyth
            RHhRVm43Nm5BdlZqbHRpZmpnLytXcGphUEZRClEzQkJkeXY1K096Y21VM1pBcWZq
            ZEE2MElKNmY4T2NIdXV1MStiMlBKeFUKLS0tIHQvU0ttdXZ2cEVQQ1RVUzhMZm05
            Vk9ycFNPSkZvZUJFcC9wUGVCb2ZnRDgKDpga52V864EJ+X7GsuXM9xHkzPU9HBx/
            cB+wqPHWf93KHWGfCiwejVkISgNIQV1X1wRFkuYM1jGHcPQwOdr+PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T14:19:00Z"
    mac: ENC[AES256_GCM,data:NQ8sCSC1bMFIlHFyW7D/PXm5UjseEoFEHpZJi2ALudgDno+OFQQsYhSdwCkcdDuDyGAx26Bbr/8drLLhXzGs5F7UwI45nmvHOGHD2zDs2dpnH2p0+rxXmczmcoviAxlVhBT+jZU5IH3XY6fAJbE6EiOO2YL18hcEI09TG+6TXEI=,iv:uj0cGifAX27fhDlYcGV+mR8TEWu4OOLxxj+ilnfc59U=,tag:DO5KI8Kw/2NBjsJTSLCCsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
