apiVersion: v1
data:
    key1.pem: ENC[AES256_GCM,data:FAtkPi9YFi6hE3ii5FGHVg1H/vGIk2msDD7tn3xYQ1AcWSf8ckWoXtBvZezDZ2PEjvMD3lrQDU2Wblxro82frU0mq05pX+7QfiZ4PD+cIKfEivAV0C5v5ZoQS1+GEI+QSZVABt/flC4FK5UGRvtyQX89jLxLqCcB6HfUvmTIAYSMRCghPAeRfzHuMgMmAnxet7ZaIKrdughub8eC5CQXhgGexU+H3rYexfLAnJtyychjjfCSadkVcTUxkRxBldoUsB3kyBhhI019wKyo4japkfuEjuRsiStHhyLTM3Hw2TuuK7Q829ADEYsdiUNtCdBzwp2py7wZmFLTqKKckOTaKZYx40s477mId1UYSSlw5jaPnMTeiYY281JUXUaN+unRuPVLuI3+D9NPfYsPy+/Umusm9j5xvE2TWCOTqA21K2Y49NbUekHW5Z6XFUevxr3JK3eDZ8Qhd3R1+yjT31kBbs5tthLK8D5SaB8Yar5RHm/eekzdWi0Mkrh21P5PExD5KRtR/su47y1UGQS36jd6mozLa2Cqclg/WkrkbK2WThN8KPhqxRHxvEfDiTj56gKfLCqfO9agTJ3V40RtzjsG5rM3xWEB87MEm52AQh20K6zEIGSUFaFIzoBhrnGGxhBOKvV3BtpfKD8oKUEIT9pF6A69eOTA75rrXtUr7piuHXis/Js5NmIEDzp62u+LI/o5OwtOEPre8VMmc2htP6MDTN4/L0mWyx+QUeNHJ3wkxNAG2hA62Vy1cw25XoKNmz7YjzcmDz0REDhU5WJFMwQHM7AYoG2tSNBEvfygIw==,iv:aXZwOQ+Tf15sC8cEsGTt7n9qBEKQQkX++epsS9WEHUE=,tag:cL8Uu/Aij2fgZYUZyq69GQ==,type:str]
    key2.pem: ENC[AES256_GCM,data:ZnpGT5bI0pfJAv0iTDfF9t1sIHwM80SoYveYfl3nsoiBPFuJ+GgzCELmvTOihJT+ospmAjhRpkqi/A1QCwgjDuQap+xT+Agji8Z4BZyrQqIzFGKpjRnQeKfZsrzY5jzjnf7cL/zFtTINlStum14gY2WOw7NyLd+uveAcoH6GI0hWNUjmjROQmjS/xeUdparHWkli43fMXFrOjx7mzh0sXJgqq5Z8oBt2MjmXvQU1C7oR1PVAk1Hi6e3JSUwtMEiLQ2ne7UH0tJEzAQtNKTfhwaq9S6mfhUU74Hk0eAH5l/hU4o+eunBoGSUcmkjqxCktp7RakKRPIAZVdankn1HvYEEEftZmJi2gEiTcNi4SSBZ509/NirgVi+J1hV1HGNHPzg0dbldEikv7eZ45bW+RqroQE7bKQtZ28D9rCKYz3CUUPXR9xZOo/09thkskYtPIGTHO6iIz1qfBp+ggWZrPU6zZ1Ti4/odOuu5fgpiB4v1Rpexql2nyXBrBMoKBms54TtnJ3wEA8tES7hnWdm7lpZHrMFT0bIZqcBHxQWxKZpAoEMx4K1oGaxuY4Gif8eQRAbl8U/MugQijtly+RqMdA7pzrNh7GZ+2Fa7N3ZK0xc1IGKKHp60bLFA5yGjIpwVF9qw18RWRzhcfwmwqnJCn7usC2sAOlA2kDfJFQlxA14X1M7o/6nHpWPwz8ox4AxS8JBi/u4YDjXLgAMQ1kq75mlaEjmxcc/HcqAcXjB1m38hBfo8+gAIBPkhnX/kLpr+nL8+yhuFdXAiXhHJRgWrPgOmCmdsufyKbZoL5qA==,iv:GwjA09NiYSmfuEJHIb+M05sBLLVOkEOt3pryHY4zQiQ=,tag:v/keYAj4IIOTTPFGctyPZw==,type:str]
    keyId: ENC[AES256_GCM,data:c4dZzAdBHp8=,iv:PoEB+i3OFLWdRVN8TQ0yUzPuW64KZq725T0TAwo7y3M=,tag:v9G2MZtB1T977MXNazqXFA==,type:str]
kind: Secret
metadata:
    name: extauthz-signing-keys-secret
    namespace: services
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZXU0RUVjRklicDVzSy90
            ZG1sNFhpSHgwODhkSlYxdUtDOGpoV28rL0JJCmIvbThvREx0Q29nUHdOaThWTUNw
            S0FGVS9QVjJldlIvUFNtbGQ2UklDTG8KLS0tIGFTOVRsYnhpeis3ZFg5d0MrY2Nh
            dnVSTHJ3R1gwZWZkSTRyUkRUbmZLRFkK06HdaY7hgeQeWfwpKracASaxt+lAP5jd
            aAJajG9jFT6ABkqNKXUJBjvPwGyANc3aeeULBVPSxufkJ9CsWm2vpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NTcyd2g4WENTbXFmSmhE
            T3I4cis4LzdMZkQ3dzYwRCtOYnZKRnZacmlnCkhtckxSZkU1cHg5Vm41YkdoVkw1
            QUErOHZzMjhEcnRlRkVKSDd5em13MUUKLS0tIGZCV3lUUnZMRk9aeEd0T0hPYWRQ
            R1VDY3VvNThJNllWTTA2OG51bi9PMTgKqK9kkVbfYbHZrNad1OGvNqz81mtfmBsG
            c8Y2e8Hq89kU8cQNPsy2qaVYf1x5czgGmxv5Wtw1sh2973OAvDdC3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SEgwNDZuVnJMRXdZb09r
            M2pFTU54MXUycUdOSVhxQk41Rm0vRzhLVEJJCmVERFFCWEp4K21iMlFoL2dYQ3FT
            eFF6aHVzcDdjK0NyS3ZnUkZzSTdlUFUKLS0tIEduUW9JVnYyS3V4clRobU5Sb0RZ
            cTVjdDJZUFZ5SnJZamkzUThMbEw3cTQKKspeTDE5H7CddO+Xk7LWNKCilYVmIyPK
            oC/p3x/ypJfoZw0W4YaSE89sEDB2bzA769Lk2D6glOgnS1s3turx8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK0dCZk9KMlIwUnh3VjZa
            QmRBRUJ3bWNEelRCWU83K3FRbTh3WWo4M0U0ClZCek5uRHU1MnZxWVQ3VDltY0JS
            eUFSeFRDKzNodmF0WTE0MVFHR21BdXMKLS0tIDlPRWY0VzNza09PT0FKQTI5ZjlS
            Vk9HYXl2bDQ3MHovWDZuZ1J0a2lLNGsK5ZQUKN+7ndqXxoylKLC2CtsxXh3tkHZ0
            xhwysHjKmNPZc14NWfgYyv4FyjCZKandZ1s5w/rNag33CfmoenP6dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQnpaRjBHazNNT0lPRlFm
            b2Z3Rklydy9sdlZxRU9JRUVKVnFidjJncDNBCjFqeWdhSDlVMEEvSG9GVmJkaFcy
            UnNKdGRrQnZDcVVISGtyajY4MHptSFEKLS0tIFhOeHZPYUNvUUpYcU5sTXhXYkVR
            ODBLSC9JTHQyRTU5aTBOVGNKRERFd1EKrPWoFQvQYH+CxywK70NBvLCwHCZNtrIK
            1o48YNOuunzPGKda4j3e9qBBWLkDECgTaRCJLKaRZYzEWA9ywtRhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T13:11:22Z"
    mac: ENC[AES256_GCM,data:Y5yIwL7+TVjwqxmEJXe79eN7M45FiEfvd3b4b6wohqPOzJm12eeQQcG6gXpRpiFZ0SjhVADNtjdWt/OnVuwxV321Xv5/uxAK6a2WO+6qOV6rUpQEoxS+VD8Rqq24WxlavXFifo3wUowZp1UpulE+WFj3FPZv/8n/9z9/VDTvx2U=,iv:JCFfJtEuVMWBfXNFcvcRvnS9veW9vtj7Tb+2i3TO68E=,tag:0bSkJR/UzvBrcTQXdElQ7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
