apiVersion: v1
data:
    key1.pem: ENC[AES256_GCM,data:e0Yg0DjDd2ZCEQBfwjnJCOC/Qu688HkRb6ig0dptkTbK/ANCrZViV+pLZlu5/IIreZq1x2u39tNnzzz5azGNdiyEbvkMq0k1hA2Obb2QkgliwDnFj79Gb6fkNPwI23sanAIqBFvQhcifT3Ggs+v1udpy3ceZAtAJISNoepQLkYsn+I19PC4NvMSOcPR3emro9/GVxr1FRhiQQ4TTPWHY7kc/c6R1RsS7EE26tUTPnLz4ZISL7rowLh7waptZkxsZJ+vkZKYbjFHXoDfXoqn2Vk+2bfqRKF/SZ42FrLjWUCeJ2KGau10mW3alQyHj+zOq0SwBUk6Y2ZJg5iohDHhkNz/5RKqOCn3wBIkxGdAAMoEcFrruNueYPb4NGxycWuoD1+lSr7FiRtu5xJHMR2lMd/i6Y3HY4sgmilb8QK63liut7HDYcudtQVi/eV/X8l6hq/hfgseSXsaMQPuP4P85lZVSrwo9YTS9t97fyKUb5xhPVwv0UnF9EYsOcBk0En43uZQNon4p3+NqiAjlecrS3I3fH/ZdYnlazRFQTuXql1OOX4MDvL2b48kRhSJaBYDdDMt4JbenGug4/7R7wwX8f0ADeC0bTDTWtbklpOuEDFW+LYqeIWQYhi7ByHIZcG27oMNPZUIDVAZJpZITTrz4FTbjdGIqHq1Q6EasJiyQ/GYROVteNXNEEZq+a36umLqmiIwi1+PAqaxM14JmOxVwIkfBDNJymlgJHSnR6Dlj5xtUMkxQn78cnxUNAvF/D+pbVdptcYeXDVmUBnW2fct60l7fWaar7hfi/1zCGQ==,iv:QoKUHLIOOZZWKhjLehxjHHdz/3V1xXs4ynGyPQ6kP3E=,tag:KVDqJdq0hwr+QP3NQCdImg==,type:str]
    key2.pem: ENC[AES256_GCM,data:feUPlM14Qd7nVkB2HrjslOU7IEcGRmObGL4iz2T6Jxkly/7vOmGDdm5ZI5zGBbeMBjlD9NQglfLQTLf5JgmrIaOYp9cChHa71Rz8ZShkqB38a8KMB1k38D+ZCxWp8ihn56QVNGBloKyQ4yVXCvdLEe5Uu4uH4VQSx3FmG/+C9yL0QPAi76/TvXfGM4vcytx5QxJHVIoDsjQEcq7zggYjdF1v0ltwoLEHHt3Kf9puuQATkEAQhHyKnCr2dLg7sKCWvJ4GxSDbU/PwBoFDXbN7RNrKBJm9aziAm7iP5GoZfH5E3kmRbV5KNAhfZwf4Ttk3MEywf2qekm6e4c4Eeqp6Cxq9GvNfLYfXmwpRAq3/clBO/fcScNyG/XsogGBuy9rKbicWQ6bA1NZuB7VSaSL5S55x+0l+YF9koV+kcIYVuB+ulocRtVpe4916joccmzo8dCETKfewMKIO9QVv5421m8YE8cb6BUshGUSH0GCNKUt/U/TKnM+ioVN4QlyUixKLYP/4gOuh5WCBQI+lorvIFXgu1v1Yi8N04isNTRNn7idw6XDS26RbuergzOJY03tC08E69jIc5EUk56ZuVkp3xNUt2zBwS6GrarM8MrerxpceOJGs+E7ak4fVrcC1GePNDRxPjrEPLXv6vQ/zEuhoPSwCzCs+ZKaLxIuuS+BS4VF4RYuTZ48WKNgn9N5LLxRXXuQoe+oToRRT9PnapACqx5PJnb430m6xhDGXbJmDwcyeIQiy50Jh2I6nAQPG7gDhpNUNclf7+WZO5HZxRHcQ9LNsRGgeMzIiEJ9tnQ==,iv:FfKcidbwLhtez+Ar/8uUEOFUQf1Ng1UrHlvIS0MoCx4=,tag:FPSq8dRrsnESjWW1ijwicg==,type:str]
    keyId: ENC[AES256_GCM,data:OAV7S3cPsH4=,iv:v2YxHAOeNGfr9wpCwuosisLhuiDTx9jJtfJ7FtGavcE=,tag:4RUg715nwRhIRRrB9WBuhg==,type:str]
kind: Secret
metadata:
    name: extauthz-signing-keys-secret
    namespace: services
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbmNBRVNRbWY1QmZhOFZI
            M1ZFMHZ2d3k1OEx1MXQ1MG5JT3JndVVkNDFnCnhRUjQwVHd6OVFoZm50TU03ZFpn
            aFROSVhUVVZ2dk40NlZSM0NaUm4rTkUKLS0tIDdQMGZOMlJBRUNPYzBqS1Q3WjFG
            d3F0a0VTN25nU3BkN24yaDhXZ1pnaFUK2gD+zYz4bSF6qgGzrR3oBnsoaUVDLFpv
            bp7nzR/o86Al56cRKc6Os+Yhy75m1n6itGYMNuVHILWAyt59isIxTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMWdscEV4RUtSeGl2S09J
            MFdOVStQa05KTlhpWHdUNVRSNU9RcDl0M2pBCnRoRnUrNVMvVzBLeGlEYkFGeGRC
            dStvNmFvZ2JnMnhPcGZOOG0zeVdrRW8KLS0tIDU1WTB0Ti9rWUY4TW1OOHVZM3J3
            akFHQ0pkdzJkOTJMUWVIa3Y3bGVtSkkKeHKBaGeYqoSBChFMlYYMphVUXEn/OoTv
            ZuQWBQVnAU3XSwTVzuS9TjLJr8SfKTIAVvaaX6IMiQ4KiQkqpwWIJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUHdoejZuVERMekg0QTJ6
            MEtUZTdSazVMVXNhTkR1TXVJdXk4Q3RMT1RjCmJRSHNoVktjQU9HelFHR2xSYVJz
            RVM0VzM5Y1ZXamVNbmhKaTlKVnJvMHcKLS0tIDhpK3FoOEg1c1lZMlNYSTJmbjUw
            NnlURWNRanR1UjJQTUdjMlZEOXR1L2cKjsBtn/rQbzXdkSZmkAS8Fn5bFneziaxl
            0yJZXu4Im/RMGTxA//zUiYPui/QyPz2H3QriIaYD99LVb61jJX299A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTnRjNTBZdmVBNTUzU0Ew
            QjRwQkdCcks0amhtU2VyY25NY0VwOFNoa0NnCjU1aGhzQUpBYkE0ZU9jZTVZTWk5
            VUlqTi82M3lDc1Y4MVEvby9OVjZUUGcKLS0tIEE1VXlTSGVRYzBoNWc3bzE1NDJz
            YWpMbWxMVUFuL2x2YVJJZ3diV2JnUm8KGMCgIKkYoWvhLgW08fBu4/9neGk7MgWv
            +H8rBtUQ3DpcqmwN+B+1OIAsrECNUT6ZLoV6xj8YE6FAMcl+yxwW4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T14:41:30Z"
    mac: ENC[AES256_GCM,data:G+vnmVnX6sq/i3iAEQWSsJe2MwQkBychZ5uKuMhxrbgTmBM3yERVnZ4RFWBhQzpRhUYRE36n6OzLX16jEKDRWM0RAPeCKZMXdJiyExiagy3B4rmrQvXF2K/CE68FEXiOXSlU+U9IlYWZxi3KYDjjd+gCsumxqQmhFtNSJS8P/Zc=,iv:IkN1x0Rdo7ORKTfJdYIsDXykpKZ2ibVNRWXyP96IKxU=,tag:fXWwMXAjPJVX337YaykYAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
