apiVersion: v1
data:
    key1.pem: ENC[AES256_GCM,data:iTDwYQraMwoV9mg6OEwekVfoY2zvHSOeBM/rKW88cNKqIAIfSwy/C8IjkL9QfE5OjSnYf4p6dcn0o1Oia22WraYGp1c3r1jwGOAhrAibriMABzDJ9gNfYGW/3zqoN86pJjp3h1VlXwPzwgjqPqe3FdmP3k5dMm19CFh6m25i7x3HykFF/H01jeEYgUgVtxdfUsEiHZPgSPDfS7CYw+tuE6vvqIcm+/Vt6qlLnnPObj9o1GDjIL0emqhLXthlLVmZI1YXaCjLKDXlv/onZB/v+51aEVgqIGB//zgDD/3lpUyYIyIa/IL8u4svjEkl28TU9TJgIY35UwnhCh0H1i6QCZhPnVdPIwhkWv4ftJh+/jpcFNeUtDOd43Dw/ZynkKNi9FDnXaQNfFzNMaqUXVzyCBvsR68MVM1r+vqK45s9LOyVnIIrP30SDFiY8ElFimd4ftO59X2/IyO7gRcb8aY8qaeViCKJptjzyUbJHQnuAtFbvUSKig8UjpRR3Zor+26iMIRcRcxeZ2I8oOhMYW5pq/esF/PsnT2RO4gRSXMQ77agI8mvm9xlwCCygJHB/tgzQzo6sfg6FxTBMFHcqW1xtRA1lKd52oRbPVvBAgVCi8VmwyatETIayQp8JmeoLqyG4Sl+x1YKoyi6EI1XGYEYx4ZutUqEbfS0r5HVDiR4QdJxuKq/exGb2jUv2JO0R7h1S8zPhYyVNsvXQv1vDtqWkrZbqtbqMGau/j66SeaNCOTQStBnvKjvxlmTDtpTzLzeki84TPSfDvaO5tMjHRwgBm1TRF/+3pONK8Eqdw==,iv:ls/Qey7gm1lkimqChDbLLejO1S/cSfMuEJC0VT2g3ec=,tag:qeHKyhwwc2LDBUmxyIOFMA==,type:str]
    key2.pem: ENC[AES256_GCM,data:N/+8ae+ooao85SyNvJLeRAHsTW0tiKNSkllEjlD4GZTYNkCKUgIHvJKhz1Mp7C3ctt/YLVYAkyi+X0KOarOelY+BSVB9xfL4j9njzp0njAyYsW2unDCfsGaIBZkbW1/M5OoQY1cjSFboYUypv2T/hOm8HHin4zNOKMxwpXQ1mhOtiA0g0YxDPiFE35H6Rl6Xa01WQNpqRXHpAJB4tw6n80XM19GeczEOLRCHlyuGxMWsnKf5bhHXhwg/O0lx9xLO30PPT06hBbIGyctuiLEFDh8zR74oHbCGN6PQhY3xm0ZMSVScJtTyKEAV6xfDCKPblVMv1T6IpIO10mfSXm0adKNLtEkS+MiD29TRuuhlpV6b0kh2xW6hNjjfRfBI0/LgI3d2nRyDmASugL3/M+4K5MKEMFaZ8jiwVH6XOMkHUj4rqoQUcGrn9szIOslzyoRbEhjI5xDQfEQe26H33/+ItaIfJVLVfSqsQndqmiW0SbzK0TLTBSPEdeYVKkZaC0rnBOTU4S/8kImUuSzmiv2GkOOQCgl664Tl8QGlztSTWhPlRF/lZ4w6SaC7bdH72uAaHGQzh2uH7FL8F486JWXLN3WOm+s772228HRluiImezhvDobPiA9UcG4giuTmsggtVXZjnDDnOdMjbf8HJmLqcxLRgDSVPwY5LfY0T6AP60ZyBwovwJbeUmgjtM03MYsFlNQxjDkPFfabWR0Js84PQhEMRWgnsC1KWCylTZsF5J4iWpJFJOU/IuUXAyAOQp24rWG92dHoHcQzBxfctBXUIWuwjuAB6UBQyIXJIQ==,iv:Bg4zWfHZ2865B8kUiqjy4vE6nFmATu7msVMbk2w6++k=,tag:az5zqXM5QwkOKdpCqVPOjw==,type:str]
    keyId: ENC[AES256_GCM,data:nLLvKTjU6TQ=,iv:nkp3aNIuYBFU66xrFXlE6hgC49NAxfhsYvlLn+aSoRQ=,tag:a/YI7qkTY/6ulWCAXlfBPg==,type:str]
kind: Secret
metadata:
    name: extauthz-signing-keys-secret
    namespace: services
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRUpyY1k4d1hvRU96djFW
            WWZLaEV0V08vbWJhYWJVSXVzL29TY2VsYUdrCnc1V3gyRzJacXI5bVRoRW9STzI5
            QlE3cWhpVE54cXNBbU4vQ1doL3hTUTgKLS0tIGpGTHcxRTloR2VjaE5mYzZFenRR
            cXo1d2s3Z1ZSd1E5MVhseUtaRXFObXMKo1+t1yE3VtV068Uu4Nq1TYYNmZuKa/3/
            TUgLlkrkQW91FSbblR4u3VrNPQcJr6s3wdmgx/L5JRTmvU9PRRhOAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZzdDOHlzb2N4WHM1YzZk
            ZDc1NTlzc3o4K1NKVmNiS0FtNnpDL1NKTkhVCmRrdUZYdS9oU0tjS2FtZE9SRlZG
            WmZPWUxTbkFJeDVHS1JFL01ZRFVXdDAKLS0tIHFMMVRvWmszWXZQMWVwWUp1WDN5
            V0hLL0d2bndZcWxEdlhqOUVjbzRFdXMKCzSfkCkcJ9FWTCu22pg1RRyPhKehNQM6
            0ss7fvA+K0V9C5CY56lOUMw5oBPsCWamV5w/S1KdMidFGsuG4cDHjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2pvQ3RiV25CKzJPOG5u
            VGtzeXBsZWlSandxb3hER2xYdEJGUXhDT0FvCkJCY0Y5Q2J5aWNSZVplMDZuM29i
            RE9nc1lNbDBwYVh3ZlVFQ3BhMjM5R3cKLS0tIGJGTmlFcEt3eHM1OFZzVFlBbDlG
            bFJUVlRwSjR2UGEvNUpNNjM2Ujc5a1UKa4idqSWieP9r1pLX+sfDYB4Yv/jEujqD
            5PXWGRNVZf+nMHxwn97KkmoA2ZLAIuXqLVJSJchyB5bzml7LjhS0bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGM4NVh0bnVvSzZOK1Vh
            b3dxY3k3TllCZlVJVWJ1QUNiUXluTFl6cEhRCmNsZEtyYWNPTlo3MThUOWxpLy95
            Sm1KVjZsRmIyeHBCZURQSktIZUlnZE0KLS0tIG5saUtvcGxPNndUTXdhUnZqVGl3
            QW00d3ora0d4VHJZU1pscHcrZVVzUTQKIRQ61D4UrThHUoi2Yecyr03XcFDyj1wk
            d5x1JI7n1wPI4D9GgAkLglPG24O83j62HQcOdj5gqLTNYGsIlI3xvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T13:01:23Z"
    mac: ENC[AES256_GCM,data:mQnyI9SkougEEepT/QRb+jq4O3RpyDC/8kiuvY/Uhy9HwD+iRfLAbXDhi0K8ZJe4dTh6BSDPz6vvAjxFj9xBHybclTeiFhngtoSVDd0x+qW9RBdxBE4Va7GTuHvLtdweRg20FUmV2j0qXneHzj2Q76TlOpUkx580G10ufi44YZU=,iv:M9nN1TxWeNIfBaqlMT9A6u6mZ/BjUcyO/gf/OFmp9cM=,tag:1ZLoGXfaYIWS5m5qZ+XIWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
