apiVersion: v1
kind: Secret
metadata:
    name: echoserver-oidc-proxy
    namespace: services
type: Opaque
data:
    client-id: ENC[AES256_GCM,data:svpenS/0CoU=,iv:CblgIkTM5mPAZq0FGeIfnhsSkSpvI7BsnjtdY501oOk=,tag:byDwpIauLWJCoDZ2s9hOjw==,type:str]
    client-secret: ENC[AES256_GCM,data:xpoGV9xGZcMOsSWUiZVPxBAFMcrTvenQzgA5xLTxxExPad41V/rNpMMEyU8=,iv:cwRdmQ73AoOhlYgvdTSHbJPSxJWzMrypc4jn5VGNsp4=,tag:zdsQNEIa5yengHPn6hMVyg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:JwPFyD7V2vilSbw/OaP1EKGWMQddHubpq7YswEUzM8QQP0teVZFlI5MuW8Y=,iv:Zb1cWvn+//fA103eEZskVpstbmSSFM18HCvumrjzYHU=,tag:iynMQg2+IacfjJL/oShMSQ==,type:str]
    oidc-issuer-url: ENC[AES256_GCM,data:nHXQqrWz6wSNL+7JLzTUEiobDoGQUOF3QX2X5M1Zj/Fgd523mNrbC+xIfzBdGgVb3g42Jym7HYTeyIEocXAvW/qoecMBTsqc1eszvQyqhKpQKFUZYPYZVp/OKQknJ9arWSNub33aPaRo6heZ6Ff0BHeb9rM=,iv:2yHqtbx58pohzymMz4Fqg0fyqtESQk6TMFU+qQWqanE=,tag:ArYlrN6mayoU/rqLrEhRvw==,type:str]
    redirect-url: ENC[AES256_GCM,data:Yz1bIndrv0q0EMXkuSmOXpyDun345cn3TySn3GSsn0+x93ACRwQygagJS/FHH4bxXnnv5Zky5QrT/TpingfOF9H7sSE8I+Oc2bhUDrCANq+L57PP8rWcqUGQnxUpwnnIeuIt3moFPE6gRI89juvKGg==,iv:od09z+RkGCrHtpy1P5C44iixE4jGEKlq6nRK+Umzi5g=,tag:G5bwwjl8m/kR7qTUywXWOw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZWJRdkRub2dwYTNhV3J5
            MTcxV2Y5ZWdTY1hwRlU2NWpqbXZzN1p6M21zCjRrVlJyOVlYclAvV1oyd1lKM0tD
            RjAvTzhoZ1VDN0FxWFh5N1V3WHZxaEEKLS0tIGN5MnBLWkZlVTNPcjR6aGRkSTNX
            WG9NRnk5ckU1TERDR1VqU01Zb1VkRDAKuCPHliKj9fYcwsD9OmH4vimW5ErTPv+R
            UhBGggopgHTyi7a2s9cSpD1PglF3XhvljGoGTOBi9bn7tiGwHQpfiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MzA4WGpSWi9mczFhUzBp
            YVc0UlVrd0pscllnVUVkTGRSbjdUSGEvdlFvCjVidmlCYmpINWFuMm05Z2owdTZa
            dDVXQ0dCZElJTVNwcndDYkpadUo4M1kKLS0tIHFKTVprUk13YmZyVjBpN1R5RTBw
            blZyMGdFNWNjWkwvQXI1WDBlMkg3a1kKkKFx5zv+oK3F8IafucNJ0W8pW/cfroBP
            Y1oiGdMcowtQCRaYw2/Hz4zqOH0nu3K3029Ptkg9p2lthPhFvRfM7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdUw0YVh5eVFrcWJ4Qkc0
            T2xnSjdJbEdjdUJXbzlOUGZNZ1BjMmJ4Z3dJCk9TRnlRa2tqSVNIbWtSR0JkSGQ2
            bm1kR2hMcDVjY3hIN0lGRlN5aG5uV3MKLS0tIDNXNncxRjI3TWwyU3NMbVQrUmQ1
            WUxsZGltWCtXa21vRFE3aXEzMG5mbDgKCneHBeqkXqEK9W3zsQAYz+VPKwTHWfqf
            z4juDmB2EZvZ8kKgK4KpO/X+rbYsBN46cnrfpXl4wFEQbBLDaTU6Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbG5vVFFwNjhwakdJT1Bk
            eFBaUEx3OVdMOWVXSlVkTWUvRFZRaXZicW5NCnFnTXJtS2x5V3RBVFZqSWlwL21y
            aGpZS1M3eFJBZUVneWF5NmJxdUFRVmMKLS0tIHFLbSt2YnZobU5MQVdjU0VabWRa
            NFBydTFpa2NXdUcvOWplQmdWUHFiYVEK3AMEIGZO3SxqxisGXfyZDPyORbJrOlCD
            z8pR+571hiz3fzICgdQH5mrSAzOyzplxA+J6G+zDfC72dHUT8X2mDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T07:49:10Z"
    mac: ENC[AES256_GCM,data:9Y8mO/jdv+vZ2TmtK1GWYDO93B0CCap8LRr8Ar7/u60qwUJGl9nBJZ76MNeNDi9KnbtVY1tebWznSd9G7MA8rutJL0im2MOkgBL9YSpBgXwZzz5l1xIJO8m4W+nugyfRYzK0aQya7BP1EWNJarsrX1YI6JAdbQP5cP3K0o1yEek=,iv:zXCVBJopNOSTlUB37EMHiOfe8LRNdxXlfXTg4fL6mSY=,tag:Gs5LiRRwY3SjvU7WZQbMtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
