apiVersion: v1
kind: Secret
metadata:
    name: echoserver-oidc-proxy
    namespace: services
type: Opaque
data:
    client-id: ENC[AES256_GCM,data:IdusbRKmw3E=,iv:y0eZkFbJxtShVzi86MhhVmLjQAWmzhs46PgRG4txz2k=,tag:4fgQ5nwmirIQOOlqaGL+/g==,type:str]
    client-secret: ENC[AES256_GCM,data:gzHTm9+HwhyN//t/4XEDaJyS/aVacwTS3+MaBatu1Gm9KCb25ZOE7oiTigk=,iv:1r9p2exuYCVBjCzoagnPechpNu83en3qlrPgIsRbX4o=,tag:RSDxMdZa4lS6jUz3e8mWiQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:8mTzyzXSMgx0vmfnBncJf8UkiOY/Zl+XqJtjglZLVimns42O9AILjSXzrsE=,iv:OUCuGFonpo7spedoAcA8mWpa+EYB4zAkzTbKJcPAbDw=,tag:ryqq+mxoCLTR8AIquBW+Ew==,type:str]
    oidc-issuer-url: ENC[AES256_GCM,data:HhkbVOYfh0QSCpeDVK58J6DwXHvGvqGeWR/KjHPqg0bW8B3aDDdD5tck3sbSU9FW+Fm6svwXuKrVrq8lcB09LDxD0qbUVssz7R9s9fB2Qfjew2UvIO5ZW6DgCKZ94TcttCGrMrKhZzzP1HI90h5Vkl3MFSc=,iv:P09P+Q9YiNNHaVYkQEibGc/VdV2NqRxSOCFVXfD12IA=,tag:BxgUW1sMp1ThJD+IY23zJw==,type:str]
    redirect-url: ENC[AES256_GCM,data:+zpxBgNwPErN0FGXj5PGZ0oQmaBtxTzLySO3xA32/CuiIGB6tOVAmLV5r2htolVAFOc27izgJj0E0kLNqtvep46o4moMQ888oWhIGZY0GJUQ9ra4EIOa4a1gAcuWG2iclB1Odfu1vjilnt6YzvI7vg==,iv:C1bFxiRsIzOxq0CdCBB6EWI2cWqPFBd0Aa4UQ8Dkes0=,tag:CxjGaO5d2vI3DLmyjpEVUg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMkQzam1Nd1JwRFdxM0NC
            R0w5azhMeDFuYndYMFVaUHBSeUhTM2ZkY1dvClg0dzRtOGVQaFFsUW9yc0h6T1Nk
            eGNZMk5HZEpjVUNXSXBvTTY1YVVaS2sKLS0tIFhreGt1WUpFUWo0Y2dFTnNDNDlL
            N1BaaGEwRW9xUm41UUppd0tqVzl0VkkK7gNp2kyFPZpJiunxDaifZzcxgjeo7aln
            h8BeOJS8tzwB90cBJUszH6n2JgF6+s0EFEx4V4q+V45EWxECSOKBRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd3lDbmFSVjBpRVBwSUdE
            b0ZyVlRpbFlTTVlXVTJ4cjlUaFAxVXNpdmlVClg5VFZjN25WSVR4c3F5RTBybVho
            NUpheG5WVVBDRkJTa09xUDNZNFRhQ1UKLS0tIFNrbGQxT1JrQmNxVWdKd2hjbk5W
            MklBVTFxTGJpSERiZnBkWkRrVDlaRWcKhcWL8G2hZ5avh+sLmpNkRt0kre9IkXeQ
            eFsqsrsVryh1W5iDz+p9BwBLSIfuPUDVYcDeGV7XZ6+Z+w+0uHtHcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZFBZTVBINFFySDJrSndE
            VG1ubG1XRjhaVjFTRGl4cnJGUmlUQ2oxeG1RCnpwbHZGWklkQXVxa2pCbWlNSkVY
            Q3Vadmx5NVB2NmsraGpvaUxpQWxFcTAKLS0tIDArU1FtVDVkeWJXbGZQWmhmWFJr
            UUdOdk04T05lODdEeFNlVlpxUW1jZncKUsf+YkyKH8X2Db3KfMDbL3/pam+Y/EyH
            v2yv4sQzRbND880cHg8maxNLWsZpSOeC1gxm6bt4j65EUGf6p+js5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRjA4aVE0QkNzeDJkMTkz
            anV5Sy9xOWErdDVJckVoMmxySkN1UG9MSzBFCnRCUEpybXNFSEROZG1QVDduYmFP
            aFBIRTJPL1JBZjRNVFhrdmxtUE9mc2MKLS0tIDZVTEN1VEJaL0k4WXZsRVJXaHZ4
            M2tlZzNtSWw1Um9IbFF1dkFFS2I0WDAKk0OGC91W72j/sUmb5tZtkjM+qR2+zB39
            1LAgs18YcI9HD2ogAEAPM6jh535i023QjQ33LRDK3p1rOQjBmux78w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:29:30Z"
    mac: ENC[AES256_GCM,data:CiWf8HDKfWFS4JwNmg2KT1vHsIt+aAdjbh8/nk5fZrPb+XsrR9G0wRGrrwnAqKgrJ9CVtnLaTSdLe34b+1/2i2jlOxpP5NO+engllAPH0mIQ1Ohk+L+psRczgr4kjkLz0rGt/1ajjMgRAX4UHFbKjnu3mg6BkkjMrUmf65KqKiQ=,iv:6huEBll/1+XFhVq5d7l2vNTfZvNBYzaLW3p56/Y6htY=,tag:vH2qNxyItEAss4SebbK0JQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
