apiVersion: v1
kind: Secret
metadata:
    name: echoserver-oidc-proxy
    namespace: services
type: Opaque
data:
    client-id: ENC[AES256_GCM,data:AaUEwZzW5lU=,iv:M2jjX/E8P1MZTmmZRv640znYvqhTXcQc4tSGAsdVfkQ=,tag:swn0JQCXb5lsm+kgzXYWUQ==,type:str]
    client-secret: ENC[AES256_GCM,data:hTAVceK8g74WsDx87wQnpREQ3D/gzZU8uqHhontfLYDNPfaU6scE0Yq6WCU=,iv:3g2506sJ0cS+Xod1jUgx4E2oxJAqDfTp/ufHjuaM2Ic=,tag:I+FBWnt2UEP9MXlPm/mZAA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:mBmwlwR1+5T25p/XDyRtqQMlm+9F/NCiAiwJgDEzTQRG7cKUFFW60zawrmQ=,iv:zKXEGKXMkjOSBPQtEU0SQpSoQErWYJtzUI8IjYxUF14=,tag:0zcwMqO2G0bDQz5qedMaEg==,type:str]
    oidc-issuer-url: ENC[AES256_GCM,data:mqP23FeZFrEjbyzj1IMNZUMIuPevWWkM6C4BucoF2Cm/JjwMh88mUUkFjUYDs0gjD/ilqVEUwJ4uZyT47ykxQn45lioPB6bmCF5fWRwERD9i2qTRy1LmHburrVa8h5NUtuIsA2M3Cu5hbKYKutZzBcK+xMQ=,iv:rzmiFuB/fBEiw6ZLOj4XAX5xcC9PI9h4Lih8Yc9EtGE=,tag:0BCm7+H5q2emQwrIoHntaQ==,type:str]
    redirect-url: ENC[AES256_GCM,data:Re6PulKmRc8NJSht5yl9YORNvedcU+d3UOMnrUyGu1GMrWjL+SHMoJaS8z8y2SJSClMSCNsFDwoiicSVCOKTE5rjq5h5A3dbDxpJFqu+RT4+/zow1oUtr2PUq6va3YsojMQXWnO37ogHS6PxWlVqnA==,iv:iYGiQHa+dyFPYycJA7wNvSKJvqjyNpk5+7XdEAr6ESM=,tag:GbBzlrdEPr4Ub5JgegfVrA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZktTOWV4MmhqNnVxYmlH
            blFSaTI2UWNoVjZHWnF6NG53dGxiek14ZURRCm81T1RiQlZUdUd6N1JYYU1wMUhz
            OU55RElQNnF3akl4eExrV2UwY2crV3MKLS0tIC9vQ3hRdnd5U1lkNzdiNTFoSS93
            MnhCbGJNRHp3MVozOTNrQ0ZEU243QWMK3JXskqGpIjYh89eUBNAVvhG+n+XgMalj
            p5RnutXfGKci2/1LvCtTG8fAUnN9crawxAvVDKL02cViqNO/LPDNTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUWovN2xhNFd6QjZTMENr
            TVprTDRpUjBYQ1dIUktTeW1IbjRPUFB3bWpVCmVoR2RCRzUxN0dvNGZtdzRlQkpn
            ZU12M3VxRGRKVEZsNStSd0V1ZzdXQWsKLS0tIDdoQnhZeTNHNWxuRmw5Yys3Yy9a
            cW56L25tY2kyV1NkM3VmcjFJb1owWlUKoXt92Cy7bmcHfIwabG65zwLm4wo1FHER
            on/msgMd1gu33CauADFKvqUFuIbzwwkBR0MCTibX0pfxIL/4I0ng3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdi82SEJVeUlUZVVsemdn
            L1Y2VEV6MW9ndUJEbnRhaWhLSFhrRGpNcGhzCnRlNGh3WFYvaGhMeE1abjljWUt2
            SldCeXg4Wjlja2E1aW1yL1RLeFdyR28KLS0tIGRteE5nVjBCZzZBbHFwSWZQYWR4
            S3E5MU95R2RNU3k5VDJveVRZTTh3eEUKsZ8Aro1e4Jn+FOLflTKQ1VVW6jG35C/y
            UIroGNSUzctrUlvCB6w/jel0eq93BW3KjKHIS4vZH4VEhl8q20vMwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR3NRdWtjYVF4ZjBCK1hW
            TnJxcmNpcEtmZENPUWJ3RVJJU0pzTDQ2b2hFCnhjZnVuSXZGZUlYU0VVeXhSaGJO
            dSt3Y0FQRVJwWkY5WjhuRTVZbEhsTmMKLS0tIGpmVVBoaExBdC9kekJ0V1ZXaDB1
            QjV4QWxtQ2R3NVBzNTdpVEJreUJBN28KntJgkrKtcLkjI2sZ1t+kGKhHG94jXfyr
            FlcpUWZNSCPaOhQluSyQirTGEpnnFqEyCrACUGOnX59tLNZFCp5GfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:09:10Z"
    mac: ENC[AES256_GCM,data:q22gZsbZgCmDELT1LnE8dnqMCL0miDz812seqYi9iLryZWsdBqyBFAOVIJ67RLkASMptx4NAdUOrwOBqU8GoMvbYp4GMPuOrlzjalI+Cdc2MnY+N+KJINdKEIfys/AKfiaY6GIysQBu4C7GmhaL8JheU7/f7YIi8L863X9xkBPM=,iv:AwdCk83r4JYV6z4OivuXNvP1KMglj8Dn/3CzXkeWG6I=,tag:by7iAS6Z7XSPZNF8FjcY8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
