---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: krypton-operator
spec:
  targetNamespace: krypton-operator
  storageNamespace: krypton-operator
  chartRef:
    kind: OCIRepository
    name: krypton-operator
  interval: 10m
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    fullnameOverride: "krypton-operator"
    imagePullSecrets: []
    image:
      registry: ghcr.io/openkcm
      repository: images/krypton-operator
      digest: sha256:f69e64ad584fd85ac38e9a8c6a33455ed64e3150386336ca1909b46ed7df8262
