apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-trust-management
spec:
  interval: 10m
  releaseName: linkerd-trust-management
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    resources:
      linkerd-self-signed-issuer:
        ## First, create a ClusterIssuer for our Linkerd CA. This resource will issue our roots.
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: linkerd-self-signed-issuer
        spec:
          selfSigned: {}
      linkerd-trust-anchor-certificate:
        ## Then, creat the actual CA certificate to be used for validation paths. This
        ## will be signed (issued) by our issuer created above.
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: linkerd-trust-anchor
        spec:
          isCA: true
          commonName: root.linkerd.cluster.local
          secretName: linkerd-identity-trust-roots
          privateKey:
            algorithm: ECDSA
            size: 256
          issuerRef:
            name: linkerd-self-signed-issuer
            kind: ClusterIssuer
            group: cert-manager.io
      linkerd-trust-anchor-cluster-issuer:
        ## Finally, create another ClusterIssuer to sign intermediate issuers. This #
        ## will use the root cert we just created, our issuer will be "signed" by the
        ## root CA.
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: linkerd-trust-anchor
        spec:
          ca:
            secretName: linkerd-identity-trust-roots
