apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-extension
spec:
  storageNamespace: envoy-gateway-system
  targetNamespace: envoy-gateway-system
  values:
    config:
      featureGates:
        disable-jwt-provider-computation: true
        enable-allow-missing-jwt-authentication-envoy: false
    image:
      digest: sha256:83fecedc98d444173cf9171c6af9f76dfbb7cea16d0d90820b50446b0cd0b866
