resources:
  ingress-gateway:
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: ingress-gateway
    spec:
      gatewayClassName: ingress-gateway
      listeners:
        - name: https-gc-cmk-p-glob
          protocol: HTTPS
          hostname: ing.gc-cmk-p-glob.cmkc.kms.cloud.sap
          port: 443
          allowedRoutes:
            namespaces:
              from: Same
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                group: ""
                name: ingress-gateway-secret
        - name: https-global
          protocol: HTTPS
          hostname: ing.mesh.cmkc.kms.cloud.sap
          port: 443
          allowedRoutes:
            namespaces:
              from: Same
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                group: ""
                name: ingress-gateway-secret
