apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret
spec:
  chart:
    spec:
      version: 0.16.0
  targetNamespace: external-secret
  storageNamespace: external-secret

