apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: als--pre-release
spec:
  interval: 1m
  releaseName: als--pre-release
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  valuesFrom:
  - kind: ConfigMap
    name: als-base-pre-release-values
    valuesKey: config.yaml