apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey--pre-release
spec:
  interval: 10m
  releaseName: valkey--pre-release
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    resources:
      certificate:
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: valkey-certificate
        spec:
          secretName: valkey-tls-secret
          duration: 2160h  # 90 days
          renewBefore: 360h  # 15 days before expiry
          issuerRef:
            name: linkerd-trust-anchor
            kind: ClusterIssuer
          commonName: valkey-primary.storage.svc.cluster.local
          dnsNames:
            - valkey-primary.storage.svc.cluster.local
            - valkey-replicas.storage.svc.cluster.local
            - valkey-headless.storage.svc.cluster.local
          privateKey:
            algorithm: RSA
            size: 2048
          usages:
            - server auth
            - client auth
