apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/canary/workers/aweu-cmk-p-02/cert-manager/
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  dependsOn:
    - name: namespaces
