apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
spec:
  interval: 1m
  retryInterval: 3m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/production/workers/aweu-cmk-p-02/envoy-gateway
  prune: true
  wait: true
  dependsOn:
    - name: envoy-gateway-crds
    - name: external-secret
    - name: namespaces
