apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-routing-system
spec:
  interval: 1m
  retryInterval: 3m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/canary/workers/aweu-cmk-p-02/network-routing-system
  prune: true
  wait: true
  dependsOn:
    - name: envoy-gateway
    - name: namespaces
