apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/canary/workers/aweu-cmk-p-02/storage
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  dependsOn:
    - name: cert-manager
    - name: linkerd
    - name: namespaces
