apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: worker01
resources:
  - cert-manager.yaml
  - envoy-gateway.yaml
  - envoy-gateway-crds.yaml
  - external-secret.yaml
  - linkerd.yaml
  - namespaces.yaml
  - network-routing-system.yaml
  - service-account-issuer-discovery.yaml
  - services.yaml
  - storage.yaml
  - reloader.yaml
