apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cert-manager.yaml
  - envoy-gateway-crds.yaml
  - envoy-gateway-secrets.yaml
  - envoy-gateway.yaml
  - external-secret.yaml
  - linkerd.yaml
  - namespaces.yaml
  - network-routing-system.yaml
  - reloader.yaml
  - services.yaml
  - storage.yaml
  - rabbitmq.yaml

#patches:


#   # patch to add `.spec.targetNamespace` in Flux KS resource
#   - target:
#       kind: Kustomization
#       group: kustomize.toolkit.fluxcd.io
#       version: v1
#     patch: |
#       - op: add
#         path: /spec/targetNamespace
#         value: flux-system
#   - target:
#       kind: Kustomization
#       group: kustomize.toolkit.fluxcd.io
#       version: v1
#       name: namespaces
#     patch: |
#       - op: remove
#         path: /spec/targetNamespace
