apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/production/workers/worker01/openbao/
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  dependsOn:
    - name: namespaces
    - name: openbao-secrets
