apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-account-issuer-discovery
spec:
  force: true
  interval: 10m0s
  path: ./apps/production/workers/worker01/service-account-issuer-discovery/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
  dependsOn:
    - name: namespaces
