apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/production/workers/worker01/services
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  dependsOn:
    - name: linkerd
    - name: network-routing-system
    - name: namespaces
