---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: krypton
spec:
  targetNamespace: services
  storageNamespace: services
  values:
    image:
      registry: ghcr.io/openkcm
      repository: krypton/images/root
      tag: "v0.1.0"
      command: ["/root/root.linux-amd64"]
      pullSecrets: []
    extraEnvs:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: krypton-secret
            key: database-url
      - name: KRYPTON_ROOT_KEY
        valueFrom:
          secretKeyRef:
            name: krypton-secret
            key: root-key
    extraVolumes:
      - name: kmip-server-tls
        secret:
          secretName: kmip-server-tls
    extraVolumeMounts:
      - name: kmip-server-tls
        mountPath: /etc/kmip/tls
        readOnly: true
    extraPorts:
      - name: kmip
        containerPort: 5697
        servicePort: 5697
        protocol: TCP
    config:
      kmip:
        bind_addr: "0.0.0.0"
        port: 5697
        tls:
          server_cert: /etc/kmip/tls/tls.crt
          server_key: /etc/kmip/tls/tls.key
          client_ca: /etc/kmip/tls/ca.crt
