---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: krypton
spec:
  targetNamespace: services
  storageNamespace: services
  values:
    image:
      registry: ghcr.io/openkcm
      repository: krypton/images/root
      tag: "v0.1.0"
      command: ["/root/root.linux-amd64"]
      pullSecrets: []
    extraEnvs:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: krypton-secret
            key: database-url
      - name: KRYPTON_ROOT_KEY
        valueFrom:
          secretKeyRef:
            name: krypton-secret
            key: root-key
    pod:
      securityContext:
        fsGroup: 2102
    extraVolumes:
      - name: kmip-server-tls
        secret:
          secretName: kmip-server-tls
      - name: vault-data
        persistentVolumeClaim:
          claimName: krypton-root-vault-data
    extraVolumeMounts:
      - name: kmip-server-tls
        mountPath: /etc/kmip/tls
        readOnly: true
      - name: vault-data
        mountPath: /vault-data
    extraPorts:
      - name: kmip
        containerPort: 5697
        servicePort: 5697
        protocol: TCP
    service:
      ports:
        - name: grpc
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: kmip
          protocol: TCP
          port: 5697
          targetPort: 5697
    config:
      kmip:
        bind_addr: "0.0.0.0"
        port: 5697
        tls:
          server_cert: /etc/kmip/tls/tls.crt
          server_key: /etc/kmip/tls/tls.key
          client_ca: /etc/kmip/tls/ca.crt
      key_bindings:
        K0:
          sealer:
            config:
              secret:
                config:
                  name: KRYPTON_ROOT_KEY
                type: envvar
            name: root-key-sealer
            type: aes256gcm-staticsecret
        K1:
          crypto:
            name: kek-crypto
            type: aes256gcm
          vault:
            name: kek-vault
            type: unsafe-sqlite
            config:
              path: /vault-data/kek.db
        K2:
          crypto:
            name: dek-crypto
            type: aes256gcm
          vault:
            name: dek-vault
            type: unsafe-sqlite
            config:
              path: /vault-data/dek.db
