apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal-keys
    namespace: openbao
type: Opaque
stringData:
    key1: ENC[AES256_GCM,data:2BKZznx4hF3UqGsIcLvPvjejpCCe7o7LeQ02umdPyM8QPqsX/iotFcKNKQ4=,iv:1XZxrbffmGMJdi/3T7Edr4T8u9EH8bCwbWzOhIblG6s=,tag:THijAjqkolTZZ6xdx8mPTg==,type:str]
    key2: ENC[AES256_GCM,data:Rp7XWQKXi/7c+7Zp6CKG/ws6CjZveJij6hPov8OGa8pYvL40Op0WuUMcOAk=,iv:2TMCxolNcYKsaZZZfXgEzXNSV43gw30btFUfvAzUalQ=,tag:BNGMcVdhcxGkSE0o/h5WCg==,type:str]
    key3: ENC[AES256_GCM,data:LmKSGl7NdvO90XUu5zSWUYgKuR170Gt1x0sX0QZCoPbF2Us0IjvfTYDsFtM=,iv:fYXiQJ5F0DLEsWDwqjH2tkdPSSIP4QPPRpeZrWFc9Q4=,tag:eT0HTfC4WrkVGuNunLmEfA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITVNzVWdOeGxLTThZTXpX
            YkhTRGE5QmRNYjkrNTd1bkh4Z3l4YllST1gwCk1WSnFkWWNXcUZmRCszWmJFeDdm
            SXdVdmpoalhmeTJQVDRyOEJiRHBrcjgKLS0tIGxCSUoyMkplM1ZlaU5GQUY1Vjgw
            Ulh0bnNPVG16L1lDQVVPNkxXYlNNcGMKeRpAN+nQuY8pmsYsjhbDOIB/Iv+NYIAq
            pKKShw2Bs4pYqxWyR/1n3m37XJbb0JeQn6y7/9z1TKkHj0eCVSLtcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcW8rYjV3SWU1SjNyYVg3
            R1dUV3JzQnFMcGNqbjUyY2s4V29NZDBJcEdZCnNGeFU1cTlLdS9GQ0FFWHI1YzJ5
            NzBIb0tTUDJySEp4a0k2U0l1V2lwWFUKLS0tIE8vcGIzRUdFV05oN0xIYXArZHlU
            cXY5SWRoR1Ftak9WRlRrYkFVYlAvVEUKTAV7CT2kAaWuFMu0G29EKfeI+tO+8psd
            jdrpXYdXpjM9NMwI1+LqncIGN+YPBWJ8m16feeRj/v8E7QMYU5BFzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbmpuWTFYYmcyTy9PS1o2
            Y1dMdWVkK0ZiY3RQRVdhUnFKMFNoRi9oRUFzCmFWMHQveE15YXA3RkZidlNxcmRP
            VTRrWkZhc0dEUnFObW02WlJXWkVpRVkKLS0tIEkrSkZ5N0NSd1h1ajB1ME1SNFNa
            YTVJOGY0STVLSkpSRVlxc0M0N3BNVEUKKyLo94ytoZ/ALEuREyLAMJUfC0Yi/lJt
            0BiGNTrqYZyMnHoh+dtGRTQt+qOqEbMhKyDy5AbnLzC3EF5RNHV/4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeGp1UzFSSDhQQVE5aEhN
            YjBLeWdVWkRvNDhsbCs1QWNnZFpRdDdKOWpzCmdpR0tvdldxYUdDTEtrSjN5eWRP
            clJHRFVrdmo5VGs0MHFxOWQrQnJBYUUKLS0tIHltVXErVWY3dUFDaG85ZFZvSkJv
            WDFNcXdkcEQ5eE5YMFJjT1MwTjFMVXMKaEuGye2trEepgWG2w0CLIKQ+jMjkvFOK
            7y5Nqs/QC9m55+IEq64fMdkFoqy7WI5S+6fvJ6VpWO0aAefU/nQVow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T12:08:36Z"
    mac: ENC[AES256_GCM,data:D3nq/bN0nTmuA4mVU68j1tgV1tMrbbNYns1OVKPfsT6Elyfwhv6ByOaFUCimvM2cG3ecpYBH7466zeepY9RvuJQw7tww+bDPcYuntx57w67f4Tf4hGqxDq4LCtrJ/fyIvChrAhX6oEiJtvj4hx64fLMJErnCQvtDhpvwN7TLQFA=,iv:UZYc1Ey1LBktANTsGuAgWzME8kGus2mvEP0sJBZWBlI=,tag:8xxrFctfWKXY7CoEHwujZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
