apiVersion: v1
kind: Secret
metadata:
    name: openbao-root
    namespace: openbao
type: Opaque
stringData:
    root-token: ENC[AES256_GCM,data:onLPWziYbpDSSls1l9h7C3ZbAOSs+0E0aRg=,iv:GU5vF6liS8YA2bMZ8e47gHdWojuEevD9uREkRh7JhNQ=,tag:xuUs3Csr5tc/e7xPRw+YPQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN3B0Z2hHZEJERUc5L0ZW
            bzJvQ044RmpUalNvUHc0OVhtS0kxUnY2QTJjCldkMm5ONXVlOEdFbzcxSWRmOVdp
            bmhBbk9nREtBOEhpOVd6NHA2OXorNE0KLS0tIGU5N0hNWWNMWjNuTnY2UkxLODJs
            Skc0bXczQW1HWC9UTWxoRnJ6aDFRL00KyBshIB07cmTNektw8STrnhYATYZK3zJ0
            69uSkQGFw8b7Cy9+LAM1BtqBjWmQeASu421NkwONDd6RSR22XGjfhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTm9MZEFEb0Z1K0tGV1d0
            MmViQm9zY0hrczQ1dmxSM0tIaXlObXhDaEhZCk8rLzBybWFNc1BTbGRQTE9MSkV5
            aHVPYnhBQkVabzNCM2F1cEc3WEo4NVkKLS0tIHdxdUZDTkZ2dG9aNkw1ODJXdEZv
            SGlOOXFrMUdVLzEzcGF4bXZyS1JIdWcKukdUiBgD9616SsFT7JlIIVGY80JS3C6Z
            lp+5rm1tv1n4BYpy9nSIIe75OFdCoyPzNbndsZwERTGEoWS2KX4ivA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOTZneng2bWJOWllrUHhR
            eWN6TldqQ0x2WXI2NmxONjJvbERzTnRlekRBCnhyNE1wTG5XT0lxeWd3RnRONkZ3
            K0pJKzRaOWphUkZhTGFtdjZndUppSFkKLS0tIHlmeU5nQUx1Ty9oSlZVMC9UcWFi
            QjB1alkwbUZMVndOQjlFcGtyUWFjM0kK4gph9EDU7tl0JDht7hUCMerGsozawTjK
            xkS9XjNscVhU9Tn90oBxWOvhmb1L7zYL+o00s1N+5IxC0Ax/cpsavw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZHpxYkR0TXhtNklBUnRX
            b01iTEpDNXdKWW1oODJmc3pXWEJCQVBadVVVCmNXdGNEVGFpbURoUjhDWkl1NVVU
            SGdoMXlHSzdMRUZvcmlaN2hCVUNUcTgKLS0tIHNyd1hVeXVtQmZDY0QxRXBsc1Bs
            eFlQcW5iYS9DckRLemF2bjNaeWMxR2MKx6FdunRUn58uO5vtowGuivLpG5nNw7Dl
            TV9eMWUM4cNy0yLsBg5yUJ9k0tCBFeAsMXyQA21b+lZAcuatVarQGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T14:41:30Z"
    mac: ENC[AES256_GCM,data:u1efY/k9x23F7aM11GvPAHiyEI3Hfuru9m8I8q5GiGzrBD7of8VhQNT0KpKBtKyT+2rqM8Bn/J6M/Rd2QxjspAMfQgHOFiN3W4ooxBXALiVBXzwN3VXi7zS0ypLWgBVQgOtMbgrmeOx+ACu72PIQ79Pis8SI3GIB1F0zgelVHn0=,iv:t3XKYCZLMrQvE0djiaQdzhm+aafoM4qeujgPicFCy9U=,tag:CouVd9BtV/TESud9pWIL6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
