apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal-keys
    namespace: openbao
type: Opaque
stringData:
    key1: ENC[AES256_GCM,data:CW19D6ea8/AU5HxH9eQAkug8ptD+oIrIwo6/ORoUIG3s0Cus6J9yAtgDJWw=,iv:ZGRCQkZg4+N7ggtLwckyaKOR8Ef15rLK4PMIp2duN9Y=,tag:9hXXnmWdbctA78MhMtAaCw==,type:str]
    key2: ENC[AES256_GCM,data:cZYpIy9DUTbI77I/tvuZFwAg84q9mOIVvX6WwP1kQDFS4qnDKQwbO/Q8M+A=,iv:2ZpqoFemOWE5NxJQbbd54ZpgY7tlCjO3pTdU1rQA4F8=,tag:DZkswtpulrqyy+t39qNZ9A==,type:str]
    key3: ENC[AES256_GCM,data:jD2hAjz1fN6dIDawbYnvvI5PGAY8zc58r99ErtQxAqkaqmhCHwFPZvPD9sQ=,iv:5hVnjXEv7ardj3JOyUFzYGOjhXDMxe2fgFeVVjDbNRM=,tag:jdquCb0BB3UuH75DydX+rw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUzdtTU1KQU9rRGxyLzNa
            ZnNETmtQU09kOTlZc1N1aEkrR21TWjVNeFU4CmVTT2VoenNWdlAwekVJblV4YTdn
            K1ZnblBFU3o2dXIxby90blRJYzUvd00KLS0tIExDUm8rQXBUb01Da0xOQ1ZGMVR3
            ZE81dUpyQ0pvT3o2bGoxTHVNTFkrSlEKOXNc0V0xK10plQ+dCsd0zv2u0CpZTep2
            RESPQOOOS4D/s56+hitvn8ca0+0tWVA0h6rl299cFjBBtDehNcihjg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUi90c1Ira0hIdG5tNHc1
            NWxTUmZOSnF5VVdEVVZyU2V3UGIyV0VNNVZzCkVKcHNEOE9lcG5tcllCelFPUGRx
            a3RpVmJJeElMaHJMbkxXcnpCS3lBYjgKLS0tIC9vbUNrVUh3c2VXeGRreElMU0JN
            QVdISHB5cFVKSVNRRUdVSjM1c3c0ZUUK2NpUgpkfadeYZnzgMRrNNelbBcDvhQBS
            hEK4n32eLlYUWeq5RnOJtilsrJ0ZPs5irAP1Zyl0V2pTJ47882/4yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eC9lcWVVMHpwS2FtV0lP
            V2p0NVZZYUJSR016dS9pVy9tTE5DNnRXcjBZCmRYWktheFBEQlp3WTZ3TUplSFgw
            QVQ1NXl5REhTUnFlYkRkZlhIOGUreVEKLS0tIHo2ZzFaeWtzamsrVkZoWENnblJD
            WmRrcGQrcEs4cDlNTU1CNjloalI2eGMKB/S7xzHot72iiH9zSGWVw1RpS0YV3Yvb
            wvihBohn39O+HVnm0Seo9O/CNhS9ioiCw78m+SbGcv1WfKxEvq5NuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNTJHY3lNM3YvY2hHVUhH
            QlE1ai9jTFpHSStGa254Mjd3RmZscnhqWGhvCkRwYzY2am96NmowRUZkdzFkbC8w
            UjVldUw5RGdzQ1pucGljVDNibzlZek0KLS0tIGU2REZNZ0llaWlHeFZDcFJ6S0NU
            cXRFUnJXZWhPdzlMNWgwVjlZTlhJbVUKoAnsV13rgfr3P8fTsyuV2A8mKA/eROUh
            b60lLHGvQyVu+B3ZS+JhjlofVit45x7eWLbkh6IU13EJGIgga12Kcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T07:24:26Z"
    mac: ENC[AES256_GCM,data:MF8kgE/6debmDqSU3ZU3OgzRp7j4Hg/kDNtLV1m52xt2I8qJwq3QaNXT+qIJfsYdQdOEXdhiqgr7eKHmFx60FAWNq8WWXS8CmZNXC6SWcrCd7/gceLFrpt8TQ2Yo/LpL7EkNS8aVGk5acdpq4RofTnJ8RBCiIGOqOBpVY77vjD0=,iv:SFFrV/Av/VPDbikpKRgt/8arBfjRsEwRjuYN0X9RIjc=,tag:+2HPiMRPe9Xmt2e4gMPgIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
