apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal-keys
    namespace: openbao
type: Opaque
stringData:
    key1: ENC[AES256_GCM,data:kQom5PDOFDYE+E++fVEFWbBJdjMMc7Vz5wrdtwarEYgFlapAJ5TCMiHMeGc=,iv:EtbiQIMq9lcNUMP0KaHCVczJXAs3OAB7+bXdJobOjDQ=,tag:38GNb344hLxPTdt2RRDYwA==,type:str]
    key2: ENC[AES256_GCM,data:Bw/dkShxR6NIBdWOS/DVXNE/CuCky1Zuz2U6fR6sbOaFVY4laY6G8eaWaL4=,iv:w2VHvXF2sRvbjNyqLH+G2qlprwDncC31o0UB/sH8kQM=,tag:PtUBrSCDXfBa/ecx4BwG9A==,type:str]
    key3: ENC[AES256_GCM,data:NxSP5QaR3/g1NbV39WpZ0NlOp6Qrfrqcah1fr4p+l2iOTsJgtRaU59kP8aY=,iv:ru57SYk3Yy/xut2qW+Km3vV4GJ7pgITAOiDrMZhcgc8=,tag:rVOszWpwHwpnecVOlHVQ4Q==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSlR1VUlPMFpRMnQrQnYw
            K1B5WUUxOWZ5ZFVGV1EzYUxySEFUcXdtcWo0ClpQV3gwQ1Y2WUVnUnBzSWlJMDJi
            NVN6aFo3R1hnUStkRDIwWUlNQnFCeDAKLS0tIEcwZ1JMRFVhWFhheFplUnhIa2c2
            Ynk5Z1liNW56ak1SZzRmQURseU1Xc0EKKEAYN7o566yrtwT6Gc90AVCll568phqV
            tnW/Z1DyfVXy5g/XABrLmkQPtQpXVXCGLZq8IIGdycRRVQ42UXIauw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UVRhVXB3WnZwT2FZYkQ3
            ZWRyQ0g0K2MwZjF0ZkpVaE5BKzBTZjA0NHl3ClVlbDJDSDE1TTVFUVVWTXl6TU9V
            c2h0ZmZLU0FXTlNzbnpkZlovcU5uVDAKLS0tIHVoUUFaYzB0ci9vdHFtTWRpL0pj
            WTJVWHdHZGwvUzVoYnNjTi9NcGVxSGMKLhnECNN2PWHVX6l1K9u9F7uLNjM5QEy7
            BUQd4ha5Ytcus6RUXokZ1Eriy5FhaAsAyBGmEihzYCFCNIJBWj2KwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra1ovaVpvaTBzNmhCWHM2
            bWZWNDFzM3MzU1AxUGVCWHlYZmc1MDk3UzFFCm5DMGNzb0xEc1JNM1ArK0Q5ajFD
            ZDNkZFFpeDM5TFdXY3lVZURWSmI4bncKLS0tIEFKK1lBN2ZJMjVxU2I0OTQwR1dW
            Z25vTlNaY0dyZmxiTnB4VjNza1ZaU0UKXMuGnd+Fe3KtuU3g2gZlrclif3dgDCvw
            Znvdsy85ujy80UR6EVqgweZi2XrO2kx5DRtw1Dpu/vdjNqLlk8CVcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWEh4RDhGM0VQR2lkZWt5
            cU02YWY4TXArWmFFTGRJVzBISzBoVDZzR1ZFClN0STlsMUozOEhxNy9IV0RLYnNv
            UU1rd2oralpnbTFDOEVQRmRNT3hyV2MKLS0tIDFBSW0rWmg5WllNdVljcWNUdk9J
            ajlhYkFBZEQ2bktIdmhqRUswRVMxb3MK6qgHsbd8SmNOU8PfnYQNjuJxDiKLEKH8
            5XwWLfSC3TaiSMH9fL1Qt7yXVw8d/vAVHFQ+ZgPQOtJ28kxwsFccUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd0c1cTdQWkVGWWdsbkxn
            cFBiKzdYNnJLNXljUHQxMm53Z0xxVmNOeGk4ClVtS3VFSzhtM2hLYmhQeE9IVGo3
            M1JhbC9qbDZuVUp1VkFxYzdMcisrak0KLS0tIGxyY2hDSXRnS0h0RVNWZjF3Rytl
            dlJqQjFsUnVDK3IreURpMm1lS3VaWm8KjmAQ1e63SiN5jDCWn0PopXIg0p0pd2rm
            1ZaALDmehnA6ovo9Zt4Wyd7m5hyV5MbsaxmrvJfRAOmoR1JLVUyMNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T12:48:13Z"
    mac: ENC[AES256_GCM,data:iVHd+KAbA4woKFfgR3RNlda2cIMZZwYycNGAR182U2hAbcD8nxnw0uZVULmYEecjtIaQJdiRsAPQ1rEVdXEY3MnvqmCp5rikUeyMmOoPhH90Rh0FnyrUCFdoHr6GMik2HczlNFFDwfxes26Mhch3RgVoXKOjAz1edQjMMFCReag=,iv:MQn8zK/m0XBaJGQTYvnxZkG+5zScM0FaVi22ie4bgpw=,tag:ZUSvo49909GTFIFnGsElJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
