apiVersion: v1
kind: Secret
metadata:
    name: openbao-postgres-storage
    namespace: openbao
    labels:
        app.kubernetes.io/name: openbao
type: Opaque
stringData:
    config.hcl: ENC[AES256_GCM,data:MM/ZKRXPraItOy99tl07AhwuZXNvuspQsTGAsYZjfZEDmTPTGOXWZCeDczKoxLDqv88RWoQokS/HL4mZyeGEKmjxqCU9X7iblh/7dy6tK8sHpVn7EflhgJR2e1rhi1hb/x3W42Jgt5aYXsiBRI0F03dc/0iJBhI1/mHBvrOoXhv3JphNTXxoUKgytCMEQnnQd7xs65x/SrXWiG9Ri0QEETne649gi23BEoikfyIc9WSMrv8lh2b4Kmr35X16W6l8+9yMXKyclQMUyqmc,iv:10gRFWVUsg6X7R2MjkkloSxGjHLnAgC7+joyS4hODdg=,tag:0eMAvCwcuRM2lMtQnwdF5Q==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucm1tdnIvVDdZZHFLOWxU
            dUJ6NzZRSDZhK3ZoTlV4TWhKclpZbnowSTE0Ckl6NU1OaDBVaXQwbFQ4N2RVRllr
            eVBqeE1UU1djQlU0T2MxWEhERy9XYVEKLS0tIGg5ZlZ2LzQzbnlXZ0VBS3JqYmlr
            bE5zeUNkZE1tbHBPN3JRWkR2Qk0rVG8KHLGmyY7vHbP+7A3HMZ6DU/uvyjMC4HSQ
            MnJSz8Ti7hv2ZHedyItMNsmDQoxjuaGUextYDQbaqMd2qclPRhK+cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUkRjeHl6bkpuUURoNEhB
            dWJpMEVkNWR6Y2NHcnQvRkUyMExRQlBFSURFClJZMTJLaHQ2U0hkZWdCUEtadUVU
            ZkdVN204T2hvMllsSU5uc0krRTA2MzAKLS0tIEVnekdsOHZ2UzE3dVNVcnE4SWJX
            TkpIZHR6alM5YW9zNm1SYVk0WTNSN3MKEsKDQ+4pTy8i0IGuLKkJCDJJs91MrKO8
            1XFQLfdRCKc2sAxrnL16Vbdzs25TdwCcDk4Jc1TzbHQ2V/z9A/1QtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUzJod2ZCTWI2OWQ4VHRB
            dzdpb2h4QWY3STcvWkdrMEpUVVpzNTFRN1dBCkZiY2cvK2I4Z3g4ZUN5KzN3emRM
            cGFhTlNHd1B3Qnd2cDV2MEI5NDg4cDQKLS0tIE9HdllNcFlRRklnY1FGY0ZSS3h3
            NTkvQnRQNWd6cDNUZVFsWjN6eEpZeTgK4q2+bB8aQ+5KUIzKxm6uktDdhp6m08y0
            N5IccgM4HDMYYrDxG6bAl77Ko/WcEHTTybiY1zub+nDM8Ybv03Zm5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeklpOTVSRDZrelg2ZE1r
            S0tBMWZMdTloWDlOZnZ4cGdVTFBTeHpyaXdzCjc0VEhpZmpSaUFGbFZtR2pRanAy
            VnhDbFo3Z2x1MEpia2tKV2tCS2VUcDQKLS0tIE1DZGpRMXB6Ry9RbmVMZERQSVNw
            WWY5SFcvdG5Nbm5aZEpwdWVWVkcvZmMKrYnSjiRBTbxpkah21VbK5tUKZrdf5c/+
            3mwwqI2tfdV2aCx0QgnDBcsvTaBdssOqmsh/ruPVWBMXDUHxugyivw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T14:41:30Z"
    mac: ENC[AES256_GCM,data:5DmSd7LMoyq1Bjy0zyL1BnEwFXPDWUI8CsukJOz7xsQmpcqAdrg7hrjzM8C/h0BGDLBLDlqyEC7fNYu53nCRlDR9JPTYzTvEjm5nGbzhkrxxOOJpglk+88MQ87A4C3pY3N/ScplpBo/wbfNTfcxf7i6jr03hrVc7PPZvid9s08E=,iv:knnOOLEtQQbKYelpT/JOWs7lBkrGhbFH14sjbw+QBCQ=,tag:h9cB1fUykvM2RHLKgdHwVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
