apiVersion: v1
kind: Secret
metadata:
    name: openbao-postgres-storage
    namespace: openbao
    labels:
        app.kubernetes.io/name: openbao
type: Opaque
stringData:
    config.hcl: ENC[AES256_GCM,data:1WXV45LWhOTEq4pHDNFu9S1xiUWGalQ9txGpiL/GD59ecg7AWuxj8KKradj/HLd/0AQAAMltbQRYa2xY7hb7Yj0ApFH6UBij0V/d1VDZSOnAbfXllMrkWDhrx+TcZ9yAwCKz+NZdGqetIovgHO515rE4rS3Qb0SscOXv8ni8lBfFwo1qkUl4C+wFNS2tGBGhD4eWWPkjWO2WEkM8+74dBumJeB/R3fWyqXfqVLycoIrI1yvP4N085g+O2eBWF3HWa119n3O5T24aTTP/,iv:FfbBn35d+ehGMrZGL+UM9sZgkWejbZeudV9gdINnTDs=,tag:fQ8pVECNm9e7FDgu8Rslgw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXc1h2SUJyS1htQ1V3NWE2
            d0c3QzFUUDdYVWhDVnE5dDFDV0YwbUVncDNFCmVid3RRaTJoWHBSaWprWGNMdFUx
            dHJwZ1dzTkovL0I4QlhsZi9Uak9yT3cKLS0tIEd3UTVxWXhtVVB6SHRXSTQzU1JD
            QktrZWdXZFBPNnJobHBiby9TUmpLUzAKeP1zQeqKOR3jWK9VzT/qYccL0Rn7lG0h
            MNm+y6xPV9fqqqwgVfSv9qHJydcLtinFHaCqENJJLXngJNBP5Q7WRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMEI1R0hNeE5GMlRZb1g1
            b2FBK2t1THNMQjhtVjdYZWhOdXF5Yi9ZT0g0ClhGVkNRTlJWQjhBVy9qeXdkRjdK
            S1FydC9tOXlCeUdHRXJuMnFDSFhFQ2cKLS0tIFUvb1lkVGJ5SXNZaE4vZVdRNXQy
            L2tjNm5RdmJmQlZzRTFzVmIzS2hNYlEKz2U/paVadqKubbB+dgjALgwtWAVYtY4T
            T9AkMRrOSbMEG/2icrJa3AO4nqQ6vKxpluipDRNy2b14vP/ra93p1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aVYvV2NFYUpUKzdYa2h6
            dUZRSkxSWFk2VmhubE1ObGdPMk1pUm9ZaGtZCmJkSmtkQm9RMnFsaHBzV2dHUHdX
            UUIvZncxYUx1UUhSQUtwd24xcTNsRkkKLS0tIHJDN2hiVEN5R2lZMXhlMnJGZkxm
            QWlxRnUrWmVVbkp1UU1mMXdaaTFZM1kKFtIJIBFQwBIS8mdPR06R/J+bLHXuLWaK
            ARah8Qwf1ysAp3uC6w0LlOLtqzTM6fI+6U+b7ULYF52sUoD+71DHwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2M1NCalg0YzBFdWxnWVVv
            Vy9Lb3VMODlla05rRWYrZm54YnN1U1NoOVI0ClhzSFQ0dEh2clBZMFlyNnhPRHR2
            T2xyTW53ODRZM1dna3ZUKzVhUnBlNlEKLS0tIHFEb3ZqcUg0d2dpZzRobXVQZ3hv
            RElFanpMdXYwZlJlNFlsOFBSSlVCVW8KeWgTTS2m0q3+fBYBhvwzsvnps7HF2mII
            TMeyh7iRzhG1jHTR5frg4CVJuJv3FumwVs7tsU0EVttsazMQiGpBkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T13:30:35Z"
    mac: ENC[AES256_GCM,data:euq25TFlMS7Tdgt9jnNQAt2YRTHW+kDanOjI5shhOfm0LidO2VNCqO6M1J7Ls3kDw3O98h74lxW2elktHECpod6CF3ZPj90oMaMa3j/n8/74agUOVnxN5yKEwv//LTmE4K+eAB46+aDjBEjNZu3EsOWE5TRVPXgcmdg948uX7LQ=,iv:OWdfnOxzGV0Rj6sntpIIg0R3wBvNjuzT+DDVtMveFrQ=,tag:0YBcN1k039yRzoRtBxB0tQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
