apiVersion: v1
kind: Secret
metadata:
    name: openbao-root
    namespace: openbao
type: Opaque
stringData:
    root-token: ENC[AES256_GCM,data:BmqtnZ/eG3uPrOqxGXkSRIBmm6IyITxrDOE=,iv:qKOM2MZD3emasBlgnLrUAohJQUr1izezQtRNOunU5dk=,tag:C16MeQbATPNQgcUIRsnOhg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZDFVU2xuYXpiSm1HWjlI
            Rk81cE5LWGVzaTZOTlZYdklyWk9DcjV6WTM4ClZVS29SRmxTd1hxb3h6TnorYkxJ
            akE4RVZBRnNmbkxzb0RxbVZNbVRGTzgKLS0tIDQ4MmMxU25pYk9MQlJHcUQvYk5O
            K3VwZ0FXNjRScE5CaUJxRE0rMDVFTUUKsCoJKt1okYoSufFdEPKPZ29EUjg8DQ7J
            vHkfYTr3S+rG3rnJkw4iWXkLdNY1/fP4lJuwVxHUwHElrw3uOpq5aQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEpkczFja1J5Zm1LRjhr
            QW82aWZ1NTFHYlBBaElmLy9Za2hhaXIrRWpVCnNGaXU5QUVVT2JJY1Y5WWhlVzda
            NVNjSWJRN0RIRVZ3KzJiNSt5RmhpamMKLS0tIC9OT1I4NGtZL0J6a3I4UktvN2d3
            VXViV3JQbDY2NmVqdHN3dVpFd05Gc2MKHU3nAvP/+2TtyLeaJGC6MBSSC6/IbcY2
            zT+62NGDuougNFBtIAamDmA09EoYXLyM61tTqbWKA10Ff9uqIYBqpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQ0FrakNhL3RPbnMzMDZC
            N0VBOEJFajJWN0J4R3dGR21BYis0VDBGb0ZjCnJ1c3FXdkVyV1ZsY1ZDeDQ2YUd2
            UklONW1ERjhKUGZRc3pWZjF3cTNmdEUKLS0tIFYwZTlnWXNYS2ExNlhxUVVUUnNt
            ZGM1NnhhcXNvcHcvc1hCZWNQcTAzVU0Kd1I6nUm2ymybt8EeucdqEBOg46lLcpOX
            2xQF0Q9HrNBYdrT2u1YmvUEitFQjPhcrA4tGi/6BHZ2LQ89e3dpL7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVVV2QThXMDFFb2lPWm5a
            R1VhR2tKbEtKRTVocDRPeXQwazJyM1JXUXpNCkx4NjVOM1MrcTJtWGpuVkt3Wnd2
            TURBSXZoL2twQ285RklyNEhEb3pqdWcKLS0tIGFFN2pkcWFHWmpGczVHY3VsTU4v
            Zi95eS9PNWxpamozSG9NR3c0dEdoa1EK6lCEpFMP/l+6b3pENRLdP4DPTg5wzxLd
            5bkvj2E2T+nvdGJ19f2YPCuHcaWK3R40Mudl0dU168gahfkxoOi+xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T12:08:36Z"
    mac: ENC[AES256_GCM,data:InUSb5DH3Vbx5HF4lbbLKP4M8hpyLyEIjjXHGWEPO5lxZEvMuDFImlwgmEkAe/92eg+KEST9pFYBmqWDY2IyC+rEPItq1mUM43qQ6mkCHLRyyQOw4ctcKGq9/wW6iR3o7RQwMAdDdV+/timfvBHWy7Ysz8K7d9gM1QQO/5ejc8c=,iv:g9XtGSjkoYZs2e3hFX2hZsuiFTCQ6q+IwczcRVL8wsk=,tag:TG1sLWO7YP49m1wOrvhEvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
