apiVersion: v1
kind: Secret
metadata:
    name: openbao-postgres-storage
    namespace: openbao
    labels:
        app.kubernetes.io/name: openbao
type: Opaque
stringData:
    config.hcl: ENC[AES256_GCM,data:fWRmKAZdyy+z0KvlNW5YJ74k29h3BcXGVzIoQzb213OsyiSOiXvJT4LAqr8W/HLrF3Cpr0/6Lksao0m6UUJbGQAXiDLjSkb6m5kWhLDCjjbzMX9I3k4SzCrInvSqzTo6/aeCtho1IANuW7pOd3uDUEMs2N0Q/SIT284v5T8DxJYRao1L8eVzeMlQbVi8/HhWRgifNiauyHiMRrUKllbrBLZrw1emSN9q7R49CBpqlNoSG7NjFxUbBin17oKXmL8fU/ZO8EzbqmYYgrcU,iv:loJtnRaemTkVEziL1ctR04nFYEynjIsyxW7eI2sN92E=,tag:+/vi5FdetnPkdT25IThCOQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUEJrcDdFbWlnSHhvcFBv
            Wk4xWmlNd29ycHA0NU01ZGtzS1A0T3NXcmw4Clo2U2lBdU9kOFZheGhrUGo5amE0
            TkFvcStRTWNpWEpMbTR2LzJNSTcrNk0KLS0tIGlUclk0U2pNK1pIN0wwMkFoN2F2
            UmwvVndoWUJ5Qi9keU0zeUd6OHlWRUEKpO3Arrbf7BEfHDe1hYSohO5wG01lUipA
            w4oPRGsH4N4PmWzZ+zIZmPSGbv3W5MQHxm4OM+ZNpsaAiuigdt59WQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRllleFJMRVhlKy8wQW5u
            TXFORmNjVHFzcStYN0tWeGFyMGZGL3dMYVM0ClUyM1ZqSHBJVlZqa3FZREhROWFl
            bWxuM2JhNVA1NDhEMWNwY3BWM0RkSm8KLS0tIFNJT2ZWOVRuVk1JWm85aCs1NWZN
            akZQSGZKTHQydkI4Q1ZyWlgxSzk5TWcKpH4bFNCtJo26IbCKydIyNDhgekXNzEw6
            3YV/pNx8Yvl01A8rNWb1cm8RIG8j0U8wccWqPRweL+RkHwrCk9zk3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTzlDY0sxVWJHZzkvaUNx
            QlZIeTV3WmI1dElKakNqeVJ3N2d5emhvZUJzCm9wcUpFbk8rUDU1WC9lZTZDQm55
            Tm1rK1JrZllyY29lOHVuSTVLM2ZXUkEKLS0tIDBFR2FzbDRjcU5jNlV0aFJPSzFi
            R2diSnN1UldwZ1BXbWtkTitNN0VnNE0KcIWSc5zBplDL98Bag4zdFGJUpRkKslYL
            VGkZsaXlUN9SF4aox5C0kXpcX28t72oy1OVesIZsOe5S4nHbmVemWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMGFLY08zb0hpbUN0OEJ2
            eXdsN3pBZnZwT2dYL09YenVFL1l3S29nRlJVCi92OUR0R2dWQlcxWU5taFA0VDhz
            enNjbERHK3VSZlNaRi9pekhCcHRHQ28KLS0tIHlHbG9mZEIxblNWWDQwbjltdkpt
            OE1TT1FMRW1XeGkvYTcwbkxXVW5qZGMK0ulwUAZnP15/v0x/AgOoPrFiqUFNKYCn
            nk+/83cWWGw3INqA67Kg2SoQIKT6CaLhOJ4/MAtTp4uyh+m8V+xJGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:03:15Z"
    mac: ENC[AES256_GCM,data:7mK+tHupLkBFuu4bHU5uYpz11O2Jr9z188L6sPQ7VXLPmGaFgnSlPWvLgKtxqo7854rjbNHbWNIEafZfxw/JUCdkszT4PFWKCiHI9XwbGRYmNCqoZfjf/jj4AVczum1P+755tf63/QDdNNmVlqJHkbNgRJZkGZRX4Wl6tBtfl7I=,iv:M5P8QSn5y1EP78PNiBYc4zZ/mHNJv27HmSKzRalVRgw=,tag:IaoRiIs8XXCWFN2suqj10Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
