apiVersion: v1
kind: Secret
metadata:
    name: openbao-root
    namespace: openbao
type: Opaque
stringData:
    root-token: ENC[AES256_GCM,data:5nfv06eIiCqXrzfFp6Xd4UrvmKRnUsX3r9Y=,iv:mS7pR1LOCXOUq6JijbSTEFGChObeYv+7bRz76LjvWJM=,tag:IBzss7kh75fLtkEyp/HjBQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmFVZjBWNmMxenoxWTFG
            Q0JBaHFXNXc4ZmRSUW9VdEIxQ3Y1Zml5ZG5zCjlWcmRvZ0F1VmZYWjN6RThQUk43
            OXBVZzlxVVNITjZlSy9sb3k2VlI3Z0UKLS0tIFpNc0QzMWIxWDg2OHFaR3Aza3BG
            bFlUMHNnQXhwZkNiV096NXcrcWJ3TmcK2MqIkTA3e0/6Ay2EpmZ+hOkaflWOWtbK
            G7pHTJRVtXQu+waR8lyg5IuGfjDJLH481Bnde6BOpAoZZ8pS0zmpCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd25jR1pMQytwRllzRTRw
            STUwWlJ5TG1haThCaE4zYWhhRzJLYWNjOW1nCkNhQlNZKzB1QjEwQ0Z3SjMwRlZh
            RmU4Uk1ydVc3SXFObkttSHdHT25lNm8KLS0tIFJyVmJ2QUVWTU4xUVZFT3ZUdUc2
            aE9iZGZyUlA5QnI3RDltQUkrY1hTY2cKRQTH+KnL4mJluttsrw4KzgJNcTpqlSjf
            A3rXM5eJiknAGH+GZ01nhTwNIqHpzws/EvTZ+qxJ+gVj1UH7svlW9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDlmMFNiRi95bWE3Tk9T
            RUFaSXcvdVJnVklmcmRqVndEWFp2ZTl3a2trCkY3Q3VTSGdndksyNTNIQ0ZFT1hh
            TkdVb09ORGpoM3AyeGRQTG9jS2tMcWMKLS0tIHN5U25sOWVnV05zdEdaVEJnMjlR
            RU5ERnRJbE9VRGw3Q3ZJdkpIZHI1QlUKiwIPgP8qlOATt6NcpXEaoV6r03kizpj3
            wBlmubSQJD05Yc5GEPYNlCY1UE0iIF7rXjhKKrvLNGq/v4GJiXX3vQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZWQva3E1L1FuOG1SRUJ6
            WVY3YkdhSjhRd3RJVE1XczBwYTFOd0I5c20wCkNPNGJZRkhZU0E1aWkvNW5rY2Zh
            bjNZWWNuV2tCdDNnRHFGc0R0QW9WcnMKLS0tIHNrRnVCaGc2Vzl6MFpaSXF6WS9F
            cHYwSUpWWVhNZlQwRXJqSUNWa21qQ28K+qeYjPTn0aYn6cNKMArsknm4F2o0xgMM
            sE2DrFYJMmI79TzkRueaEK86JLkSPZRgFIZ3q3gK+Yb6Xu6pMEr8Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T15:06:24Z"
    mac: ENC[AES256_GCM,data:k0Z6+C+eLOeAdZQP81C/CXFUkaP23QW9Bd3A62CxNXuSHyJhk/e62sGOzmZpSnleEKzbolBF6dc46a4DMlsFDPlMOoiOjPDYZmAtdTkWKZLu9/TQIzTmPjKbktEwh+PJJogYSfpjm3hJKVHJlRYFM9qx21n3A/2v/sw2wr72Yjk=,iv:O4Dfre1z28XOvAEy1x1Mj7AnSd20anhRSjSHrc15rIg=,tag:jiIKEFRLZYd7kXtgORsx1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
