apiVersion: v1
kind: Secret
metadata:
    name: openbao-postgres-storage
    namespace: openbao
    labels:
        app.kubernetes.io/name: openbao
type: Opaque
stringData:
    config.hcl: ENC[AES256_GCM,data:JfuFHJjUHYkQXSttDUg4oLTRzadq778zZCNvR+BizOUz+7FOLvG3eedpJDCoxlcURltVsdwsPqBRvuaQAl99QFpxv0oRfOZYSe5yaDBiszYVyY35NloXGpO0QWLOuMegviBwNVCM9SyCANMMQZs70U7/galO7qDTbreW6QnEVtBaCJ10OZQqTUUjwlW51rNcK4W1e9UrZgJWVco5FxQjwkCS/8y+8sugrqOx7mCerNxursbtZAIfdBi7/MayD2e5hhKFhWaWw9wCWiuZ,iv:MNSFHxhNT3kKLnp6n2URlL+s7IF3RX84PYDVwxHHxX0=,tag:T7dTCMsGQgW8oRVMSAxPkw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua2pkTGVxM3NMaEMxRDJz
            MUdpWTVVWHNmc0ZzRFRKV043SmxaRDFBQm13CnB4Y0dGb2NIUTJwV1ZYNlV5ZzZU
            VFRPZU5ZZXZ4WEowWHlBcmRpekhuZGcKLS0tIHViUjExYnNZQTVHT0JwUzRhd1d3
            WXQ1cCtGVFFYTUkrZ3lqb2ZpOVFRdFEKyKAiAKFpAS9i4+hROfAt5YuN5o003QWF
            ecSLLzklF3yqVxZJ94GSw+C5US5S9pdmKNc+FN+ZWVYgnrrTQYj/iQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eUhpRTZWV3U5NmhKdlJp
            bW5iRXFYVklaN3FvODMyOUpvMjdvdU5QR1NjCmlvdGVqbFdVdlZOYys3Qk4wNFdq
            QXR6WmMrenhINDJoMkFKdWdQS2xsSEEKLS0tIGF1eDQ0WTZpdGZhZUQyMG1WdVBG
            WHZvL003OWZqYXFVS1pGWG5iZmxheEkKuR6OPZgbOO0MAGEKt6KFsT8Quhq4UpAM
            Lf7nbFe/tf3BDtpRuF7xRDV3s0MyfRfYYSRCBY72USmqE3A2+SO/aQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWE9ES29Na2EzcHFpVERY
            ZGorSlBQNW53RmdRUDlhOFp2bkVNS2lKQm5FClVUcEFhYXU3L1BDN2Jod2pLM2No
            RkVsbzY2TzkzdEphVHhBelJBV053ZjgKLS0tIGxwd0U2M2dJVlJ3amkxUGQ4M3lW
            Ti9XWCtBRkF3MWdLZG5BUTRSSFlOa2cKEtuu7PYQAL4U87C/Km3Nx2THz9tlwoLl
            8kMuS+qKNLG8jyh+iZpyE0Ew6ejCN4B7YC5paQL8B7Zk5kUnpiY8IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaGFIUkI5M0VjOUFPVmRC
            TGhpNVBZbWpTMjBOeGozaFJUYzdNeEd0d25RCjFHNzV0dFVNMzl5eGZiUFR1YklK
            RHk3SDY5Qm1JMHE1a3lCY3A3UGtUYjAKLS0tIFVwZ2NXSzkxV2g2eW9US0hPQ09I
            RFpEVXNRK05wYzhGNFN2UmR3T3hUTzgKUAa97Zo9iVeDimXabG+4zLWzEfkXZX8Z
            yfcYk3Gp5Fq0p+8bx2gXmRr56rZHYnUCvI7yJIgE25W7VefT/SkJUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T07:30:38Z"
    mac: ENC[AES256_GCM,data:+/oGyK7YtRowF0LIQyhBQ5eQn4BJamCVUvuetFKa4GgM400rJwPf0lAayDhN961lLQW62gupibmds/PMTXiJ6sFhngdm4VngmnooHDK5x3mMWzd3CTOI1TjN19cvSpuANEtlI7NjsBb8wFrLXVz67H0G1AMFG5Hw2qt1zRhOwUM=,iv:NaYRg0AkxUxtNvjmSYW6n34udOQY7awSH9RjHjuE3aI=,tag:H9TMw+LTixjUas+HzQ68YQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
