apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal-keys
    namespace: openbao
type: Opaque
stringData:
    key1: ENC[AES256_GCM,data:BGCHWO6OcRNGxN2N9yUaWRXQMs37B0ho2UGU2r7gTupCk9cqQ8aeLPp8dig=,iv:LF0u3hzilTVXISzUFZNg0CtjAvPiTP0cmi7Q2JXsgmk=,tag:UAE3bfRDsb0XHX8qKtoWog==,type:str]
    key2: ENC[AES256_GCM,data:wZaJWI6XrEX7Zbg74xpbFilWgZLVc0Dv9s6c0fsnucHC2oo7PtV7JqNhqdg=,iv:Pa9ZUisea+lRCKsAiGok++QH35YHfVsLFjmky8NXK9Y=,tag:8qGKHyiJfWvopElNCyV6bg==,type:str]
    key3: ENC[AES256_GCM,data:WDbV9OeL/dTsbSWRMada/uHsTjy2eIhZ7dM3rZFRsRUD5O+wcYBL3H86img=,iv:5QWvuUuV1+AkMxjfu9du2haWsq67c3lUYhX7ZJktFRM=,tag:uBGfEKxaejrrIeG8WTG/8w==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcG5WQWFxWTJYdVdnUkhT
            dUtKa01sNm5sWkJUK2lYNTV3em5nRjdCblFJCnA2a1psckZUR1BEVkszR3ozZmV5
            ZUJ0V3p4RTZqMjNrR3ZDbytvUGVoWjAKLS0tIFluOVpWK09ZSEEvbHk0eEQ1Z3Q4
            aW9JMFFoR3BnVWZoNXg5c2lrQ2R6YjAK+YZ330LQdrSjov/GmpbUvviNXGnq93mp
            TVHOV2TcRUpY+oI9T2B3MRGhFyiyq6LZG8QrJecm+DvNzgDHUToLLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeXU0YWF4Si9HYmM2bURK
            MjJ6RTNhcHJiMVRqYkRYTS9TelNWdlkzVnlvCnVzYWQ5U0tBa3VqUzBrQXNWNllQ
            MjJlVEdYV3JBMXRTVWlGa0hieU1McXMKLS0tIFBreVkvTkEzelJuMCtWeHQ5a1U0
            RFFJT0pGZUNMWXRBa1VJSjQ5SDdETTAKxAhyKO4V5o2QbWDJKQbJxAZUKW4bM5Ih
            cmdRJZvAos1y5DlbhwfgcDBt6+vFmUEKxemdCGiFkosGYGeOcW4uRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQVhoWVcxZU1yNHU1aUN5
            YkRsVmptOFdDa2xUaGNudmdwTVp2QXExRVRrClZVY0JqbTlGSnF4T2ZOaEswcXB0
            aEU3dzhMV3cvTmRaZ0k4K0E0VUpicE0KLS0tIG9icVJKRjV2V0dBbmsyVmV5OGdU
            T2R1Qkw0MmpnSXlZaG1BUndzdDg4QzQKXn26INnrxtL921nXzWGykSfrVLM+vcj6
            8HMsZwoiXk/ao+pKCCuZHHmzbeCWGCAIj6G5aFAus0vibaedUzPdgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdlhTUnNndWhHdjFZVjRC
            bUwxajNoNjZTZlErQ0hxTTJsd3l1ZWJLNVNzCmZWNnkrRmp0VDVJRlUrb0JtLzJC
            YjFSd2twZlVZQThCKzZIT0RwM0xSSGsKLS0tIHc5SWR3eEVOVmdHb1pFbGdaM0hN
            MThmdUtibnFLYStDcTZtMktoamNmWlUKS2byJ3LoxhsUIR4q+3hOIS7lkmuqNmM8
            n3t8E1BIu3WOFvjbinLbk/1VMebkrgSaPq6UGVh9nDCJIe7cd5z3nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:17:30Z"
    mac: ENC[AES256_GCM,data:Z4VN6HfaTWVvLFpOLM+O7+4qrNIDchuX/QHeyCjwbeEQ6pokvjKZ5AJdQ1rlqRqQQ84PsXAf7yjf9PjUSW/OdToPbY39djS/RQxSbhwhnJF8IQGMkdIrY4y61kmNS8Dimz3gZoxvgMx1QG2TO+OdI2QCR81r4lFT5yWGx8KXEyg=,iv:zI1r4iXt3CTD1QYZH2LGNzgdmbRDUWyyPl7dmYN+f98=,tag:8o8KKI95xjZ+rltISrSYVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
