apiVersion: v1
kind: Secret
metadata:
    name: openbao-root
    namespace: openbao
type: Opaque
stringData:
    root-token: ENC[AES256_GCM,data:rtgu4JvyRoEjX7hp7Bdsk2UMsOmL9jR3bYo=,iv:qfFwCYRV+espwU2IVknHrM0+z+6vRiOaaZ+zAZDzF3U=,tag:EY0pEtmkoauuBT7Lb6ECcQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUU5PYnRzWUFmUW82QnBY
            aVh1NkY4QjR6aHV4b083TzdBeGZwL0NXZUEwCjU5Y2pXdzRHbGZMc3E1NmxXZTV1
            U3pGcEdNVGNQOUx3OCtrTlhQcFVXR2MKLS0tIGMzL1BaRFM5VFg3VjM0SDZyTHJs
            Tms3T2dna0x5STdxTTJFcm5DbkhNUUEK8fbMq1aar8R+FkzgZJl/UPhr4wF5rsCZ
            ZDDMm2J/6mJL0GjhRQ2+qhU432vGVJIsk/4wlN4jcijMklNSzfu10g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER1NWbmtLUjRpS1lvclV2
            b3lyNjNhVFVtbGJMUjN5SGZUTzVCVU56eFNZClZnd3V5R0l0VUl2ai9NVW5kZXM0
            cnpmU0lVODZzRHFnWTBkSXdobFlld2MKLS0tIDU5bzhqbmRnTitwTzlVZ1VxYWhY
            WXppdVUvak0rVDNZYjhWTWpNbkRuNHcKzNhsyXOcEWTgzKR/QGi5sXsIYOaebRLl
            0lVbDFhkZoU6rtpHqYuqfPaXcjtbN5k8WCMcMJnP4/KS7VQfq8IYzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQlVoRmd1TGNWMzQ5bUJC
            T2tSL2pqRC9vcVp4QmJvTk5rUU9XTEdVc0ZzCmVGWVNTWEF2WnlJY1FFSDBkQVdW
            L2NRTWxLQ3FDM1BqTkg0bjY2S1dsMUEKLS0tIDY4M1J0RGdzeE5hUHVURlBpanBW
            clVxSFh5WC93dE1KZS9rUlNyVUFxZnMKQoM3iCdaX8kkQ3VpaVyyN6NcEy/OxbBK
            /QR7jLE5lQWqN8GMwiia9VkZY/Z6/r+a3CokDXvRt9A40V1+cZJagQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTDRhK0R6ZUMwc0lRckxo
            SkFuUFAreVBmWHg2SDNha3Npb2trQ0x3cWtjCk5nRElBaUJvZjdFcnVRdSs0bThq
            R2ExKy9HamowOUtvUzMxaVJuSG5xZHMKLS0tIHFWMDVLWjFNT0lnQmhyYmpsZXZZ
            bUpjaEEwaFFEdlRvTnFWT2xjbUJXYWcK+tqhGgCNoA3Z3xtfKhCdFF0lHrNAxMpl
            ylos1LMRVJkoqXg3LPZCzSuLPf8xDs7Zx7QkUOG57004kQaIirBrpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T08:58:58Z"
    mac: ENC[AES256_GCM,data:WS3Kcqlb2IGQ4STm43w5Wh/jXX/8TDb8IYa+zoBGcypI0xJ9lAWdO63ELqbPCidouUr0EsPn+C4PBxND0tthrSu5qnb8gBPmxdvOrQKJj5rLB9lRhW5zTEUSEYl71Xu6MNMzaONypc8eWa61FvZ5jSv4wJSBBaHl1vYNm/ZhIVI=,iv:dNrRp2zH5lU3SHryqHVZPg+veIVTupgvsK1BA3uloOw=,tag:YCz1fJOpnbMDMpll2SdRGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
