apiVersion: v1
kind: Secret
metadata:
    name: openbao-root
    namespace: openbao
type: Opaque
stringData:
    root-token: ENC[AES256_GCM,data:zJhOdC5FEfqI0tP0AVEXGuAkKOe9AjhbwPc=,iv:pc2iZHz1AQWLF7eaaHUcDL1o+g0DdF1ZdKs8Oz8XIX8=,tag:DhVVtjX58034HGWpi1OcMg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR1BmZmpKMldoRzExY0tB
            d01uZ3ZuUlVvTWdUbzg0ODI5TGNTR1JLbVVJCjlIa2lCbUdIZ2dhSGQxOW10WVB2
            NUNSdXRQOE53M2h3cXJ4V3VxbmhpNFEKLS0tIDNwdmxJNGV3TkZ3RlVJaU4yeVVS
            LzloQ2RZTSs4eXE4R3FSSjVReFZNUG8KItnQjExXcuyNEwWLSArHmyy922eBTnKl
            96sCQvVdbvSKo76eUbmoReTjKA5bZoufaHBiJhutPsmyxgU8H6xwAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdVhCK0laY0V4Nkcxa0U5
            QVEvbG1MSFpwWEw1dlFrWExMVUFnWG45d2xjCjBSYXlRaHJEc2NLY2RXTGFjUW5C
            TjdLQnhPV0xoa1lKOVQ4VVkrMUV0dXMKLS0tIHNySXMzUmJRaXIwY0VFMmZpY2h5
            ZmNIdUtObisraHN6TVg2ZndJaFJvdDQKriloPKgHdYYmkCEPWhnu/EGG1YJVTiBA
            9kKVNA6cXBweRjPiuVHTBoLO0VtaBmLJYW/+NpMqF5lwFqlKOeEE7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q3VnNVRlRmpzSG96dUJv
            T3BuUTNsRDNzK0srTTBPV3UwbzcxL1RJckc4CnpuTTk0M3RFOHVaSG1uMDN3MXN4
            M2VBK0FzMkIyWjgwQmRiRXh1dkREUkUKLS0tIGQrWXlMWDdwelRYMUpKN041WjI3
            R1JnSGdWM1p1Z2lyb2grMElwODMzRlUKQ/8zWtijvwO6l2H7SGc3h/PG38Lv1KDO
            qaXg+dSkck7q4ohJ0szrO55zCZg2HPF4ag9hLG+70K8SJgsawk2eRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWUZKelRFZWJUaHFxdy9n
            aFo1R28xR0tiWU43V2RZdU4vRThTdEhUMmtJCmlvMG9yUENZQUhGWHFDYm1iTC8z
            MlhyS09OaExzM01Yd0kzWmFWTkh1ZGcKLS0tIDVFUmVMMkxibE9MYzc3eUlzdkY3
            ai9hbm9GZnh3eDdSMW0vSXUxbm4yTUkKYzXu/TPF2qmdji//rRknAPSdRqd5lRQ9
            /cJ6+CHS5pxeHmsjHYfdsSHp7D53MxHZClQmCH+gbUhlvQqFgb3GWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-31T11:31:47Z"
    mac: ENC[AES256_GCM,data:634uYx9GrztaEZlo9z+qKGaXP6dAYLLUymfAKgDATmdIkfq2/Rmi7MjSfKwO76t4cdaPhSlQRwuIOV63R/W7JVHaYsXEl3sFm3AZckyQ2HaICrr+IF+9VvLtzxpcJYbXcDldfhWNR/L4aFcfQchAs69ZqN/uXFbtOickR6HtQw8=,iv:OmY0W1efqVEQGE5CrWV7kMS0axHfTamwch8QDfTT4hQ=,tag:Rfe3hzXySdZ/Z/qGNp01fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
