apiVersion: v1
kind: Secret
metadata:
    name: openbao-unseal-keys
    namespace: openbao
type: Opaque
stringData:
    key1: ENC[AES256_GCM,data:NU6uJyFNirUUL5nGXcPUFOBGbkkkU0E7smxZAFQxDiwaa0THI7T8pdikvtQ=,iv:vRhBAX2f3H15ctCgrSEzDMtauJ43DV6+tDjhKv+BXE0=,tag:xmltAfrYJkLzJwQwXIiLdw==,type:str]
    key2: ENC[AES256_GCM,data:tYQ56mVPC8VjROL6jfQ4nt1Ww/m2LpIR/WTqZAbczOUQmbACJoMet53ehJQ=,iv:0+KyWF33ZWjLqIkyD3Z76kdMa99ZjWoZ0dQvnaF+dXo=,tag:r680lomXjXKubjPB7KrBiQ==,type:str]
    key3: ENC[AES256_GCM,data:VKs4tQjHfkRw8qsH7xD0obo5SwCqzuPlXv17BbJMmwNPZokRBEJCNF8w35I=,iv:YO1xR5vgWl8+jUPIyjoZEBGIzYm5AbmQVjpN+BildMw=,tag:gNNQCdhLozqa0XhOzzeAOQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1T3J3TnQ5a1FLSFN2Z01M
            b2ZzTlVjRXJYVmlCaWdLT09vZHBwRExtR2gwCjF6ZkVPOHBzQ001ZG01Z2Foc0tq
            c3U3cHVVZmc4SnZzYTJoenBldXpNaU0KLS0tIEU0ZFZBaEdwWm9DbUpIaVc0bW5E
            ZG1vZnB2WERWL3FxdjlRT2FZSnRuelEKfade2Uruc3hUVjaDZbtjuGVh11fMLTqs
            5ZfspaHdIPCwCfr4INLE/SAp04Wu8b6/NYbTBnXo3TQDQLxeanaK1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOU5COXhDK0VqbWJrYklQ
            UEdXSTZUcHluY1lIazU3OGlPYXVIYnpqMXg0CkcxdTBTZTdCYkFPZkl5blBWWVcy
            ZUw2aUY2d1Bydk9kSUVpOVRwWVNGd2MKLS0tIHYrd0JVaWFBQytMSlJoRm5abndq
            UlRRNDlaWTArZVNYditQZndLL1ZmNlEK58qGJ6TnutiGRv5DR1f2vMHLLmEFlJSH
            ETxs9QDsravp64Sj/A5lALpxGrig/AT3Ohdxjay/m3tAWSybbPanAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnZqeUNyaXl6Zkl0eHp0
            cUN5bmx1UFhqamVmZU5zK1hLR1pCbU1PNDFJCnFrY0FrSkJkMUN6azNPUnZzMWR6
            UnVjSmdicnFrT0MvOXF4N3pQYk5pV0UKLS0tIDJKM3dPUXRoU2dTemFaYUQ3QlZr
            WUlnMVBDWmo5d2xQNndRc0M4NVBXQW8K6LD2S5M+6wJl/LafTxEp1A2Ak2RV/SiP
            rfIK7EzUR7Rk64NzwZrlrU5XTLma8fSgIehtvERhs8um84vqre/BWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3alZQL2hoQU1mSERONm9y
            RUR6dE81U1hXZ0NiNkhGdzkzenBteWxoN0ZrCjduMG9BWnlMbkJXWDU0ek80Uzcv
            K1licWlHWmdVbEdIU1pzdE5BTlNBNUUKLS0tICsvKzZiRWM0UlFjMmRWV0poVHRK
            Y3F5Rk1vQkZTbWRaaFQrOGVqc1llY3cKhMi17W5lzIbklDn8RQTpgzMVLpXZCcuh
            MFAGvuomdReLKzIOBGfkh4brgx0TrlWIiAMctvBP1H20DwLGIQLZVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:59:58Z"
    mac: ENC[AES256_GCM,data:h+T699aLRmjgz3tR65tAvTaJnkKo/3v7W35tc1Hx5OxUjQTYkWM1FxBQpXIV6wOaTyZqiZucdTgw4mF7gUj2oUTrl5WzAUNAmy1I6ohTyy8/eQvKFZJ4hizJynAhYK3VkyytAbuyWs263eZevuSe4w5+3qdhmmoRUmdGLFkQC7Q=,iv:xTqr23CWpyQO/WH3ipwbFkOeOlFw3Pn/sNqUW/RUMT4=,tag:OE1a94Vk83TKsOLyV6lWDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
