apiVersion: v1
kind: Secret
metadata:
    name: openbao-root
    namespace: openbao
type: Opaque
stringData:
    root-token: ENC[AES256_GCM,data:48xEo/TFLweFam4Xqu2k12ZneYWykOrTfWQ=,iv:7ceFjx+9n2rGinJ59fl5PVwi6qAiuwJ4kFBfAVx1IxY=,tag:fxVWRYEK6fkRIrYaKURDjQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0RrbWlZaGp4OC9nek9Z
            T2cwcHpwU1p1QTVFNUx4b3lzYTErVHBENkFnCldORjc2MW1KWUxZRndTR0E5ZmRQ
            WFREejBlaTB4bzlEb25NNGVlbkcxb28KLS0tIGEvUU5XRVk1RVk4RWRmcnMrQXBv
            Nm9IRkZ0d2kvYndrckNNdlJ1OE5vczQKEnn20sst4qsnY8bvzlmKB/u3iSQeHxd4
            HcOuPaXKLmjCXFEI0ZQVHKcRpQBjKieEkUcboCbubbHf1ptenlD8Pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON0tvZW5qdmhZVm9XaW1G
            b1MvSVd2M3lLS0ozY2hMWGtaVlozWmpRYzF3CjFvMmxXSEZTcVcydFd4eUhqTU9K
            R3VRM1ppRU9Ha29Jem1JY1VFRy9HbWcKLS0tIHZpV1FQalJHaXFaQ2JQd1dJVWM4
            YUxQZE5TZFRCWVozckt5RkYxeDV6KzgKPgttEVZTAsQkFQqM2j7gYBrXViWXyQyR
            F7re4Jwxn4cPOZWC2yaZ4sIrVoH9J29pVEVkWAoJh93X2ID+EN9XbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNFpLODV5TXJLRDNtMVJp
            MnNid1crMTZiSEZPN3V0QWl1cVprUlRMWVdzCkRXaG1lcnA0T0YwWTZ1M2o1NUg5
            UkZnYzJQa1owVkxwcWphbU44VGRuYTAKLS0tIHJ4cU1hUXJadFVjOVUyMnZFWUM1
            QmNLd1JFVGViNjNVczRMYWJhTVVQRjAKrIMAX0smxXJ7CyFEZZ7LfJTIaJaNROhV
            DETVt3gPywc9HNX13x89FARLwdh6xFywmZ422ybe9EDyJ/eRlGx2yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcmVUZUJoUEZnUklJcVlJ
            UmhVNERUSDZMSEFuV2w3N3pnY3p4NjFnR1ZrCmUrOFBhRHIvNHNXL3NwWG1yVHYv
            ZUdMYkRWT281Sm1yWXIzSFJwbkhGaEUKLS0tIDVwVHl0YjQrNHllRWMvdWlReG5N
            aW1YMUpmZ2ZsZGtHVlNZeE5ieENyb0UKKejgnXpq1QCZ3PPOGVF7N7ZmiJec21sK
            q5J9tnjtfpQF0m4pjTKTkC1rsbLoz64DPJPpScRN34uPQzP2Vg/YSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:15:47Z"
    mac: ENC[AES256_GCM,data:/3IhQvlusBrwZcvx8fxUIrLp8yPMk6gpeORSkqAG6YF8knOGmyIO+i9VykbaYpKm4Wu5Pojl2NFnMZkjYk35SvBUJgyA0B3e/tjr43z9GKltQWaSH5IfYM5gLgRBI21Ia6ADZ/tR8aZqwaMlGSSJ+yzinzrDNmTh8OdY9JHAVfk=,iv:lwwE1HPeNN7gmiZM7pIsJYRc1XvGOZ3suDUS5ImNdMk=,tag:zrh+2CHuDr7ixKc4tIZ6lA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
