apiVersion: v1
kind: Secret
metadata:
    name: openbao-postgres-storage
    namespace: openbao
    labels:
        app.kubernetes.io/name: openbao
type: Opaque
stringData:
    config.hcl: ENC[AES256_GCM,data:kiUNTbRTT6xt4J6yeMGCtHcmetUb0naKa4Wmu9/3626QXTtXIrUwBMpCyR8PRMRhub/rDiJQvShboVfhc3e0A5PlDE4L2OnhkuzK3ddjpIQQ3f5c28C2P+pxuxKk/sKk98MXJ5fP8KPHy54KMo+Yz2Iz4pY+0C87jXRkhyyDPFX0/p/XgKx/dZ4+tajJ2ZYazvlDRPUG49Xy6yUa2kQqHxR6bVFmus6h9XZqGtCv/PuS5P1W/PfcUFOy5LEeNg0bbo0Msply8E9YzgwP,iv:tsZ2hGpvAaiYjREro/96e19QW10BkyHRqW7VaiBtm0k=,tag:sMIH+NbYBb5H+kJy+BPjCw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTFFWQlRsRGFZN3hCU3Ex
            LytCZUMzSGI1WkNCaTFEdzViSTdpelhPeEVrCm1xakhGQTFHWXIvL0x2Q2VVYnhD
            MTdtMWV3RFR0UDkyVysrNEIvbHZqaUEKLS0tICtXYi8rTStlTnVqZmlYcnRLYkZW
            ZWsreTZndnlCTjVXUWZCUjFLS3VrQ2MKEGMvUpG1lMRP7nbcYZf7f4fpKJS/1Iab
            f/Zy1c047Mc+d998yZzgge/eDzFjpPBaxPv3hIc5BNQyj7wvyWBxEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWnFleXBJVVlVVC9vd29p
            SjBwWWY0emZ1SUVLUzVTOElxbjdzd1ViVFJBCmZGRHdSQzVLSHlpV3I3bTNQVWd2
            SGxGMU9XVmpYSm1oSzlCdnl0Z2J1NTAKLS0tIGtqMzgwbzlyeGJsM1RlTjg1T3JR
            c0gxaWZhZzZTSW9WUDZTKzcwd0VHZWMKkKiBZoQ+HYmBZ0jlK04rW4nFvOJ3i4wK
            B4f1PPEZumyhI+8Bs5cDWP2cKjUaIp+FJkgtvCCVZUa58p1XRif5Vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmxPWG9sSkk3Vy9KMEZq
            YUdteDBCUmdOKzFJcUluTW9pbG92YmJJMEhBCmZYSlV5ZURxdlEwWVMwRXBmU2hO
            cWx1eVE1dDdVUEdNeG92TDJwUVBqYTAKLS0tIFNTME9jeW5KNDBoR3dXekRvRHQ2
            azBMQUpRVWdIYXZqcUZvZjBMY3NaZDgKPorw78vM+hjy0BSFACXK8ucu3IBrGYQ4
            vbkTxA6QpyKx9a2DftSZPxcz7T57136uEtzRaATe3DIcbOi6/6ap8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraHc5MERwMVYwbUo2SHlM
            Z09oY0JUTUl6bGN2OWZUNlF3cGVmb1RoRmpJCmtMZllQTG9lU0xmdXJ3TkdHQU93
            eEltY2wyY09lV25yL3F3Zm5mNEY0WFEKLS0tICt3R2lnVkdraVhocDBZS3BhVDR5
            VWNrRzhqc0IxY0ZyQU4vUmJrVWtYUDQKxLC65SGXRvelSar68OHCnEdRxrYZ4sHi
            +7RkWVmjwHMmi9Go7hITJC+OPFOC4BeTBkcXO0Bcj9DD+hc9wZWokA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:43:12Z"
    mac: ENC[AES256_GCM,data:pd4lu6w7AF82V6RuqcqFQlfQVZrz4IfQCNIBOQSsko8/0Gk0Uc0J7JlNXkjhujXtLC3XaP+C3wdlRmum0sngY4W2K1BSP6q8fy1HEQ4z/1W6cj3/kHsyKvhos6G8BMWWzU9oBM/UIpyE5QU0vKM81gSW5PNjRz9Gl0V5rAaQQIQ=,iv:AV+67V73K2/+WunLV3Z0bC3QAA8ZgQF8uO4H4lLZz/U=,tag:Kf3sYcsTIyYE1qBzNlB5Jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
