apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workers.yaml
patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      version: v1
    # patch to append a decryption block (SOPS) to every Flux Kustomization
    patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age
