apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: operator01
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./environments/production/workers/operator01/cluster
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
