apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: worker01
  namespace: flux-system # Note this namespace, as it is init to worker/cluster apps creation it could be inside 'flux-system' ns.
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./environments/production/workers/worker01/cluster
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
