apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:oyg0W/YzMc1o8vmXnL5kWQf5bBk7aYuOvtdsourlvvWHqS6LLp/y7Hy5I6Kxphq5gFx89G+ppSodv8Vv,iv:1pm2nsyIqo0iH6xaeU0EB63DMVUeUTar3od9z+0A+rA=,tag:o4zwA/CvMplT0XTuaYPISg==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:DYgiY6wm8savEoTdpjKX3xAjnVGZnrzYFc08OobDS7LoIXrmRya2EmsADGT4OK4pUdfTvHsn//ELAYdU,iv:2PXSRAw6X4EY5u5AJgGkGuqXZ0JZI5vE6qjmd1mzQbk=,tag:KosobzoUt0bi3zjqrLUEXQ==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:ZLSl4hls1MSFnZx6r5C6cSC2arLq4QaeSKcB/l+rU0qf6g8Xb9bKDDhiQIYdJjLM5vE6F7XAyH9v/Kgo,iv:wXmOLW+5uSAUqgwrTEA2PBmFqQR5M/L7ucT5sV/zxFE=,tag:HK96vVOCDo1H7IRkuforrg==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:OVTBhdZ1CSmBVb7ndoSvKr3kkm9eLzEPfWFeB3qiB0HbOQXIane0BGibXXQ8MI0xE4lDjrP+xyJHKl/h,iv:Z5kwlVzB6EUKzoyBjKePIpmw9ttWgUPzyYRwRbzrrnY=,tag:iD3rh8Ov423n76pQoqQ1OQ==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:8TU9Q8TmunSqSPBLw5R9l0QZt9ZNF3aITBqU3Kv3umto+2FjPc/XW+qNXM+xA9ikFRTdtur8pF5Ev5qP,iv:65AA4uG29PF+Yhui5vXY3V0GdIgasqVCafSFpRW4pdc=,tag:ORtWte5zjdy5OBD3p/ubYQ==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:/FauMDvW+Y+uWGmxmbmNvmaJJ8PRoP2p/+/o/EgflDQ7ENTD,iv:Eq/bA+Fl6n5M42vvgazkD0DtUfulG5ifLYT/HapUG0I=,tag:v5x3mEQ6FnUVwH3G7eVqOA==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaEkxU2RUa0lsdTJDQ2JK
            SHh3UERJc2hQdm9hUTJEOWVtY2dvUWZJRnp3CkM0ZC81VkpmU0hLbXdJaTh0cVBi
            c08yRkRHQW5RNlRUSHhXeHNIMjZDNkEKLS0tIFk4SEovbjJBWkpvS1YzRmJXMkVF
            SUZUQlIwRDZEaWt1MzJLYW9QK3VzTEUKMfVIJMwDpKn8RU2s5M8jXlXvtKryrxFN
            ow+TvB272HpN76bsgkhiVN35WwsROodFgIM/OAjZEgcwZSciQeWlMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1S1lHekV4VmVST3FRU01R
            NUlzTlJxNnVOYjR1ay9aNElVZXFNK1hjNUZRCjFkL2VCajFodDB3RHhEdVNoVkZS
            Y21VUjdhaXBLZzJnYXRDSzNXd2t3SFkKLS0tIG93cmZ6elJDTFJYa0FrUlhyTk9t
            Y3I1aVNPUG8yWTJwSkQrTE5ZKzVDM1UK23CscDt76U1TVG8cpA2Z/TzmZvv7l6cM
            BxRnRi9soCQBCv+1r8AnlSU4v0aJB4syMxhm9VyT8nBpmfUfVIgc4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMS9tb3JjMXVXMVRSSk1K
            OU5rYWFQNVc2UU9JdGtGWkVRcmFxMmVOVkRzCldISE8yT09mM2tNRzU1eEZ6ODZs
            K0dyWThMWklScHJCT2VvbzFFUkV2bFEKLS0tIE55VndoeElLd1FqaDFxd085VSs1
            MnpaclJYblBVWk1IeE1RckgwWUsrdGcKSCx8TiCFXdC+t7t3pBI7hgAf5uzZD/hA
            t24L/GLlUaIA9Rv3k6KuHQfwSwGcUlmWCYDRSaw4jv0kw8mhAjQUWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y1M2Y3RWQUowUU1OTU43
            Um05VW1LNU8vTUhSbzAvMkJVd3hKTnZFUkFjCnhTVHRaUm1xTkJKeXI1R3ZSUnJT
            UmdvZFplY3JraUdWMHpxUmZ3NFZYNVkKLS0tIEhZVjFTU043YWpIOERWVHdIUjBY
            QVRyejhFRXYvVXhNZEx6WG1vR081UjQKDDUG0E4+CN5Nt8I2ifOE9XEbgL0GrUHo
            aUqpTgQvUTo+yb5RoV/7e5IinLCmNbbfoajK0R9NFmWiH9xHvxPidQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T07:49:10Z"
    mac: ENC[AES256_GCM,data:klwFpN4ABSaZRJtm3YIAn/798ZV+W+5QocgwTzIQ4uj65WKiKf1wJUNbsXW7c9tueN4dUb7KEGj6vmuXv78eiSSL9US+srivRLpB/zabgcCD6g2GHFtbu8NtIZ1pQc9N/5FCG/gsAJs1cwPEoju2qSCvwzr/4f8NLJvF5eJ0Ms0=,iv:Y0XXQeKcUjQqEv28xhfnWotRJNjrCZ2xxMHQtueUA7s=,tag:8PgQrms+MJjYyuuG/mz1yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
