apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:sqVKWiARZlPJrvFKNOF8dkfyAxf13wWNylqYRk4m0cvR4n9We49ZgXA7w98XYAUBlv1XeQ0wd8ylz0tW,iv:deRsqHftE8PKuO4jmEhnQWar3Sydh2XAZwMSXLx4hvk=,tag:MKvRkpxWpXAVgD4dQowiaQ==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:CZNuXHW0yhaiISgL/5c4XOY21T9Qn4onjui6DKUD7Q36rpZGTQWFiEW1a1G6tnDWTWhjK+1PHPJVciTa,iv:9s3uhAzsHprMs7J5AbmdItTS4M2Uf7ssMzwO0rh6kL0=,tag:oRHCJLJ9nNcmxdgBairO0w==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:5/kO41O0N41XWUe0sd3iUens5vcw5Cp7LaTetMscw1SUbURC7Bcqkivu0J/A+JMLlXEd/LqbxWxQrxY6,iv:+AGUHgVrRQ2+W4xYZtBg7nuKj2tlr/monmoM7ilSuk0=,tag:KL+LxxVZmB+SLI2L8ea4xQ==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:5dutoIMv6Xp9Ge13pzz7hwtBcsrAqOhmEq8NkI3rUWArora7WdY5Z1VHnBgKOAqUgsRKW/DOkAQVqdnM,iv:fdmMJ8mFxaQnhnu3Ow4wMbyyKCT1CewHx+BNI16rS/4=,tag:hGadtL8pQxqnrnOjZY7i8A==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:1uhL594sPCvb04PHLdQF9arlE5u1mXCqv2eDP37mRailCI+SasXHPlL6Qj1awyKB+V72PfRebHfKS7or,iv:qKk/KYXOuZq1mQFNUhpJv5VCqnKV8sb7mEotwJj2DEE=,tag:PvtUBO7mMkwHB5SfBwXIxw==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:h2Nq4/N1lwzq6JTIuNjDXLzRslY5mN9js+8NOgvlYKb5FXLJ,iv:imACzocE3MAzCq+puqjecjmiBarPZIWBw3FJwJfAwIY=,tag:PqL0Yc9RVaiQWyMAIFvq2w==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OVFkb0haa3NYOXlvemFN
            OVZ0czQzYzNGeUhCNnJEb0cvMjZ0WXkvM0JVCnNjN2ZtRzdzTzRiTDJaL0RkRGNT
            SHowa2hSRE9lMzM2akxqMmM0Tk9qMjQKLS0tIEJjdlpKY2MzTGVWUzI1YmV5b2FZ
            YS95V01IZXJsV2NieUhqdFQwTjRCeDAK4iLaFTSCUAlTG80mqm13jj+6ptyoIkVC
            9DD8g0PP1mIhvcv9BDua6kr62NI/uVS+D2znxWBdR8RcJ+h9e824kA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVHpXSm1pbzRhT1pra21w
            Um42a0pkcDQ3SFgvUTlwVTV5enlSNk96TEMwCkdOREtEMnZMME95ZzVVQWtYck1Q
            R1IzTXRaYlo3S2wyelNOVmxXdUhxUW8KLS0tIEZZVnpwLytkd3hDNGZ6Yk84NmpM
            bFJUbGt1NHovRUg2dGd5eDIyUWlFbDQKsbVRf4OWZdpo43S5RdHBUm1MnN3+Bjl6
            xpnJMjjo4VaXzcjtLwzmFZ6NgUVA+6TVSNMiUbFwjT93K4lTpxc0Aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOXMxS1BkRmR0bXFmR2Y1
            aFhRT0FGSUl6WStZUGM2bUhpRUZMaWdrU3lRCjkwYzRoc2tCWjhXNkFBcGNTSmEw
            UHY5ckVZeG9McUtBbVNPckMwTXJHK2sKLS0tIGZpMDdubkNLVEoxUVlLRFVmQXRB
            VU5SSkFXRnNrOGpLSlhHVHJDWmEvR0EK+bXGwvMHk4iR4mmxSUtXnrAsIGWM0PFn
            hQLvhcN3PqnLjbaXxr0ENQyM0dNTEAfQVphTNDpb4e7hAISHldEqWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNVIxZFkydCtXb1VwcTNy
            ZGdWNjFXRlY4NFBmWjF0amwyWGdTbjZkTnprClF2MDZkbitET0ZjTlo3UWsxTmRs
            WFdzZERndUk4ZlA0emp1MWJobThkMVkKLS0tIDQvVnRIZ0pieWwyWUZmMU1aNnEy
            Z0hIMWl4WnJqOFEvSzVtaXhsYmxlZzAKgUKm24VEdkpOog6xRo0Y2puT+xKh05jq
            0iF1HSMHopRt9+UTyE+vi95UTawYIYCsO20e1IbP8fsn/Wi4eQxc+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T06:06:52Z"
    mac: ENC[AES256_GCM,data:bl6cLK+6VrEqJV5IR2+kKLOBx7Kh11XODJTLSz0Qwyy0Z/uUYgtuLnepFNgA4a281p0jgyy9292nKl5WAxwjZEd4vX7ZWNxNrRsDu02lAzAXGzVteVgTSxJAbTh+39guoXc6ZJvDpXbxfaT6Hq5bOqeBJJIqTBRM6sKaxPVql/o=,iv:vtASTGGrxzHaaZ0S31lJn0TiXJXbVmLiGXLb2MjyArE=,tag:bDcwmhdafo6A3QA9dstMzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
