apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:/YxL+L3zzf6lfe0M1K8DJgzxQnjkaef/CXnzgNgjTDzdym/c6nR5A5kuJvVKGnZu6Y9zKL0/5UJQljNa,iv:t8dUyTM+083sGESih+ueW+dl/ZP0IzrzIwz/lonE7BA=,tag:oUMy5byYaZp9ZyS2RCdtUA==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:hu43qRBhKXH9MgB3iu8lzlput7ibJ6BiXolwOcboYFKECwhpnXL6GmBH7viFOxlPx01OtdD3Hn1oLt+x,iv:c++XwQ4p/6e1y3UVEjiBiD10r+nTPvBnozhGKQHKKjk=,tag:SfkVrXj6SPKiB4WziV+6Hw==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:V+hwu+p7YGF3L+871WMRtqCly69l6dgFg+8wMhWLiqDMq5CbfYaJg9BMJtnVdjU5aBsnIsRePAs4ik0t,iv:Un1iZpN8NfbXSFz1V2V+Ea2VV8qF5CkyAAvL6q4KLxQ=,tag:mrDiS9IRm973P3JOw64sNA==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:DbiJZXdlrf+DwmExaA0U4qHoNGt1GFh83QPnGXqQYMvxF3zqfYKST6WXno608mgsy32pT+9nkMAifybT,iv:GG3ecOhabezDtyl6Y6INxsY3FPgj9TcSUs3V2cX23Fw=,tag:zFTKJs4QuSDdV+v48CcYKg==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:7SSNE7/dURAXsUXJYgRcKDHNDwSge/8goUl7XvARSVpkqHFYclzHKyo71jrrsy/dQinrUh3ORVc3VZiG,iv:Xf8uKoRSYHqgblH5yFLNUFvqISA7VrimxkPnh/82YzI=,tag:dp/0Z7JODK4UXzk6sL4Unw==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:aSz4DzIBHqxLEbvaSaO7jAYEdsOnKG9yz8K85/I3MrPjqaHI,iv:8SaZKs7txLuxOYHosgb1a90ckk5vQBeP4KQO1Vpxfx8=,tag:JarMS4wjaE2h6jnThoVI2Q==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdDRmZm5NT3h1QVdIQjhD
            VS9zZ0lYb0Y2MVR1OE1qWEdMbnkwZnNBdkEwCm51eEo2UGtwK2VkNnZlQURYZEIr
            UHFxNGhvcldhOHBONHduam5BLzVlOE0KLS0tIGNSaUlJNjJsWDcrSGRLK1dvZ3hk
            bjczbVlYRWEvemtJa29DWGJjakdPdjQKgXQfe7nFYQd+zfTr8pFk8byMVSpO8Y9N
            SNsRLOp/zv81dPR+oQewOXEDj0kfhEOjXIzTmuWjWgkBdYoJgNwQpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL09YRlRiRnFJdjNJYldQ
            RTR5YlVQNGt5V1V1SWJnRXJwWjVZRkR1Y3d3CkI5VHVKS1RrUTNobUxpZHdxZ1Jk
            VnhiUVMxRXB0Y3lML01saFpPR3U5cGcKLS0tIE02QzczOURuazk4YXZpbjI1S0Qr
            TndBMm9VSkRNenlaL3lKNkxFeDNGakUKqdXAPehCAtTLNtnOT/tSbaIJ46ytaXBh
            H+HhT2Q1bL66BrYxaH0rg1fN5E0w64q+/xsCT7V9/uyE9tz9Sr6Ldw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUEo3eHBIeEtxMktFdy9O
            bVdQUEV4VTl2eHlHZ2xxc2N4WnNnYU1ycUY4CnczUUdlWldndVVpbDFuMzJCbUVz
            QllZRzVkVXZERFZMcVZuSnhDRnZDYlkKLS0tIFcyZnZ5SEZHcUtwOG5qa1ZCY3F5
            K1U0RnBub2w2MlByQlVhVWVzSy96ek0KnYpzkpW+6JBYzmHquLYDv6vgK51UQyYU
            fHDjHLHo/MeWD4JY0N1Fl5UwmsMhBzElULgtPDnafjNAIiJEXCYlBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUytubUwwblFBVi9NdGFk
            TG5NZmV2WitkbEZleTZONUJmSWVDQ25MWFZvCjM3Vi9LK3JYcjhqZVgyd3hFTjB4
            SGJFT3dSa3AzQW56VUlpM2FmN1FVZlEKLS0tIGdLMktHeU5kNWZXdzZub2hhSkRu
            R3FiREF5ZCtDVllBRUY1bWkwdnZrVVUKvi13+DU5FYTPJDXh7U7wvWiZI6zKR7Jq
            37jDpNHz+JmFAPnADBKedzxCRy/Pk9aV6s8WFaONLoedpgvmIGjksw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T07:30:38Z"
    mac: ENC[AES256_GCM,data:GS0k4IJCzB4CN3WFrhFV8yFMoM21jVAzJXfH9yX78o0WZ9RtFeM9gGTkGWA8O3zgZF5NBmv8euqvhj9q8ukj4cmA/jc9IXUJY46zBuRDXyaJuD1MdMCPRrwlHuC2t7eHQ0kmBddAK3qLyGfNT+uYeVK2jrS1Q1zxlfi0muVmpOw=,iv:lh+DDiNH6Npuni+qP5UKA2JssIYnRCrnI7SCGMjiOz0=,tag:PqhojF2wn/+dnj3lohBLew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
