apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:M8a28xN4DfcO5veXF3f9XCmN8GrT3LZf6DR9uhsUVZjTpFRGf2WKKiwb7HpbQDiD/dvstI/YSJM3o1uf,iv:P0/jRVm7yeRoSCZCJUW4bGWlsp6foEnZzzs0CCpKqeg=,tag:XVT4oJ3VBV3cTrWEifw3xw==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:swi5VDIERT2MuaDyVOjaYqGq8sJhxQc+O6Xx6iRWJT9f8APg7iIM4SuqpT7S9bn6Dmxm3Sm8IRu/Sd/a,iv:5rkkDOub2cdTAy4FOkM66qq4oe5qjMU8c70UeOiqPk0=,tag:hmgF7iOl7eP8v1cUHBQRsA==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:43/iOIwJiplvyojWbIik2dXMAB/R9lYbBHJJfGhOriOcwwYYF2QGAtaL59vcYe5fJER7NY6vErougqSF,iv:073IzV/EXgl8rQeogMcTWCkagsShhyCbT+R3qK3mDZI=,tag:1kdRnUwJbx6Xq0M/EGO6rg==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:I7W5/oPr4QP2NUvIiNL4Q7UMuRqkfONS6NXMSNmhtBk1xxiS3fHt4jmXadBAqpXgTHrtCnQmHWPT3BqS,iv:L+f/wqq9rsAd08EyMMLyFdH3/YWKENKNQQYyvvOngec=,tag:w2Yyz+U/i7MSwLBCOinHPA==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:A9hzxpIcpJTg9IdnG98FRYD/v2DCcnSmq09AUiCktS54XZGs0n+SmXTlO3xbocKcJypJAv4tIJIn2Fkz,iv:KOlsfz3zsdlAYgChQoIiJlp8sa0Xuta45nEcQ0orqcg=,tag:0iLyWV+qFX/PzNJmZBlBmQ==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:gBtcSCKy3Qb1B/82f6QaTQwz855n6yLeT0VJJo4zOEe9BxnZ,iv:YNOHp2HSz1zJNf5jIG1bHgC/4EVMpYyj4Sy30YHBTNY=,tag:/Ea9n5MgjIcfD/Y93rfp1w==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYTd1OW8wQVFwN0s2K1RK
            d2RXbVQycGxvR0l1Uy9nZDVzWnVWUVVYcndFCmFMK1h1dFZLNnZnS1dHYVIwUzR4
            NTVXSzl5RXRuRStDL2xWS3NRZEFHZUkKLS0tIFpGcWpLSnZoTEtKT1RFREhlSU91
            WWQ3dmNxVkhaOW4zMzBsRlE5d0tTdDgKWBUS15PDO/+LDUKClTtLTz3oAtbPXRwH
            fLV5Zkyo9fvsBHThhYW2Sf+WkrRVPYieDwa2L27riKQPdBoOkf/oZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c0VlWXd3ZTBlRWxySGRn
            Rkt3cVVJRHdqR2Y1czRIaHZzc0t1TWhLWUVFCm1pc1Y5RjlDQ3FZTlpjOGhVcVVk
            U3JMNU5UTm9xQ3hwanBJYm55cTRkVkkKLS0tIHpkVVVoRWF6TjFwalBUWWFWaVl4
            cEtQelFYMm5JNHJ0ekZ6YUk5NEVKUk0Kd0duHHrOpRDizr1wTkBVqmGRzfZNmZWb
            i9vGBsbjYA/mML5iEMS7YNrsy9seMU+m2VgdVAKH/BM0qDd4PS8pdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b3RzNFdaK2dkU3VtVXE1
            UHUvSHllaXUvMTgxTGorQld3VkZqV0UvWERvCnhtbFowSmxlck1xclJjQ0hRdnlk
            ZHRacDVnbzdQczRBalUySjNIL2c1dkEKLS0tIGlpaGdBYmVEeDVkRm1BVDdlSHpT
            ajZwdzZaeGtReTZGUVA5alkxeTNDajAK0SD58wBakUYH7qCmOa3FwUllHior5Ky4
            dBRgUFIQRWAJ2qkWzATqTwefuzIZzOMdMPhlVFcrwHsAoNqfjOYb3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aGdUenl3ZUtCb2t3UWo0
            N21sc05ZV2tsMVVNV1NxVGtTZ3BBcVJnWW1ZCnBJZHREdlJCWE9kMG4ydFluekh6
            WmdNNXpVbE5ocXgrTHFmQnoxbWFvZG8KLS0tIFFqZjIzMW9sNGtEc084c05ScDl5
            amJibHNWT1hCQTUzWnlPQVlOTkI0L1EKSDquOhFDAYoJhP0Wn0U5vDItZazQIwek
            w7Q5wGmkHKfU74DiI467ZFVJQ9DNHHfm26rcZtmi76+K2ioxy5FU7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T13:48:06Z"
    mac: ENC[AES256_GCM,data:ZPj+RbyJrFMb1YBB834j+O9+1LwSF/h48tZ8cUxssK8mSyvfvgFO/iApd1FrHRBFJ3d/v5qhywpB+PoxK9prlzHsPbD3zDYjst1tFHOA3oTbSKCRqvHqj50gWWVhxKeHyfl0ckzu7p8y2Ap7rmW/8RC4pOGfP3l+paY7+DhthYU=,iv:8X48BKKtICz2gAJV2EPsoNhOGL7btAjO0Vj8nUetJYw=,tag:2uKdRYBTHneoSo4EtspSmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
