apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:ubO8yVg0a1ybh/+B2slzQE2bB6t0CBpC/mMA8aASNJIjycF2lyZLpYWZkFlgK7l2zEQq3NURAClT9z5V,iv:Qf7Yl6J+9w5aCF8UvP9kiJ1iCmM6Cxwu7V+XONQ3LZI=,tag:0ReRK3TtxEX4y/SUneB/tw==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:7wXCV9bB4NFDUPB9TUSxHEqEGP69oYBiuSVkxzWYVaP5/yCGTYqtjZC2uoEwgI5Db5zm0fBYxjoEyXOT,iv:bLx5o5dC02EqNZWM8/vOsplvhWWec8UROL8KitxuvmQ=,tag:eyQEBYy9sY2HWw2Kf2eO7w==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:UMbkUIVWS1iSZOUjljbKQi2pIagpfoVu45E0J/HgiY/TVd7GX61tbnMyN0p6p4hijoLmCV3S7wTeygua,iv:s3Dd6jGiKsPn9FaErhbprbhnMLD80QJYSDx6CLr0NeE=,tag:AxHz+usgjCw+13rDdRNu3A==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:6GQy2G04gEuDiZEH4cI+tBpyTCwdGPW7xeq3SeOaPZsdMH8UIHrNmN8gu3Nyb8ZQkMXY9oeBmK+n0vBA,iv:tKmobZINgDHEkpAANfnovK+SOKfT/73Fr0RNsRXVfes=,tag:ss79fL3DgCVfKHhkkieHAw==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:Q+UNRhDa4v9WxAGkH1sjMw0dAcE6lMmhe3XSdk8HZKXzE8YkandtB+a4s9x2jIc66FzMokVtIb/l3wUW,iv:aHtVXE/O2xZ6loiColF/KUZIkaFgIWPZ8qFJQclHld4=,tag:hju4SkY3bNNm9AsgL2F+0A==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:4SKV4/5dPD04h0n8yAhZMK9tUwaqfTPBUAErH0g8rE0kmYdm,iv:jbLVmo+qYZnbbZHFvB5YWCxLiiHVjc+lpthlGodimJw=,tag:DMoz2TvL34/MWkYuvnRedg==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVFUyUUt1RWxucVpsZysr
            cEY4R3BMTTI5MmpjVmdETUk4am8rMzFBbjNVCjB2Ni80NEFlcnMvai80S215SUhP
            RlFpVkVqcGloUklmVEo0cThYcEtXcncKLS0tIElNZUJ2NmtOSm92V2RJdVZSTFB4
            WmQ5NWRYS25IZ0llOUlIQ01lUzc4cmsKphoVl5RSwQmdO6UbZPXdmUpRpwFDm2oo
            ShUxl34WvZoY3DV7tZ8P8J3y5ANeo07ZngFw2rkVB7xtuWjMn4YXDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0STN2UUpRM1FINzl5SDV0
            dXByemh4emgxME5BeDNMd281UkhkUzNHSGg0CmY2WmxIYmJ3V2FvUEltYWkzMUZT
            OXh3ZXdSaDF4eEJRV1BYdkpzMEl2bXcKLS0tIEQzVDFUeU5vZHFic2JWSlhGWWUy
            NUVmSkJUQnc5S0wyeEtGbHFWd096b2sK4OaDi15DvDr6rHmpEuUtYm+KhgmMXJAK
            YZpUMg4D5MJIDno1C4K1Dc552kD3MMzpXVF8n9ZGomi4XjcZbKkjaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZzg5RmhoNDRwZzVJTDR4
            MkU0NnM5aHVrdjNvcDdZWk5UdzM4T0NvZkhFCkFrZkpGSzFPVzZzS25ESGtQUXBZ
            ZVdTVy9uN2RFUlg4dDBENXhVNHQvNUkKLS0tIGNBZUJ4Z29XVlFPZGVSdldldmVG
            YUwrRWJhQUFLeDRuSkVqY3ExVS93a3MKVJ5Kj9r3sO3CTsE85db0jhieJBI2rk2G
            TIHYlltDxFLfjuII07vhDf1EljkvOw3vZH2J37QMTOgecG0aAaJtFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a3k3ZXhnbzQxeGdLYXlH
            cW92UkZ6b3Q1N2VwZFBPNVF2ejhBS2JTbmxjCjJ6T1pKeHR6d2swaTJXUjlFc2JB
            WEQ0UXFmdmhjWVloNWp2RDBvRWVYWlkKLS0tIEZrN3VBMFg3blJ3R2Eya0xMMGtq
            WXF4Lzk4VHNzUUZLZW1OYkd6NVBIRzQKEIEy8LcDBntdKc3yGVGYDdsjdHn4/W4f
            Oy3G5ewjjlQ7I4VlBr4ELoAtp9JcmIrbp/9eYrNc5YhBlA7JVmsmrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T07:23:58Z"
    mac: ENC[AES256_GCM,data:aSPqPEv0OuLYL8aekmrgZNAn1L97Oj4SbIg3aRQu5qnIqKseG5NV4tkRMWEPDzz1Ssm8/ujhuZrbQFgE80CwIQQzqIILnWVkspsGuhCklil75jlWLUjyQoZ4y53s7e3sgbDtU3QYqePR5hlQLQVUaiiuKMC3WC8iIWokwE1XYaM=,iv:rLpntsAx6f0GetEdVOq7zF9DFl7vEjjLEXdDHbW3LiU=,tag:7bWzyM9K0SRUyvgZkccAfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
