apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:HSmjNRp7tiF4CeAV7P4H7Dr3QxUw90gZLlv5gnjRLkQcPncIaQTXzI/JSbVM9yKo+e7HrupoMwLMFp9t,iv:ZtTK0wjYuHoyT8AWwgh8hSW9yCFfEsFSySbK3vhHrOI=,tag:ipWrkEWxYlWVYkWuqkl8WA==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:hBEhaTJZIAD6SHoa0xt5Q9seqTq0kkPG41PXgjNwDGtX6mTPYhn7XGoc2q3dCB389MGMwANNwFAaJ1M/,iv:nFX7Q5kfjU8eh+hnsLqjpqyF/tMiMQjl8DQVbbqmGdQ=,tag:Q9d67gnM4XbxTkpoG/IJpg==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:NT1fENEsiTG9dpsNP0hht2AeQjpSOjlCKFCCZYoic5Hxp2ji+GdeSy/ush5GGJtBQ7nyADe1QDr9i9tC,iv:NQ78BJS5wb8UScgRrOreXcxztGwn2JThpEldx4rG9H4=,tag:vTO84fI47Pz87LO9Kc79JQ==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:svDt9W90sy0UjUaMtgp5zkBGPfOYPFofWBeyOAqRwfSKNEhwqUANY/jNzxKH0dXubL/Z/hFYrtSn+j3y,iv:/8548UngXKqRaDF+3uV6dA2o+LIV1mhk+bSAF7zcAvY=,tag:EGVV+PROQUU9G+ZFv1rwyw==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:ZBeG4dwSEKXtcxNgkrtyf5y4teQNZG/vaEXw9OQAaQX+57acN4xBqNCDAToh+RSVpxLJ9T7L6I/WpIkl,iv:KgIqmi4gpfZEHENfxgpneSpqAeoK45QbDOobmhcVscM=,tag:hEI9hN9oOUYZOW2JN0dMZw==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:hz40lZcMe9C9YioV9NWfxQW+F98sr9Wmbb1XiW5+qgksmdmK,iv:fyXsgWeIbuLko30P3Vvr9Kk2XoecZciHnbzpCmSAyew=,tag:5RKNs8T8U2Ox+Vx7/eRgDA==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRlNmV2JCYXhkU2hBeVVR
            RFhLUzBjZ2srRGF4ZW42OXRmc3dub2IxOGtRCkNRMmJkWnQzRUZnTnl5QW83VjM2
            bFBFV0hPbFY3RXJicnNlUUpJUE16bmMKLS0tIFZyTXdJaGVpY0oyZWFXSkdmWDRM
            dDJEOVk4czZBbHVyU0NwOUFEYzZCTXMK4xLUGJW9gWxLhcyQq53r6BBF4NxZIHCs
            sU4c5ObgnRpWmZAEGkwN/MkmfLMj9vAJp30EW4RUc6HFpOo4460JPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvKzBlUUJxU3hoUFpxcHor
            UHlDZ1QyMDBrQytoZFpGRlNiU0s5ejczcXhVCmRCMnpnQVJtV3lxamFSQnJlZHpa
            Z0pqVDRzRDk2Qmd1cWlRbVNjVm9rYWMKLS0tIDd5c213OXdvZlFFL1NuWG9tQTQx
            S085R054L3J3bnUvZ28yWjN2MDhFNmsKryRNJzNat6fIn9EJQoMFv+PWeym9n3OZ
            enWw5lTvWxP+keL+zgol3RnP/MiOrW67DID2Sw0Rz3HmOZy8sRNARQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVHhlQnlkYkZCd2ZMVi9O
            OEN2YWRkNzYxUnRIT0xKMEJOdmJhWFRvZ2l3CjJ2cTIxaEtxRzYwcWF3cWFoTFFv
            TGFSUGdmSTJsSTNLQmVBU1FrcGQ0WkEKLS0tIDM2cFBKOEkycFQyVUtVMW9TdnFr
            ZGNsWnBrZHdCUm5LVDAzSDZtTVZDQk0KCExm5e4H3GVovdvCV7CnOOGh+3yxP/EP
            mtFDUbIOTh0btGgtqyAI7mGPPUkn1o3gVcmKD411klsLoKagWS4oxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eWJTd21LMmw2QXlIdkRG
            a09TQ3ZXS05FVUltOGFNWFdHc2lUZ2FJaWlvCnMxYXhVQnJCN3dqMnlBUFhpLzJ6
            U0RhenVXSzVseThWb0R5RUdOV2VWVGMKLS0tIFM3aGdXZy9GUXpSZW5qV1pObEF6
            WlEzMkI4WmlIMDU3RjFxQ1EwbkUzMjQKwz5tJf1Y5o0aZVMDaRpl5JJfrVirarsC
            JTgM02cT/iTvYak01x4zfqZtSC7aTPdSitSJ5IJEphxFd/zhEWB0jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:29:30Z"
    mac: ENC[AES256_GCM,data:ml97xLShPQviFsFzfzBp4EsMlSCZH93jcs6yrOiRg42AVuHRXKWhVVmjavYJCAh+bpAMYaSmud4jttkoZJW00JYcdRMuZlIqzRdc9510xlrxESVNe20vWmLB87mcrMh7mtVfdyhL7zAFilwxx/xM6ifUo1Dg4yhpchrin5t6wag=,iv:r0T6BmXa+ezQ+kv3Os8bNbjN3shWVfJU6BXw+BKfsBA=,tag:VMQXIcUffHNzEsQGoUb3fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
