apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:dIK+R8YWH6YgZlw1da1zViJjUurjSK5kdoWdwkNz4IYJ9r1XWIBdOJmK9DL+45bWKNPzvU9X74i3MnKt,iv:84u0VjGinoIJawFt7VOt0u3/ikzTLDq/bqjtawPG0nk=,tag:4Lb6yM9O84POsy1jzjdnAQ==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:sg959DgKXebZN0eGvH/HpGMaT39I+by0kO634zoekM3Qd5ZoEUv957oDk6L4HrOAsPagAll4FhDFrGNF,iv:kj3Cr7tICV0jj5+/PAFwA6oUcq53mQ/AOAmtKKbYxw4=,tag:25xxbL9M9osX1LbcyWAUIQ==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:w99AqBOYlfYdLXp42pEvbP9s+BT+sgfEg3m1XwX+j6ndKtqc+3An5v/Qkrkkfm2imMqC4ai66JJdmbr8,iv:y0G4hgH7biIbp6WjOyr6fN4oEIbCdNWyNJFJyWM3HAw=,tag:bMpX+NJbOPb3zWHnENkzoQ==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:kan9gdPHxfWepib9qEXMr2HRf3zw3EAKu9ENzssGouCeTNicX3QQr63T/Gy5HtAjB3raeaJjlyX2q7sb,iv:Y5O9EaqDzoLxF7Mpaz6ryQfmKZZ4EXcyOQ4QBjmWu9M=,tag:8/m9kDRI3zazGo6pxmvGxw==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:pvGtGQC3nPZTSQFGoP2FplRZ2tw/ZKsqoHD23WOaYpjKCqQypycffhReYT6efM/h1fin0bBBuWQUtnc+,iv:qLlq/P5L8kdwAs02VrfaLulF0qHV7dxgdT+gJymPEqQ=,tag:uTWt9cJTorEB2x/PjKsXBg==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:H9ftBbGGKNhsSSJKwiakROwcCE4VfaWLicJJhMAAZ/jLUXvR,iv:t9+22C4d5r5BAujte/OtPRZVI+2hFHn/STQxPbhil3s=,tag:q7YLUZJvhtlxapqFxMPPUA==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicjNMUDFxOEozUTlJT2FC
            WDdiQVFqOGFMYmtyUm0ySnA2OGNETk1vZ3g4CjV5V0lmN2VFb0NaMGRRRjlTN1BQ
            bDA2amxSQk9QOTVoRkN3M2JWU010U0kKLS0tIE9OTlJVdjBlbHJseDdaQ1h2eEtX
            cWpBNXdxR3kyQ2xmMDIxbGlXQ0JSb1UK1bC/CusmBn9u1CCXJseGBcmNv4WpuKZW
            vDeXnuaekgnPl9cpe2MuIcR5XdTARg5KhNvDj40JkFFYRtEg5HE3VQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTXhjOWhIRVFGVHlKR3hh
            RDk1UktidldiUmF1Q1FYaXB3aS9ScTJ2eXlzCkdvNlJCcWZWNlVyYnYrRVZXczQx
            VzQ0STQreFYyQkxwajRzU0R6MjFGY0kKLS0tIElJaE9nVWRYWnpha2hpblhMcjFZ
            ZFo1ODJFV05HUXo1WjJyMFBHTnNVcDgKec6j509ZPUrqYyYW+5SgqDxUOlJXJmpv
            V6t8exFyB9Dfniv6XE2OD7zCxStv+KRt8nwqEPsABNoU5S3ONVxtYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL1RMQ1JURHo0V2RIYUp4
            d3BFZTRUS0NMSngxWHdwcFRyQjNuRkdKakh3CldkNjd6OFhOT2lZZy9TaklEbEdz
            Q0hxcnRUS0FuQlVpNjJ0Qmo3dVkwc3MKLS0tIDF3MFpQZ0FqclpKMHFXVnpxa2JQ
            bFRlNG9Va1dmeXNxOW9rajR4YTZ6UFEK5zU6Aj9jDKXyhbZpibezL/9+KwTb86gR
            S05PFBrHedyV8nSOuN9r1yYnWtyHdzLfBX9kNvKtodo3tmPOkVFA1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHd6alYyOVFOY1BRTE5j
            NXgyeWJiY1ovTStyaVBuSWFOc0V4S3FMTFhvCmNuUERoSXRsTUJaM29LcThUL2tw
            VjU4Z2llUUZlODNtenRPSlExZVBKd2cKLS0tIENRUy9NcFVtODdVN0xNZjd4cTEw
            K25wR2tCS0p2MmtEKzh6S2dJRTBoWFUKP4BwZE3L+7FQ4XW61xAXXDYMjp9/mMOn
            8kXD55nOaO75qZcOrSsc7jaLTeVER39gzGSIeiAIHc1lG6gf0fa3Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T12:26:30Z"
    mac: ENC[AES256_GCM,data:6dC/ADxVp2GkhJU/KQtSnmSzKfzbeeyLsxk2UT+9knmQx7MJtWBkaI+2wjn+KWBUX8n/9mMp1u1yLxezPt9MCQJhBiLX7wNZRWbvWToE2djHPcQVK4pJtrifT4TA1WsoYi88oZUdykPci1RBDudWvMeDDaOeuqmzUDcjRNZD0xs=,iv:LvtUVGpK/+b71BtDX5SCFT/4KhWJzxjrMowC9GP0ZHY=,tag:3zgPGlDwGFSiGzWZ0v4zqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
