apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:0Reb3LKeXTgYcbHevKpb/axOQeidbfT6jiwGYKlRRt+JTQBRQVd2PZh69vaT594DqEwzRDVxLkNaOfrF,iv:h0p/SD7BPFcOh+wSxWAqjrBaDYeF/m1UsKvIWJZ2pmM=,tag:2llWUSFR8DD3DohqzTcgYQ==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:0D4NZbJzEw8nL6Q1ZGk746RDwtjxR39wq5au01tGn6BVtTafIr+VsE23s1Q6HWFZFHGDqJqcbyINlysO,iv:0/R4CeAMcEKWhybL3Dz/iL4n1kFNSonFanO3Js5b4UM=,tag:NSuOg3F5Jdg220YgnrzlkA==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:re5q9Y85hV0fZu/944MtgMZoUdAYbCHttwwo8sd/Fvpz8ZCDDOKYbDYUGWTU84lctiN3jHhYujdF9PgV,iv:WKvUHm17PbQMz9Sv9nFMnhONnDfd2RBNogP43qPj1DI=,tag:EnIkAbG3t1IuBrjhKlmpEw==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:Lddguu9GODvN5cksYZUewQjKGMinZiycGEYDphI/ItH6aeo6Liohl/1gcrgjTXz8IjYOXvgFxVK+LMdZ,iv:9xYx8Yaj1ZdAZ1rSAElQss7Qa1Z2/90Un1/xxO8Llds=,tag:S1a+WiHTNSpFH8aNv9t5/w==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:3Q8BDXk3lTo0TrcR/BbUBKckMIQed4VOcNqVKYY4/6XJypnQqOmHjPd9QcIKAg1OFEOhaTW0/mguQoPS,iv:BRmv4UcGqlnk0NpgYYjLjp/mpqFwQxR7rsS5kuqTxJA=,tag:Nb7pidEDrd4OWA5KRfOd8Q==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:9wmFIYbupX8ttu6v2SMfDFUUwclqM93FSw14VQAPlUDPThjx,iv:mzzq3bgI182NjkLlwQi5JSM4nmiVAzAWM3+3WiNCF5g=,tag:rGcA+/7Lpy/nFW0vR8s92Q==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWjdzTXZ2MFEyTXp1OTk5
            R1FPSStsYXRjZFcwZ3dqTTJxMjhhQTFtTW13CmVteDMySHNNM2tvM0J6WldlVHpU
            RkdBRjQ4Z1dLVk1WWHRVTGxEOHdsREEKLS0tIGFXbWxUSlppM3FwOEc5ZFNySjl4
            VVRlcWlHdTlvaHJTMFNHbjdodngwUXcKBYU2hED7nfj1rcpfm553Dbw/PwiZ7myx
            DSeJ7a6n8e/mV6yIvNSCgCDbJLJ5pKg2+N5BZaEyGLf9GfqT8tjGIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Ty8vZ2VnaVc4b2dUdVAz
            SFQzRVo5ZXZXOHZ6V0lKSFB6WFJyKzB2dDBrCm1ZTU1hemYyL0Fka2xocENJOVV2
            blBpdjJ5dGdBU1U5V1ZlRC82L1dkbUkKLS0tIE9jTDRFM0xOTnd2NmkxRmRZZTlw
            anFrdjE5L0Q0RHFORjdCc2ZrOURjNFkK5QqUoEifjS/q8ju5k5S1XH+UtwcWXMpO
            E56NziP3lRVXlP6KkVvEyXh23y7hvO7x2NlplkI16CfROoLZ/O8qIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyV1IwR3FVU2wwM3YzZitN
            Z2FQSzZvU0FNRnQ3WEQ3a3ZDVndOY2FHTmlNCmsxajdMeURVNTVoeGhVOTJkUFFB
            L0JzK0J6bGtFVmxGT2hZY0xXamhMc3cKLS0tIDljaEZIc0Q1MVE0WkJOTjRTb3ox
            TlJqY2VQVHVxcDR0N0JqZmVMZ3p5bGsKLVEoH9ckaHnmveQSLRY3mSJ+L0NH7z/O
            mw6swLiZznJh+w9f+iCTu7Pj8kd/sSwUNuvEn2r8/Vvae71BaS9Kcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGhTcU01NG5GQnpJYTBW
            NXR4Ry9Ba24vRTNxQ3h6bVVOT2Q3RWh3djBvClJkWW5GOWVzbkNzVnk0VkRDNER2
            Q3pWaElRQ2Uxd3ptOXFHZ1loM0l6TGsKLS0tIGJNVllRZE1sb080VTFNc1FBUDEy
            S3hVME5BbitXZE9FZy9mY0Fyc1I5WEEKwCgUxi6n3lVe87rfBCvqAc/7UrMJl1V3
            65WyI6LQvcMg/tiV9CBgduGAmIOKeey4/iNsm00wW/VWDIw36wQ+5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T08:18:09Z"
    mac: ENC[AES256_GCM,data:/ztM4Z0YcLob2LSzFgF6s85agDxY4R7OS8oHyNb8eMEasIx765OyE6yNc/YZYxn4XphiNUZl3mfW4rHIp1AvTHi0CkDTxfK40M8hoOtTMjwLPd+lHWKbsMYzolWjq1ITK7ZUJgFK76oaBjrPyyH3R55CMwBmCNkFHCEm+BTOHMk=,iv:AR7tb8DwA5djnf3lqaEy/TNTWRcj8QYAtYHls0X9afY=,tag:a14r9//5awvdOuJq0nn/xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
