apiVersion: v1
data:
    UnsealKey1: ENC[AES256_GCM,data:veUsVm5ST4rc3CuooqGDftrOO4+BiihAlZewsBagcvP5qEduIfSiHUQWd1TCdrkXjWYnlgjKl+mMr0in,iv:JubXBNzsvJOPn2JHDyG0gd+Zdlt8kwhC90mIEch8oJY=,tag:2TId/9P42nVSQlqNW6CTng==,type:str]
    UnsealKey2: ENC[AES256_GCM,data:rAHTulg6gNwp8GD1jqvvHtV5beMKlos1bL4y1ZCNMFgRQPKETBQKXFhPvuq0zkMCqyxE/utGRP40R3Y3,iv:mU9Er17EB+8jwQL5TywNYaZD5p2kaoKlvCN8SIpS/DM=,tag:OPRQBAPrK+c45QMpijJwSQ==,type:str]
    UnsealKey3: ENC[AES256_GCM,data:lrtWYg4WlwmXWqdxClHt7wQBO8Yw9foYv3s4KsngC0RbFCg7eaC2UR9VhL82WgVuo+AZl1WR0Qbeiuhh,iv:rzpN9pRZNM/6gv1JAue9tWK6wUZyKTbGWnQSkyOwQqw=,tag:p3LmnmdaysfDFCNPzFWa/g==,type:str]
    UnsealKey4: ENC[AES256_GCM,data:wbDAzW+OMfgiU3TInaoo/p5kRiXygshlURcg+Kv0DwFF6JZDJ6DfVmoWTiYdygvVM/hV8hMPaOvLsNlL,iv:yfzawBCU4HLHhNS04OoBhdyNNKZEBXO0x4SqIJ8g4Hw=,tag:7mG3GiArcsg5SY3chQEXbQ==,type:str]
    UnsealKey5: ENC[AES256_GCM,data:0H4PduldU8J5tfQ6BIVBjerhI6QTxg6qOZdvogWJPq30ZcubYwOlAOSQ6MeIAJLh+PGgZB/lFqqDzFiE,iv:kzTkfUxrkMjTF70tzTMmQya0I7lkMv+7HoxKZv6IliA=,tag:80+/GVlz8aZ8M4alnH9RUg==,type:str]
    InitialRootToken: ENC[AES256_GCM,data:iQs/Q8NHUt0HKGgjU29Pn48UAOSEIibM3h46f8q+AiPSATdZ,iv:HhgUY/m6fMv9uh1PRf0Yn6HLCaM8pfjwBfcADsrdLRA=,tag:Xi8LED1D8VTWIQGR+7GfUw==,type:str]
kind: Secret
metadata:
    name: openbao-secrets
    namespace: openbao
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOGZCV0MvUUtodDhEb0d4
            Q291NHBVWTBlRVVQOGQ2aWk4anhkeitaSUY4CkM1aEtZc3Y1cG1BUjhuMmNJclhp
            RTJ0TlB3OEhmUGVtSlF4T0RqRDA3K1kKLS0tIDFmM2dWZEpwcHcyQ3ZOUTU3UXlZ
            d1lpK2ZQUGVkaHFlMkFneXl6VDlBYVEKazslGzCu8HZ4/2d5Y6NKNOhmGwGPGOdX
            vs/1z3Vi2j1FSvS9AHyotwGwDo7BZ7hJiYz2bG2rCI4sbnpH2TJ6RQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlY0M4aTZpdm8xQ0RadjU5
            S1V2U1l2ZlRzL2lrekdmcEVHZjUwaFVEV0RJCmJDZDJnVElCQTdieGFLUi83T3Ev
            RFUyeExaN3phYWl5dWQ5c3Mrd3JORE0KLS0tIE9WRjJxQzZJZUw3MU10MjFYTFQ0
            eWgxNW41WktvYlByTVdXWHlOalNGQlEKgHLHJn5rDgMOKfCXy5yVgf6pctFkYHPH
            bNOQ48cvCm9o0DDHntZ9XGiH7atQbqRFI0y4IK9tbyi+GJJEGt2hHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TTk1a0IxYSt4c2p2ak1s
            TVQxVWxBWnhSTi9nTmoxQmh0ZGdPd3JML2tJCnRLU2ZaRFd2WHJ4cy9WVmx6L3lX
            YmpFU01JMXdrdHJ4eWVYeGdZa2dJZVkKLS0tIGpYNUJXY2JGWHNxU0wyQyt6YTZs
            MU0wODhnR3VXaXFnY2pESHYrcTFsZ1UKI1CaEtxbt4TrDCADF5xp/xLqWzpZMYhX
            p3mlb44H9q+GGboYmvofP6vgazORcoYYj6VtvZ41Eah2RPTuLSuOXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdHdIcVRhSisxdE9ta0JX
            UFVHS29jcGZuT216V2RGWHlmWTZ4cFk1V0hBClVUWkY0R3ZaeGNwM3NpSWE3Q2ZG
            M2NDS05Xcy93b1g5U2FpbWFFc3pUQnMKLS0tIFJ4Qll1T2VjWUR0Wk12R2lNNkZh
            eXRkSUF3US9MY1c3R2FESUJwYWFOZlkK22gfekXPZ3BAt//MZAKWlFw+gOFCIAcz
            as5uOu22uhB64doAeJ7DH7H3vcZNc+fkTZdTdJ4FJy9ptdO8m87sMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T12:08:36Z"
    mac: ENC[AES256_GCM,data:TWlCtNWUdUZ/vy9kwXOq2ftaJiUMQBwNDERPwIQEDB8DivkAy+B37HKKPEDa3NHZ867oF/VNB/jIDfa9iCZUU9n29UGn5G44m4kvCL2DdwmvAbOXM/TpRQE3hBrlukHZ7mb9u8/TwJXHeLw1lkdewe3ukW6R3Iam9efZIX9VPMQ=,iv:a4FpKuhMQE8IDYAFQIl3JWZPTs00VCFxyu/8o+xSuZE=,tag:vcHkqZy/GYUbJWAHGTfhjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
