apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry-daemonset
spec:
  chart:
    spec:
      version: 0.120.2
  targetNamespace: monitoring
  storageNamespace: monitoring
  dependsOn:
    - name: monitoring--pre-release
  values:
    extraVolumes:
      - name: otlp-log-certificates
        secret:
          secretName: cloud-logging-secret-gc-cmk-p-glob
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
    extraVolumeMounts:
      - name: otlp-log-certificates
        mountPath: "/etc/otlp-log/certificates"
        readOnly: true
    extraEnvs:
      - name: OTLP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: cloud-logging-secret-gc-cmk-p-glob
            key: otlp-endpoint
      - name: ENVIRONMENT
        value: "mesh-canary"
      - name: K8S_CLUSTER_NAME
        value: "gc-cmk-p-glob"
    image:
      repository: otel/opentelemetry-collector-k8s
      tag: 0.121.0
