apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kms-system
spec:
  storageNamespace: kms-system
  targetNamespace: kms-system
  dependsOn:
    - name: kms-system--pre-release
  values:
    resources:
      cluster-secret-store-vault-backend-common:
        apiVersion: external-secrets.io/v1
        kind: ClusterSecretStore
        metadata:
          name: vault-backend-common
          namespace: kms-system
        spec:
          provider:
            vault:
              server: "https://vault.tools.sap"
              path: "kv/"
              namespace: "btp_se/kms/2.0/common"
              # Version is the Vault KV secret engine version.
              # This can be either "v1" or "v2", defaults to "v2"
              version: "v2"
              auth:
                jwt:
                  # Path where the JWT authentication backend is mounted
                  path: "jwt/canary/infra-canary"
                  role: "secret-accessor"
                  kubernetesServiceAccountToken:
                    serviceAccountRef:
                      name: "eso-vault-sa" # ServiceAccount to use for authentication
                      namespace: "kms-system"
                    audiences:
                      - "vault" # Must match the bound_audiences in Vault role
                    expirationSeconds: 600 # Token expiration time in seconds
      cluster-secret-store-vault-backend-cluster:
        apiVersion: external-secrets.io/v1
        kind: ClusterSecretStore
        metadata:
          name: vault-backend-cluster
          namespace: kms-system
        spec:
          provider:
            vault:
              server: "https://vault.tools.sap"
              path: "kv/"
              namespace: "btp_se/kms/2.0/canary"
              # Version is the Vault KV secret engine version.
              # This can be either "v1" or "v2", defaults to "v2"
              version: "v2"
              auth:
                jwt:
                  # Path where the JWT authentication backend is mounted
                  path: "jwt/infra-canary"
                  role: "secret-accessor"
                  # Reference to a key in a K8 SA
                  kubernetesServiceAccountToken:
                    serviceAccountRef:
                      name: "eso-vault-sa"   # ServiceAccount to use for authentication
                      namespace: "kms-system"
                    audiences:
                    - "vault"                # Must match the bound_audiences in Vault role
                    expirationSeconds: 600
