kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: aweu-cmk-p-02
  namespace: garden-kms2c
spec:
  dns:
    domain: aweu-cmk-p-02.cmkc.kms.cloud.sap
    providers:
      - primary: true
        type: aws-route53
        secretName: production-aws-route53-secret
  extensions:
  - type: shoot-cert-service
    providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true # if true, allows to specify issuers in the shoot cluster
  - type: shoot-dns-service
    providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      kind: DNSConfig
      syncProvidersFromShootSpecDNS: false
      dnsProviderReplication:
        enabled: true
      providers:
        - type: aws-route53
          secretName: shoot-dns-service-production-aws-route53-secret
          zones:
            include:
              - Z04590372NVK1GNUX0CQL
  - type: shoot-networking-filter
    providerConfig:
      egressFilter:
        blackholingEnabled: true
  - type: shoot-oidc-service
  resources:
  - name: shoot-dns-service-production-aws-route53-secret
    resourceRef:
      apiVersion: v1
      kind: Secret
      name: production-aws-route53-secret
  provider:
    type: aws
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-central-1a
            workers: 10.180.0.0/19
            public: 10.180.32.0/20
            internal: 10.180.48.0/20
          - name: eu-central-1b
            workers: 10.180.64.0/19
            public: 10.180.96.0/20
            internal: 10.180.112.0/20
          - name: eu-central-1c
            workers: 10.180.128.0/19
            public: 10.180.160.0/20
            internal: 10.180.176.0/20
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
      - name: worker-c6box
        minimum: 1
        maximum: 3
        maxSurge: 1
        machine:
          type: c3.2xlarge
          image:
            name: gardenlinux
            version: 1592.6.0
          architecture: amd64
        zones:
          - eu-central-1a
          - eu-central-1b
          - eu-central-1c
        cri:
          name: containerd
        volume:
          type: gp3
          size: 50Gi
  networking:
    nodes: 10.180.0.0/16
    type: calico
  kubernetes:
    version: 1.31.7
    kubeAPIServer:
      structuredAuthentication:
        configMapName: infra-issuer-configmap
      serviceAccountConfig:
        issuer: https://oidc.aweu-cmk-p-02.cmkc.kms.cloud.sap
  cloudProfileName: aws
  credentialsBindingName: production-secret
  purpose: production
  region: eu-central-1
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 020000+0100
      end: 030000+0100
  monitoring:
    alerting:
      emailReceivers:
        - DL_66E00BD1DBECE8662B8E0B02@global.corp.sap
