apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: btp-pki-addon
spec:
  storageNamespace: security
  targetNamespace: security
  dependsOn:
    - name: btp-pki-addon-secrets
  chart:
    spec:
      version: '0.3.2'
  values:
    image:
      digest: sha256:258d15660ad29576b333a7a0c50f54b8489b980016af8adb3391baa9712bb357
