---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: registry
spec:
  targetNamespace: services
  storageNamespace: services
  chartRef:
    kind: OCIRepository
    name: registry
  interval: 10m
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    fullnameOverride: "registry"
    imagePullSecrets: []
    image:
      registry: ghcr.io/openkcm
      repository: images/registry
      digest: sha256:f0950e5f45ab48512d2b2bb93c71e4d033bd5eb4c515751d7cf61eaa2589957e
    service:
      port: 9092
    config:
      application:
        environment: development
      orbital:
        targets:
          - region: cf-eu10
            connection:
              type: amqp
              amqp:
                url: "amqps://kms-rabbitmqcluster.services.svc.cluster.local:5671"
                target: "/exchanges/cmk/cf-eu10.tenants"
                source: "/queues/cmk.test.tenants"
              auth:
                type: mtls
                mtls:
                  certFile: /etc/credentials/rabbitmq/tls.crt
                  keyFile: /etc/credentials/rabbitmq/tls.key
                  caFile: /etc/credentials/rabbitmq/ca.crt
      logger:
        level: debug
      database:
        host: kms-postgresql.services.svc.cluster.local
        port: 5432
        name: registry
        user:
          source: file
          file:
            path: /etc/registry/credentials/database/username
            format: binary
        password:
          source: file
          file:
            path: /etc/registry/credentials/database/password
            format: binary
      telemetry:
        traces:
          enabled: false
        metrics:
          enabled: false
        logs:
          enabled: false
    extraVolumes:
      - name: db-credentials
        secret:
          secretName: kms-user.kms-postgresql.credentials.postgresql.acid.zalan.do
          items:
            - key: username
              path: username
            - key: password
              path: password
      - name: rabbitmq-cmk-secret
        secret:
          secretName: rabbitmq-cmk-secret
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            - key: ca.crt
              path: ca.crt
      - name: rabbitmq-ca-secret
        secret:
          secretName: rabbitmq-ca-secret
          items:
            - key: ca.crt
              path: ca.crt
    extraVolumeMounts:
    - name: db-credentials
      mountPath: /etc/registry/credentials/database
      readOnly: true
    - name: rabbitmq-cmk-secret
      mountPath: /etc/credentials/rabbitmq
      readOnly: true
    - name: rabbitmq-ca-secret
      mountPath: /etc/credentials/rabbitmq-ca
      readOnly: true
