---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: storage
spec:
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: alekc-charts
      version: 2.6.0
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  interval: 1m0s
  targetNamespace: storage
  values:
    cluster:
      create: true
      name: "kms-rabbitmq-cluster"
      ingress:
        enabled: false
      spec:
        replicas: 3
