---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  chart:
    spec:
      chart: postgres-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
      version: 1.14.0
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  interval: 1m0s
  targetNamespace: storage
