apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
spec:
  interval: 5m
  releaseName: linkerd-crds
  chart:
    spec:
      chart: linkerd-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd
      version: 2025.4.2
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    enableHttpRoutes: false
    enableTlsRoutes: false
    enableTcpRoutes: false
