apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cmk-krypton-bridge-db-sync
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: krypton-local-secret-sync
  refreshInterval: 1h
  target:
    name: cmk-krypton-bridge-db
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        DATABASE_DSN: "postgres://{{ .username }}:{{ .password }}@kms-postgresql.services.svc.cluster.local:5432/cmk_krypton_bridge?sslmode=require"
  data:
    - secretKey: username
      remoteRef:
        key: kms-user.kms-postgresql.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: password
      remoteRef:
        key: kms-user.kms-postgresql.credentials.postgresql.acid.zalan.do
        property: password