apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-identity-issuer-syncer
spec:
  interval: 10m
  releaseName: linkerd-identity-issuer-syncer
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  targetNamespace: flux-system
  storageNamespace: flux-system
  values:
    resources:
      linkerd-identity-issuer-syncer-worker01:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: worker01-linkerd-ca
          namespace: worker01
        spec:
          data:
            - remoteRef:
                key: certificates/pushsecrets/linkerd
                property: worker01-linkerd-ca
              secretKey: ca.crt
          refreshInterval: 5m
          secretStoreRef:
            kind: ClusterSecretStore
            name: vault-backend-cluster
          target:
            creationPolicy: Owner
            deletionPolicy: Retain
            name: linkerd-identity-issuer
      linkerd-identity-issuer-syncer-gceu-cmk-p-01:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: gceu-cmk-p-01-linkerd-ca
          namespace: gceu-cmk-p-01
        spec:
          data:
            - remoteRef:
                key: certificates/pushsecrets/linkerd
                property: gceu-cmk-p-01-linkerd-ca
              secretKey: ca.crt
          refreshInterval: 5m
          secretStoreRef:
            kind: ClusterSecretStore
            name: vault-backend-cluster
          target:
            creationPolicy: Owner
            deletionPolicy: Retain
            name: linkerd-identity-issuer
      linkerd-identity-issuer-syncer-aweu-cmk-p-02:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: aweu-cmk-p-02-linkerd-ca
          namespace: aweu-cmk-p-02
        spec:
          data:
            - remoteRef:
                key: certificates/pushsecrets/linkerd
                property: aweu-cmk-p-02-linkerd-ca
              secretKey: ca.crt
          refreshInterval: 5m
          secretStoreRef:
            kind: ClusterSecretStore
            name: vault-backend-cluster
          target:
            creationPolicy: Owner
            deletionPolicy: Retain
            name: linkerd-identity-issuer
      linkerd-identity-issuer-syncer-awus-cmk-p-03:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: awus-cmk-p-03-linkerd-ca
          namespace: awus-cmk-p-03
        spec:
          data:
            - remoteRef:
                key: certificates/pushsecrets/linkerd
                property: awus-cmk-p-03-linkerd-ca
              secretKey: ca.crt
          refreshInterval: 5m
          secretStoreRef:
            kind: ClusterSecretStore
            name: vault-backend-cluster
          target:
            creationPolicy: Owner
            deletionPolicy: Retain
            name: linkerd-identity-issuer
