apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq--post-release
spec:
  interval: 1m
  releaseName: rabbitmq--post-release
  storageNamespace: storage
  targetNamespace: storage
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  dependsOn:
    - name: rabbitmq
  values:
    resources:
      kms-rabbitmqcluster:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        metadata:
          name: kms-rabbitmqcluster
