apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq--post-release
spec:
  interval: 1m
  releaseName: rabbitmq--post-release
  storageNamespace: services
  targetNamespace: services
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  dependsOn:
    - name: rabbitmq
    - name: rabbitmq--pre-release
  values:
    resources:
      rabbitmq-definitions:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: rabbitmq-definitions
        data:
          definitions.json: |
            {
                "users": [
                  {
                    "name": "cmk",
                    "password": "not-used-with-external",
                    "tags": ""
                  }
                ],
                "vhosts": [
                  {
                    "name": "/"
                  }
                ],
                "permissions": [
                  {
                    "user": "cmk",
                    "vhost": "/",
                    "configure": ".*",
                    "write": ".*",
                    "read": ".*"
                  }
                ]
              }
      kms-rabbitmqcluster:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        metadata:
          name: kms-rabbitmqcluster
          namespace: services
        spec:
          replicas: 1
          tls:
            secretName: rabbitmq-tls-secret
            caSecretName: rabbitmq-ca-secret
          rabbitmq:
            additionalPlugins:
              - rabbitmq_auth_mechanism_ssl
            additionalConfig: |
              auth_mechanisms.1 = EXTERNAL
              ssl_options.fail_if_no_peer_cert = true
              ssl_options.verify = verify_peer
              ssl_cert_login_from = common_name
              load_definitions = /etc/rabbitmq/definitions.json
          override:
            statefulSet:
              spec:
                template:
                  spec:
                    volumes:
                      - name: rabbitmq-definitions
                        configMap:
                          name: rabbitmq-definitions
                    containers:
                      - name: rabbitmq
                        volumeMounts:
                          - name: rabbitmq-definitions
                            mountPath: /etc/rabbitmq/definitions.json
                            subPath: definitions.json
