apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      version: v1.17.1
  targetNamespace: cert-manager
  storageNamespace: cert-manager
