apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../base/linkerd/linkerd-trust-identity-management/identity-management/
patches:
  - path: release-values.yaml
