apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: session-manager
spec:
  interval: 10m
  releaseName: session-manager
  chartRef:
    kind: OCIRepository
    name: session-manager
  storageNamespace: services
  targetNamespace: services
  values:
    extraEnvs:
      - name: DEBUGFEATURES
        value: smdumptransport=1
    pod:
      disruptionBudget:
        enabled: true
        minAvailable: 1
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: session-manager
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: session-manager
    image:
      registry: ghcr.io/openkcm
      repository: session-manager/images/session-manager
      pullPolicy: IfNotPresent
      digest: sha256:20c879eac5eadc0fabc83e163905e3f9e517e0d4ac0620471bd3ebe5f12c6f4b
    imagePullSecrets: []
    config:
      telemetry:
        metrics:
          enabled: false
        traces:
          enabled: false
