apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spis--pre-release
spec:
  interval: 1m
  releaseName: spis--pre-release
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    resources:
      reference-grant-spis:
        apiVersion: gateway.networking.k8s.io/v1beta1
        kind: ReferenceGrant
        metadata:
          name: spis-routeref
        spec:
          from:
            - group: gateway.networking.k8s.io
              kind: HTTPRoute
              namespace: envoy-gateway-system
          to:
            - group: ""
              kind: Service
              name: spis

