apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../base/storage/valkey/pre-release
patches:
  - target:
      kind: HelmRelease
      name: valkey--pre-release
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |
      - op: add
        path: /spec/targetNamespace
        value: storage
      - op: replace
        path: /spec/storageNamespace
        value: storage

