apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: database
spec:
  interval: 1m
  releaseName: database
  storageNamespace: services
  targetNamespace: services
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    resources:
      databasesecret:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: db-secret
        spec:
          refreshInterval: 1h
          secretStoreRef:
            name: vault-backend-cluster
            kind: ClusterSecretStore
          target:
            name: db-secret
            creationPolicy: Owner
            template:
              type: Opaque
              data:
                endpoint: "{{ .endpoint | toString }}"
                master_password: "{{ .master_password | toString }}"
                master_username: "{{ .master_username | toString }}"
                port: "{{ .port | toString }}"
                reader_endpoint: "{{ .reader_endpoint | toString }}"
          data:
          - remoteRef:
              key: databasepush/c-eu-cmk-p-02
              property: endpoint
            secretKey: endpoint
          - remoteRef:
              key: databasepush/c-eu-cmk-p-02
              property: master_password
            secretKey: master_password
          - remoteRef:
              key: databasepush/c-eu-cmk-p-02
              property: master_username
            secretKey: master_username
          - remoteRef:
              key: databasepush/c-eu-cmk-p-02
              property: port
            secretKey: port
          - remoteRef:
              key: databasepush/c-eu-cmk-p-02
              property: reader_endpoint
            secretKey: reader_endpoint
