apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kms-system--post-release
spec:
  storageNamespace: kms-system
  targetNamespace: kms-system
  dependsOn:
    - name: kms-system--pre-release
    - name: kms-system
