---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crypto-edge-operator
spec:
  targetNamespace: crypto-edge-operator
  storageNamespace: crypto-edge-operator
  chartRef:
    kind: OCIRepository
    name: crypto-edge-operator
  interval: 10m
  timeout: 10m
  install:
    createNamespace: true
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    fullnameOverride: "crypto-edge-operator"
    imagePullSecrets: []
    image:
      registry: ghcr.io/openkcm
      repository: images/crypto-edge-operator
      digest: sha256:aa2e7a7e39bafb9f519be87e64d704330c2bd9e7d91cbefd1921c0d2bf208a40
