apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: btp-pki-addon-secrets
spec:
  targetNamespace: security
  storageNamespace: security
  values:
    resources:
      pki-secret:
        apiVersion: external-secrets.io/v1
        kind: ClusterExternalSecret
        metadata:
          name: pki-secret-eu11
        spec:
          externalSecretName: pki-secret-eu11
          externalSecretSpec:
            data:
              - secretKey: ".metadata"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: .metadata
              - secretKey: "certificateservice"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: certificateservice
              - secretKey: "instance_guid"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: instance_guid
              - secretKey: "instance_name"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: instance_name
              - secretKey: "label"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: label
              - secretKey: "plan"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: plan
              - secretKey: "type"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: type
              - secretKey: "uaa"
                remoteRef:
                  key: security/pki/eu11-binding-secret
                  property: uaa

