apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao--pre-release
spec:
  interval: 10m
  releaseName: openbao--pre-release
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    resources:
      externalsecret-postgres-storage:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: openbao-postgres-storage
        spec:
          refreshInterval: 5m
          secretStoreRef:
            name: kubernetes-local-all
            kind: ClusterSecretStore
          target:
            name: openbao-postgres-storage
            creationPolicy: Owner
            template:
              type: Opaque                # use kubernetes.io/tls only if you’re creating a TLS secret (crt/key)
              engineVersion: v2
              data:
                config.hcl: |-
                  storage "postgresql" {
                    connection_url = "postgres://openbao:{{ .openbao }}@openbao-postgresql-rw.openbao.svc.cluster.local:5432/openbao?sslmode=require"
                  }
          data:
            - secretKey: openbao
              remoteRef:
                key: openbao.openbao-postgresql.credentials.postgresql.acid.zalan.do
                property: password
