apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: als
spec:
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-collector
      version: '0.130.1'
      sourceRef:
        kind: HelmRepository
        name: kms20
      interval: 10m
  targetNamespace: services
  values:
    fullnameOverride: als
    mode: statefulset
    image:
      repository: kms.common.repositories.cloud.sap/als
      tag: v0.1.0-20250808112228-60ecc6805e1466c5a2e2fd77d4f07ff40ce07a7a
      pullPolicy: Always
    imagePullSecrets:
      - name: registry-access
    command:
      name: collector
    configMap:
      create: false
      existingName: 'als-config'
    extraVolumes:
      - name: otlp-mtls-certs
        secret:
          secretName: clustercert-certificate-secret
          items:
            - key: tls.crt
              path: certificate-chain.pem
            - key: tls.key
              path: private-key.pem
      - name: otlp-storage
        emptyDir: { }
    extraVolumeMounts:
      - name: otlp-mtls-certs
        mountPath: "/certs/certificate-chain.pem"
        subPath: certificate-chain.pem
        readOnly: true
      - name: otlp-mtls-certs
        mountPath: "/certs/private-key.pem"
        subPath: private-key.pem
        readOnly: true
      - name: otlp-storage
        mountPath: /var/lib/otlp-collector
