apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - target:
      kind: Deployment
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: federated-token
          mountPath: /var/run/secrets/tokens
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: federated-token
          projected:
            sources:
              - serviceAccountToken:
                  path: federated-token
                  audience: downstream-cluster
  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure-kubeconfig-exec
  - target:
      kind: Deployment
      name: helm-controller
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --insecure-kubeconfig-exec
