apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cmk
spec:
  storageNamespace: services
  targetNamespace: services
  dependsOn:
    - name: cmk--pre-release
    - name: openbao-local-secret-sync
    - name: rabbitmq--pre-release
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Job
            patch: |
              - op: add
                path: /spec/template/metadata/annotations
                value: {}
              - op: add
                path: /spec/template/metadata/annotations/linkerd.io~1inject
                value: disabled
  values:
    eventReconciler:
      image:
        command: "./event-reconciler"
        args: []
      deploy: true
      service:
        enabled: true
    apiServer:
      resources:
        requests:
          cpu: "200m"
          memory: "200Mi"
        limits:
          cpu: "400m"
          memory: "756Mi"
    taskCLI:
      deploy: true
      image:
        command: "/task-cli"
        args: ["--sleep"]
      service:
        enabled: true
    tenantManager:
      image:
        command: "./tenant-manager"
        args: []
      deploy: true
      service:
        enabled: true
      ports:
        - port: 8081 # must match .Values.cmk.port
          protocol: TCP
          targetPort: http
          name: http
      resources:
        requests:
          cpu: "150m"
          memory: "64Mi"
        limits:
          cpu: "300m"
          memory: "256Mi"
    taskScheduler:
      resources:
        requests:
          cpu: "150m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "378Mi"
    tenantManagerCLI:
      image:
        command: "./tenant-manager-cli"
        args: ["--sleep"]
      deploy: true
      service:
        enabled: true
    dbMigrator:
      image:
        command: "./db-migrator"
        args:
          - --target=all
          - --type=schema
      deploy: true
      service:
        enabled: false
    namespace: services
    config:
      database:
        parameters:
          sslMode: "require"
        host:
          value: kms-postgresql.services.svc.cluster.local
        port: 5432
        name: cmk
        user:
          source: file
          file:
            path: /etc/credentials/database/username
            format: binary
        secret:
          source: file
          file:
            path: /etc/credentials/database/password
            format: binary
      tenantManager:
        secretRef:
          type: mtls
          mTLS:
            serverCA:
              source: file
              file:
                path: /etc/credentials/rabbitmq/ca.crt
                format: binary
            cert:
              source: file
              file:
                path: /etc/credentials/rabbitmq/tls.crt
                format: binary
            certKey:
              source: file
              file:
                path: /etc/credentials/rabbitmq/tls.key
                format: binary
        amqp:
          url: "amqps://kms-rabbitmqcluster.services.svc.cluster.local:5671"
          target: "/exchanges/cmk/mesh.tenants"
          source: "/amq/queue/cmk.test.tenants"
      services:
        sessionManager:
          enabled: true
          address: session-manager.services.svc.cluster.local:9091
          secretRef:
            type: insecure # Let linkerd take care of mtls
        registry:
          enabled: true
          address: ing.cert.worker01.kms.shoot.gardener.cc-one.showroom.apeirora.eu"
          secretRef:
            type: mtls
            mTLS:
              serverCA:
                source: file
                file:
                  path: /etc/credentials/cluster-cert/ca_crt
                  format: binary
              cert:
                source: file
                file:
                  path: /etc/credentials/cluster-cert/tls_crt
                  format: binary
              certKey:
                source: file
                file:
                  path: /etc/credentials/cluster-cert/tls_key
                  format: binary
      scheduler:
        taskQueue:
          host:
            source: embedded
            value: valkey-primary.storage.svc.cluster.local
          port: 6379
          acl:
            username:
              source: embedded
              value: default
            password:
              source: file
              file:
                path: /etc/credentials/valkey/valkey-password
                format: binary
            enabled: true
          secretRef:
            type: mtls
            mTLS:
              cert:
                source: file
                file:
                  path: /etc/credentials/valkey/tls.crt
                  format: binary
              certKey:
                source: file
                file:
                  path: /etc/credentials/valkey/tls.key
                  format: binary
              serverCA:
                source: file
                file:
                  path: /etc/credentials/valkey/ca.crt
                  format: binary
        tasks:
          - cronspec: "@every 1h"
            taskType: sys:refresh
            retries: 3
          - cronspec: "@every 24h"
            taskType: cert:rotate
            retries: 3
          - cronspec: "@every 15m"
            taskType: key:sync
            retries: 3
          - cronspec: "@every 1h"
            taskType: keystore:fill
            retries: 3
          - cronspec: "0 2 * * *"
            taskType: workflow:cleanup
            retries: 3
          - cronspec: "0 1 * * *"
            taskType: workflow:expire
            retries: 3
      plugins:
        - name: noop
          type: SystemInformationService
          tags: ["system_information"]
        - name: noop
          type: IdentityManagementService
          logLevel: debug
          tags: ["identity_management"]
          yamlConfiguration: |
            staticJsonContent:
              source: embedded
              value: |
                {"groups": []}
        - name: noop
          type: CertificateIssuerService
          logLevel: debug
          tags: ["cert_issuer"]
          yamlConfiguration: |
            {}
        - name: noop
          type: KeystoreInstanceKeyOperation
          logLevel: debug
          tags: ['hyok']
        - name: noop
          type: NotificationService
          logLevel: debug
          tags: [ "notification" ]
      provisioning:
        initKeystoreConfig:
          enabled: false
      certificates:
        rootCertURL: https://openbao.openbao.svc.cluster.local:8200/v1/pki/ca/pem
        validityDays: 30
        rotationThresholdDays: 7
      cryptoLayer:
        certX509Trusts:
          source: embedded
          value: |
            {
              "cf-eu10": {
                "Subject": "CN=appclient1",
                "RootCA": "https://openbao.openbao.svc.cluster.local:8200/v1/pki/ca/pem"
              }
            }
      activePlugins:
        - system_information
        - identity_management
        - cert_issuer
        - notification
        - hyok
      eventProcessor:
        secretRef:
          type: mtls
          mTLS:
            serverCA:
              source: file
              file:
                path: /etc/credentials/rabbitmq/ca.crt
                format: binary
            cert:
              source: file
              file:
                path: /etc/credentials/rabbitmq/tls.crt
                format: binary
            certKey:
              source: file
              file:
                path: /etc/credentials/rabbitmq/tls.key
                format: binary
        targets:
          - region: cf-eu10
            amqp:
              url: "amqps://kms-rabbitmqcluster.services.svc.cluster.local:5671"
              source: "/amq/queue/cmk.test.keys"
              target: "/exchanges/ks/cf-eu10"
      clientData:
        signingKeysPath: /etc/signing-keys
        authContextFields:
          - issuer
          - client_id
          - app_tid
      landscape:
        name: Production
        uiBaseUrl: https://ui.worker01.kms.shoot.gardener.cc-one.showroom.apeirora.eu/#
    extraVolumes:
      - name: db-credentials
        secret:
          secretName: kms-user.kms-postgresql.credentials.postgresql.acid.zalan.do
          items:
            - key: username
              path: username
            - key: password
              path: password
      - name: valkey-secret
        secret:
          secretName: valkey-secret
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            - key: ca.crt
              path: ca.crt
            - key: valkey-password
              path: valkey-password
      - name: cluster-cert
        secret:
          secretName: cluster-cert
          items:
            - key: tls.crt
              path: tls_crt
            - key: tls.key
              path: tls_key
            - key: ca.crt
              path: ca_crt
      - name: rabbitmq-cmk-secret
        secret:
          secretName: rabbitmq-cmk-secret
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            - key: ca.crt
              path: ca.crt
      - name: rabbitmq-ca-secret
        secret:
          secretName: rabbitmq-ca-secret
          items:
            - key: ca.crt
              path: ca.crt
      - name: extauthz-signing-keys-secret
        secret:
          secretName: extauthz-signing-keys-secret
    extraVolumeMounts:
    - name: db-credentials
      mountPath: /etc/credentials/database
      readOnly: true
    - name: valkey-secret
      mountPath: /etc/credentials/valkey
      readOnly: true
    - name: cluster-cert
      mountPath: /etc/credentials/cluster-cert
      readOnly: true
    - name: rabbitmq-cmk-secret
      mountPath: /etc/credentials/rabbitmq
      readOnly: true
    - name: rabbitmq-ca-secret
      mountPath: /etc/credentials/rabbitmq-ca
      readOnly: true
    - name: extauthz-signing-keys-secret
      mountPath: /etc/signing-keys
      readOnly: true
    #  - name: SIS_PLUGINS_CLD_ENDPOINT
    #    valueFrom:
    #      secretKeyRef:
    #        name: cldis-secret
    #        key: cldis_endpoint
    image:
      tag: v0.6.1
