apiVersion: v1
kind: Secret
metadata:
    name: oidc-proxy
    namespace: envoy-gateway-system
type: Opaque
data:
    client-id: ENC[AES256_GCM,data:ZGZZHtV56LI=,iv:nK/9A4lJRQZS6xvgaqcdws0WJfmRifAcV1Ba8Lcxbj4=,tag:z4dSY98QBroHXhkpBsad+g==,type:str]
    client-secret: ENC[AES256_GCM,data:xCDRUQcqH4mlV61dN/8pqGrhxCvwSeIpH8R1qOGRxrB5CS6dIKD+PLl7GRY=,iv:La6ZmnR6d6kD9TJivwriD+KLB3hNtGec4vSA07fA0R0=,tag:0vtKdlbKG60jlL5YYFUbUA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:rbyHyYa65WCmnBc77GYzAXrb/Sg+mqlU6rk+JLcCBs/MVOAuwkZmGeKMofY=,iv:1G279daASbwqA52cpT2uLTCk/7qVDuS3bXnxzUqAJLg=,tag:O1ROe9+CGe/zDy/l/nEtjA==,type:str]
    oidc-issuer-url: ENC[AES256_GCM,data:v/4GkbaXx0vz43J7kWjYnhLSW0eef2icgTNOTLhm9Dd8EJv2/uGk7vnt2nRr3uJIUe5j0wagIRY2fPk8+QOBH7W5Kcu2DzjmQ6fG/4xyGxEJVVo5Rpn0JnQjyUN1wKUdpN8PfSCeOwVISf5PH/8E7J42zqU=,iv:kZcIqafb06w+sxn2oCH37X/yEZNJlHWio8O/Zx/vQWA=,tag:xWwtFARXtJSJ4w2EJZL/Nw==,type:str]
    redirect-url: ENC[AES256_GCM,data:RU/YMaPN8NcsG8rbsJrVPIpk8IgqEgTCGiT8GCp5GgPmRPOC1rK51aBGbKMvEBTBsjDVduoLo0xSFOcBA5hPf1EfiTFPrAz+6J1mAD4S/Hrj8DYYa2MAPRMRfLsStdQNOGiTUW/j7F8xAzBaJZkQ2g==,iv:rMkUUiRPqkEIq7UgDYKrNh2ePI5oZi/Dzj1h7U/1SV0=,tag:nz/T8YlaZe6r6yQHp1jUlQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdUZVQlIvT2M2TVduTTNI
            SlNLZ0xDVUVLZWNjS09WMDFudnBnZnFkNFM0CnRDOVh1Vm1RdW9OaDJKNTJEWnFp
            ekZhclRJSDdRSVV5QUNMd0NwR3l1THMKLS0tIHBLRlYwa045ZUhic1UyRVBaNnp2
            M0ZmU0RBakNLUHZMWG44UUw1SU9IWGcKEAg++RDgi9jnPeo6hEg8jZlAgrJTl1wt
            aPiotjjYkLfocdq/uZO/8xgFl5tKa9+xx56eddejDH8xEJO45gwt3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpS24xdmxtcjVGSXN3YW1M
            L2hQb1ZKbnJNNXIza1ZOeS9UclJuL2dsT2x3Ck5mZmU2dG5hc0NpRFMwNnJSZ0Nx
            S1Z0TXd5anMyVEFabHo1NEZvZHQxdVkKLS0tIDhRYloyclJPbXZ3d1dncFJlbzJB
            WUxObnloa3VEb2g0d2xLeXpUSGZuL3cKrDl+m9AYhVkfzXf8VJstQhIssPH5wOuU
            Fw1EfEc8zYWTcGJW4rRmyB9IxyL1gBW+soNUy7mOo/uS/hpzKGi3BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNWlGeWtNZjBkMFZrKzNX
            TSt4dGJxOVdFQW5SMWRURVFkTE1hcGRBN2d3CmRtTU5TYW1kYlMzUHhEc3J2WjFr
            REt2eUg0TDNvTkZVcjF6ckZXM2NsVWcKLS0tIFo5cXRQU3o3RTRidVlrN0xXUWNI
            QTlIYVBzRlA0VWRNaEZ4OTY1NmhWcFEK2b5ZROaAatIS7y+mgkpZdeRiCvW8SH2t
            860gf51iXrF8bjsOne75qS3ks7cKESTLDCpMkV1LK7FpiQqKHL+ahg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSHJWYm81eE9jL0IwL0pp
            NUg4RmRBRWlNS3pvSmRtMU1UWTRRcFlza0dRCmU3YjZEbThIZ25SK242d3BlR2Mv
            dHQwUmRKTEcwS0xaWnlNOW5NZi9qQVkKLS0tIHRqeXIrZFNoUlB3VVM1ZkhZYjlF
            UkJNRUpueGRNVWVNYTBGRmx0M0c2N1EKxAjIRwHZJV31R8TuMltZMYgmxZ9w2rHZ
            NQ9JaBPJmgIzvQKf+7zLq3e6se9YFE7P6Nqi2h2txryLPgQEoW41vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T10:29:30Z"
    mac: ENC[AES256_GCM,data:eJEP1D6U+S4tL+/NxAhbM9W3UoqdIXNG07U8Y5DqGzFycCeBBkfRPCN8h92pmuv+2NWPFNem6g+A9vXK72HCDZgjwYD0vQIFqOCskWjYM2Wunzbo+tmZBM46W068P23x8RxN1r6c20w/DDxkA3xZ1AerXhHn3GZZsJXh0BbZ5pA=,iv:rM0c0ygURCwJet56aQdjFR1+wVjCl9O4DWfudd9BWAE=,tag:Plr//P283Qu/uGXxzQQ2pQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
