apiVersion: v1
kind: Secret
metadata:
    name: oidc-proxy
    namespace: envoy-gateway-system
type: Opaque
data:
    client-id: ENC[AES256_GCM,data:jLdue45j1oY=,iv:9JPEDD67R6UT/mJ+j84wusK5FfzcOnjF7mnuHAK9Xlo=,tag:lbM3/DJMBVNTSsd3sw0L/Q==,type:str]
    client-secret: ENC[AES256_GCM,data:IbPtAqW/qnpDbWYE4O/Q/n4aYugPgjZskQt0j00Fcr3s6r9KIOcVHBC4nEc=,iv:VW+UtPto88K8oNIVjAe6GPP+db4lmZWxlvmkZG4rSAA=,tag:Wmq20s1A3/C7R8s9pUXecg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:038AOIokdw+JqSRQ7XXyw4t0UJkJuxSog1k9QRcNOYqtjC0JZqQFDf8anWY=,iv:wd3zxsqFHEXsxF1Mdix3XeGZz11GJbWmSbPS7/1xPeI=,tag:rSzPH1tTB/GMRHDV1+or7g==,type:str]
    oidc-issuer-url: ENC[AES256_GCM,data:OGwYp4vkIFQGQtXofj/1w1mOA29V+/M4MvcKiYEhbRLR85gSi5xTHaEYco5eIWctI/Ipc9huI1870rkbpB0bQ2kyLDM/zI6FOgvy3b0F/ySyH61U3jzzJGTkeBrj9G5UDynikh0S5w8W8vbq8XEkWsH+Tas=,iv:/m6fwGaG3RmX8a+QTexHPfIKh4Ix57GxBE7oHIW8ydw=,tag:KYeEnSP9KIVoTLyDrfetKw==,type:str]
    redirect-url: ENC[AES256_GCM,data:MOW3Z9XZw+YnbApHhHA3IAYYq2KtsFYzqr4JQve98/sD6NA8X4yyU9atAxw+25FKT+mZa8W0YFTLEypA9cJ3BBJcmaB9OMANxgiOPWD3Ej1pH+0wwXZdx2OmzGUL+sGa41IUblkQX6fdYjkQZPJjwQ==,iv:wMSs2adOYdyay2Y12usBIjrE2bNSOob50bTRvhl7/4U=,tag:21CF+FLWLTK7/3Iu64QVQw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtblRLRDN3YzBhKys4VGtW
            eERYUThYdVF5WHFvdzF1cFowS0JhTEt5SnpvCmtDZnVvNVllN0ZhNWVvcnd5Z3hU
            NnhpY3pnT3Y0dzlPYWVvcXp6WEJSelkKLS0tIE90VnBjWTgxM29EMmZFWWJxckp3
            c25lN1lReUhrWFlhWFRNRHR2OW90bkUKR33dGTHTd6UsNB4ZW/4/FvByWWWvQsHH
            +VXCnkcWLjLsWng+XmVnOlgBaf+1tmJET63z5AXv4N2phURgPtbEFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMzZ0TmxueHR4bkdoNUpw
            M2FzcGltbG5mVHFoejVjVFhZUXJTS2krMDBnCnpSQnVTMUkyRi8vQXNoUkhnTTZn
            TVc5MXhUaGtrS1lsdjQyclc2MGJDaTAKLS0tIGk3MUlQYzBXL0hwdklNS1lub0NX
            bHdZcUYyVEhNN2lmV2lDS2U1UWh5K0EKMDO7Rc26l1aDjd9AF+Ob2TTLKCeiklNG
            MfHIWm5y43LIRvjhfzU8lSq1VUq+AwXb/ZMN5bUe103GD9v0Ha8f/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NG1wbERGNkhycmxKWWFn
            SDVpUndSWmU4SjQ2V1FvNGhpWnA0M2VQUW5NClE1TWRYUzFiNlNWc2Iwb3VFYmRa
            eHE2UURtdEgvRU1lc044SmluQUJvWmcKLS0tIGZ0ckExOWtja0V1M3FIZ0htc2JD
            dlZINzNDci8wbjQ1dzRyVjNJdktTTHMKrFu5cjDupxvS/CXlUjZZV953L5wguJML
            efAzl+f7oFdDkasfKYnEWgeZJTwO5cemDST5gs8e8vDuj565/MuYIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR0JUMDlnSU4vUmtCb1M2
            aHR6M0lWZ1hWQkg5WGxNb3lzVk1IbFdKZTNzCmx0SFlscHZlZEIxNk1LNllDRThO
            ckVQRWU0aWxzeThkQmRlb01jNEdaZEEKLS0tIG9od2ZZSG5aL2IzODVTd1VXK3JC
            YWF4Q3kvbG5JWEhrTlhKMVJyNWhkbFEK11l0Pt0bEVwZDrVLUR+n2pvVHskgfeeI
            jtcNO9oPalzFuW1112j2Ugi9phPh/mnBmGgytaw+ok23uHuzz103Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T13:01:23Z"
    mac: ENC[AES256_GCM,data:z/t/OJIEwYo6/1JZosWm3ccWPaGik+LQ43sU2+3vjzNn8v8go9zUfiwfDKycYDe58LvyNnYLegk6FzJZfw6R1eZgCwUmTLmajI41GI5Bhm+JkL4Wed0Pv6AuITzifDlwBW8hpIIPbUsPUJHj5w1seBnaaFLQblJXfZM5CXvDn9I=,iv:mwduO5tDY7QSBxsZDqaveOannnBs6M+OaVMHjli++hU=,tag:ZkEIfAed6GWH+IPc4G9epw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
