apiVersion: v1
kind: Secret
metadata:
    name: oidc-proxy
    namespace: envoy-gateway-system
type: Opaque
data:
    client-id: ENC[AES256_GCM,data:6mmFNQoEN3g=,iv:g44Xkt2B2bb/ge/TTVCr6Z++DvYs176SiL8P4HYXUKM=,tag:aeloH6r5VXh+/6ttSw1nMw==,type:str]
    client-secret: ENC[AES256_GCM,data:XIEXAp0gkct2XSs5jLnzIBEpwSZJ4Z+kwHN2TsiJOTWw/6DHRy7OQDA0fq4=,iv:IV5n90X0GcTv9npHyabERTzjaWUWfiPpQEZlaP/hN5k=,tag:DtWSXOEHivDGAJEd1t5lwA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:JV1c6MVDqUMfgzgDIrO8E7CREKu2QMmLsUSElfiXLRhYJYg1LSSXA3tihuY=,iv:rxQJykjxIjZ1WQKQVu8UN3X6qoWg7dhlrNE6bbVWYWY=,tag:Rjh4NLUTxDcECuUpSG1VKg==,type:str]
    oidc-issuer-url: ENC[AES256_GCM,data:KWoC15VukEKMJ7aXo1iTgNUP5aci0rnz0vqEC5ED9Dwd+Gnd3gKdmREoKW9A/P7Vd18zweu5rGQSBei0ZzS3gypLr+slK6/t7mYVuguAGVDOoBFnUOdRIVyeNKZsi1MuP2Z540LYD8DbQebbdedFx7rdGQM=,iv:nyh2Nd0jm9+pgoO2SDFjT4iYXvMmPwoSX6OnmMbBfSc=,tag:lJbOr7SdRMbMlkKoKwxfpg==,type:str]
    redirect-url: ENC[AES256_GCM,data:a7EzW8tR6FFb2Mg7UZrQNFmi9R+4CiBr6CKeTGQhFAcS+NGtV4rj8zjPlVdZTBhhdjQHkgj+hMpNRlqr6oJkeDldZcegXD5oK/cBs+taj0bOg5BMmCz/njlbzgOhd3TL5oI1sl0CLTUeMOvakayqvA==,iv:qctnVQgjhcXz7EGKdg9BnmPBdfaMWQFoFPSSjBRXmjc=,tag:ZxQ8NRWe5khfcfJRld1iJw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNEZ4VUg4WWMrWDVuNzRm
            bHVJOW1FajlYY3dBT0hxQTZVbkZoOHQ2NEJ3CmtOTmNOZ1ZEQ1JWQjRabGRnQVdL
            blFKZzBEK2ZpWWJHdjZVQjhSLzZOR00KLS0tIGY1d3BSNVBpbkoxN3l2UVAxM2Ry
            dFNuRW9kd1Zzb1U3VXZnOXFQd1Y0MXMKEVLKNJBiTo04FViZf/pgtUYsAgo7BTmD
            VIv+RI6JIEuFlYdYMPUnqZNjFNGNXjZVkR4kZUdr8yP2qNt4wksAFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMXlGMWtCTnhIQkJSZllN
            UUZnQlZQTHhSZXdCSS9OdHNJOU93blN3UGp3CkdHQkNtSU9jSGpCTjhRWXc1RlF6
            YlBjYkU5OXBzRVdPWmJKQ2R0R2NMRWsKLS0tIHovWks3ZHlxTlJxM2xCUmFMQTk1
            cUY3dTdEZlY3dnpyYTlteXNxNXROTmsKgYdOIeIpDKU9xF8ysN9c5iJXUZYHoTV8
            JiGgf5NslO9cFr45DxG8OnQlfgnrELtkWSulmrH/v9/sWnhlHstp8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcTBTMXdEVEQreWFOVFNE
            Q2dNMTZocE14NjhCTDZCc3o0am5Hc0JmSWhVCjhSK241TFFKdkszWkNvTGRiZFhh
            MDJlOVIvN2UwMFpnTWpPbHpvS1BBSFkKLS0tIEI1RnE3WmJOczh0VVptdEZIQ2lF
            UDZXcDhubWxHZ0RjTXlxTGFma20xTlUKc3ivRrsL7z2pGYj6311hJ2tCPOSJ27EC
            zBC/UcsxkZxOTOnQ3f1lD+zR1T4d6Uo8ouA8wi8UNZkkTlDksclnyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb2d6K2pwMW1KOS8yNGZw
            cmFKRHNyRk1TT2VaVm8yeHQ5WXNCS3dhVWo4CmZ6RE92MWxtamRobVhjUkRmTXVL
            T3hvVHkrdjAwcmhuOUxOZnhvM2JYUkkKLS0tIDNDRDJWY0xlM1djMXNtWmtBU1p3
            MEtqK1JTdU1XR0w4WWphNFBGU280czAKIb2V2nf9ESuP9Jg2pK9dRuCAUeJkB+P3
            KOM93pMgYEO6eRp8VE2prCDKsMpAUH4m5HlyIUw0l9/aBRSvuENP9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OHBlbVV2UFBCNTh6S0Rj
            bmJKaDlHMnVjZmZwTXZEcG8yZTZIWVZlRER3Ci8zc2dRZE1XclhxdUFBMXd1Ympq
            SlJmci80SWllUjZ2UEJ0aDNkZWt3RncKLS0tIDRpTFBPMjl1cjV5VXlOTUliQW9S
            MHVhYVN2M2EraWY5bHdBVk15OHk0UWcKUBc3ol5lBBMS+gu5GD84+kAc+u5TbiOX
            verCistNgWfMXx9VQz5yYyLg+5uMhdDhgAUy/fiTsQb8mnyzWrNjgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T12:48:13Z"
    mac: ENC[AES256_GCM,data:mKt5+hGZoJbiW7eGBRvXupSvxPlHQ1E89aiVSZWX41Ghaj5YvcCAdS2K1XmRsLAH7hI2L1msia95age9udhm3PAFJDMFwABfQ3U+Ip20tZIqNld2F/ZRxpPddMkNIGtxQuIykPp5HZvuigm0EJPguOpTyK+Q4OxV9Q9+6iBiZTk=,iv:Th4VHGVTSh4ATkgEaCUSk+BCYnysw1e95xbIamltMpo=,tag:LL6oq9Ud4uV44lq/Hg/W3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
