apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-identity-management
spec:
  interval: 10m
  releaseName: linkerd-identity-management
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  values:
    resources:
      linkerd-identity-issuer:
        ## Create an identity certificate signed by our root issuer
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: linkerd-identity-issuer
        spec:
          secretName: linkerd-identity-issuer
          duration: 48h
          renewBefore: 25h
          issuerRef:
            name: linkerd-trust-anchor
            kind: ClusterIssuer
          commonName: identity.linkerd.cluster.local
          dnsNames:
            - identity.linkerd.cluster.local
          isCA: true
          privateKey:
            algorithm: ECDSA
          usages:
            - cert sign
            - crl sign
            - server auth
            - client auth
