apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ratelimit-base-pre-release-values
    files:
      - ./resources/release.yaml
      - ./resources/service.yaml
      - ./resources/config.yaml
