apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chart:
    spec:
      chart: reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: reloader
      version: 2.1.5
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: reloader
  values:
    reloader:
      autoReloadAll: true
