apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../base/storage/valkey/release
patches:
  - path: source-values.yaml
  - target:
      kind: HelmRelease
      name: valkey
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |
      - op: add
        path: /spec/dependsOn
        value:
          - name: valkey--pre-release
      - op: add
        path: /spec/targetNamespace
        value: storage
      - op: replace
        path: /spec/storageNamespace
        value: storage

