apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao-local-secret-sync
spec:
  storageNamespace: services
  targetNamespace: services
  dependsOn:
    - name: openbao--pre-release
