kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: gc-cmk-p-glob
  namespace: garden-kms2c
spec:
  dns:
    domain: gc-cmk-p-glob.cmkc.kms.cloud.sap
    providers:
      - primary: true
        type: aws-route53
        secretName: production-aws-route53-secret
  extensions:
  - type: shoot-cert-service
    providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true # if true, allows to specify issuers in the shoot cluster
  - type: shoot-dns-service
    providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      kind: DNSConfig
      syncProvidersFromShootSpecDNS: false
      dnsProviderReplication:
        enabled: true
      providers:
        - type: aws-route53
          secretName: shoot-dns-service-production-aws-route53-secret
          zones:
            include:
              - Z04590372NVK1GNUX0CQL
  - type: shoot-networking-filter
    providerConfig:
      egressFilter:
        blackholingEnabled: true
  - type: shoot-oidc-service
  resources:
  - name: shoot-dns-service-production-aws-route53-secret
    resourceRef:
      apiVersion: v1
      kind: Secret
      name: production-aws-route53-secret
  provider:
    type: gcp
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.180.0.0/16
        vpc:
          name: production
          cloudRouter:
            name: c-kms-cloudrouter-primary
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west3-a
    workers:
      - name: worker-ek1uo
        minimum: 1
        maximum: 6
        maxSurge: 1
        machine:
          type: c2d-highcpu-8
          image:
            name: gardenlinux
            version: 1592.6.0
          architecture: amd64
        zones:
          - europe-west3-a
          - europe-west3-b
          - europe-west3-c
        cri:
          name: containerd
        volume:
          type: pd-balanced
          size: 100Gi
  networking:
    nodes: 10.180.0.0/16
    type: calico
    providerConfig:
      overlay:
        enabled: true
  kubernetes:
    kubeAPIServer:
      structuredAuthentication:
        configMapName: infra-issuer-configmap
      serviceAccountConfig:
        issuer: https://oidc.gc-cmk-p-glob.cmkc.kms.cloud.sap
    version: 1.31.6
    enableStaticTokenKubeconfig: false
  cloudProfileName: gcp
  credentialsBindingName: gcp-production
  purpose: production
  region: europe-west3
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 050000+0100
      end: 060000+0100
  monitoring:
    alerting:
      emailReceivers:
        - DL_66E00BD1DBECE8662B8E0B02@global.corp.sap
