resources:
  ingress-gateway:
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: ingress-gateway
    spec:
      gatewayClassName: ingress-gateway
      listeners:
        - name: https-aweu-cmk-p-02
          protocol: HTTPS
          hostname: ing.aweu-cmk-p-02.cmkc.kms.cloud.sap
          port: 443
          allowedRoutes:
            namespaces:
              from: Same
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                group: ""
                name: ingress-gateway-secret
        - name: https-eu-02
          protocol: HTTPS
          hostname: ing.aws-eu-01.cmkc.kms.cloud.sap
          port: 443
          allowedRoutes:
            namespaces:
              from: Same
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                group: ""
                name: ingress-gateway-secret
