apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secret
      version: 0.16.0
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: external-secret
  values:
    installCRDs: true
    # Create / use dedicated controller ServiceAccount
    serviceAccount:
      create: true
      name: external-secrets-controller
      annotations: {}
      automount: true  # revert to default token mount
    # Sidecar for debugging JWT token of the controller service account.
    # NOTE: Chart schema differs between versions; some versions expect extraContainers at root,
    # others under controller. We provide both (controller.extraContainers preferred if supported).
    extraContainers:
      - name: jwt-debugger
        image: alpine:3.20
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args:
          - >-
            set -eu; apk add --no-cache jq >/dev/null 2>&1; decode() { S=$1; P=$(( (4 - ${#S} % 4) % 4 )); printf '%s' "$S" | sed -e 's/-/+/g' -e 's/_/\//g' | awk -v p=$P '{printf "%s%*s", $0, p, ""}' | tr ' ' '=' | base64 -d 2>/dev/null || true; }; while true; do T=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token || true); if [ -n "$T" ]; then H=$(echo $T|cut -d. -f1); B=$(echo $T|cut -d. -f2); echo "==== $(date -u) ===="; echo 'Header:'; decode $H | jq . || decode $H; echo 'Payload:'; decode $B | jq . || decode $B; echo; else echo 'token missing'; fi; sleep 300; done
        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
    controller:
      extraContainers:
        - name: jwt-debugger
          image: alpine:3.20
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c"]
          args:
            - >-
              set -eu; apk add --no-cache jq >/dev/null 2>&1; decode() { S=$1; P=$(( (4 - ${#S} % 4) % 4 )); printf '%s' "$S" | sed -e 's/-/+/g' -e 's/_/\//g' | awk -v p=$P '{printf "%s%*s", $0, p, ""}' | tr ' ' '=' | base64 -d 2>/dev/null || true; }; while true; do T=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token || true); if [ -n "$T" ]; then H=$(echo $T|cut -d. -f1); B=$(echo $T|cut -d. -f2); echo "==== $(date -u) ===="; echo 'Header:'; decode $H | jq . || decode $H; echo 'Payload:'; decode $B | jq . || decode $B; echo; else echo 'token missing'; fi; sleep 300; done
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
