apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secret
      version: 0.16.0
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: external-secret
  values:
    installCRDs: true
    # Create / use dedicated controller ServiceAccount
    serviceAccount:
      create: true
      name: external-secrets-controller
      annotations: {}
      automount: true  # revert to default token mount
    # Minimal BusyBox Sidecar zum manuellen Auslesen des Tokens.
    # Einige Chart-Versionen nutzen 'extraContainers', andere 'controller.extraContainers'. Wir setzen beides.
    extraContainers:
      - name: token-cat
        image: busybox:1.36
        command: ["sh","-c"]
        args:
          - >-
            echo "Token Sidecar gestartet - warte auf Befehle. Nutze: kubectl logs -c token-cat ... oder exec und cat die Datei"; sleep 360000
        resources:
          requests:
            cpu: 1m
            memory: 8Mi
          limits:
            cpu: 20m
            memory: 32Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65534
    controller:
      extraContainers:
        - name: token-cat
          image: busybox:1.36
          command: ["sh","-c"]
          args:
            - >-
              echo "Token Sidecar gestartet - nutze exec um den Token zu lesen"; sleep 360000
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 20m
              memory: 32Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
