apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secret
      version: 0.16.0
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: external-secret
  values:
    installCRDs: true
    # Create / use dedicated controller ServiceAccount
    serviceAccount:
      create: true
      name: external-secrets-controller
      annotations: {}
      automount: false  # disable default token, we'll supply a projected one with custom audience
    # Replace default service account token directory with projected volume including custom audience token
    extraVolumes:
      - name: sa-token
        projected:
          sources:
            - serviceAccountToken:
                path: token                 # must be named 'token'
                audience: downstream-cluster
                expirationSeconds: 3600
            - configMap:
                name: kube-root-ca.crt
                items:
                  - key: ca.crt
                    path: ca.crt
            - downwardAPI:
                items:
                  - path: namespace
                    fieldRef:
                      fieldPath: metadata.namespace
    extraVolumeMounts:
      - name: sa-token
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        readOnly: true
