apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secret
      version: 0.16.0
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: external-secret
  values:
    installCRDs: true
    extraVolumesMounts:
      - name: federated-token
        mountPath: /var/run/secrets/tokens
    extraVolumes:
      - name: federated-token
        projected:
          sources:
            - serviceAccountToken:
                path: federated-token
                audience: downstream-cluster
