apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secret
      version: 0.16.0
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  interval: 1m0s
  releaseName: external-secret
  values:
    installCRDs: true
    # Create / use dedicated controller ServiceAccount
    serviceAccount:
      create: true
      name: external-secrets-controller
      annotations: {}
      automount: true  # revert to default token mount
  # Inject a projected service account token with custom audience using a Helm postRenderer (strategic merge patch)
  # This overrides the Deployment after chart rendering without relying on chart values for token audience.
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: external-secret-external-secrets
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: external-secret-external-secrets
              spec:
                template:
                  spec:
                    automountServiceAccountToken: false
                    volumes:
                      - name: sa-token
                        projected:
                          sources:
                            - serviceAccountToken:
                                path: token
                                audience: downstream-cluster
                                expirationSeconds: 3600
                            - configMap:
                                name: kube-root-ca.crt
                                items:
                                  - key: ca.crt
                                    path: ca.crt
                            - downwardAPI:
                                items:
                                  - path: namespace
                                    fieldRef:
                                      fieldPath: metadata.namespace
                    containers:
                      - name: external-secrets
                        volumeMounts:
                          - name: sa-token
                            mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                            readOnly: true
