apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spis
spec:
  interval: 10m
  chart:
    spec:
      chart: spis
      version: '0.5.4'
      sourceRef:
        kind: HelmRepository
        name: kms20
  values:
    image:
      registry: kms.common.repositories.cloud.sap
      repository: spis
      tag: v0.3.0-20250922095710-f35ae8644aa944b79533cecb56d86684ae509aa7
      pullPolicy: IfNotPresent
    fullnameOverride: spis
    imagePullSecrets:
      - name: registry-access
    debugMode: true
    # Application configuration
    extraVolumes:
      - name: cloudsql-creds
        secret:
          secretName: cloudsql-sa-key
      - name: db-credentials
        secret:
          secretName: db-secret
          items:
            - key: username
              path: username
            - key: password
              path: password
      - name: idp-client
        secret:
          secretName: clustercert-certificate-secret
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
    extraVolumeMounts:
      - name: idp-client
        mountPath: "/etc/idp/tls.crt"
        subPath: tls.crt
        readOnly: true
      - name: idp-client
        mountPath: "/etc/idp/tls.key"
        subPath: tls.key
        readOnly: true
      - name: db-credentials
        mountPath: /etc/spis/credentials/database
        readOnly: true
    config:
      # Based on github.com/openkcm/common-sdk/pkg/commoncfg
      logger:
        level: debug
      status: # status server configuration
        enabled: true
        address: :8080
        profiling: true

      # Based on github.tools.sap/kms/spis/internal/config
      http:
        address: :8081
      registryServiceUrl: "registry:9092"

      # SPFI
      spfi:
        enabled: true
        identityProvider:
          clientCert:
            filePath: "/etc/idp/tls.crt"
          clientKey:
            filePath: "/etc/idp/tls.key"
          tokenURL: "https://kms20cmk1.accounts400.ondemand.com/oauth2/token"
          clientSecret:
            filePath: "/etc/idp/secret.txt"
        endpoint:
          application: "https://spfi-test.cert.cfapps.eu01-canary.hana.ondemand.com/"
          configuration: ""
        callbackHostSuffixes:
          - ".provisioning.api.sap"
          - ".spcnatprov.shoot.live.k8s-hana.ondemand.com"

      # SPII
      spii:
        enabled: true
        # Formation type: Integration with SAP Cloud Identity Services
        uclFormationTypeIDForSSO: 86df5f15-edea-43a4-9cad-657f251f9135 # UUID for canary
        # Formation type: Customer Managed Keys (CMK)
        uclFormationTypeIDForEncryption: 73737ce2-5c12-4f2e-9864-11753ca2cc4b # UUID for canary
        identityProvider:
          clientCert:
            filePath: "/etc/idp/tls.crt"
          clientKey:
            filePath: "/etc/idp/tls.key"
        # See https://wiki.one.int.sap/wiki/x/FJexIQE for more details
        iasProviderTenantDetailsPerRegion:
          xaf:
            tokenURL: https://kms20cmk1.accounts400.ondemand.com/oauth2/token
          xa1:
            tokenURL: https://kms20cmk1.accounts400.ondemand.com/oauth2/token
          xgb:
            tokenURL: https://kms20cmk1.accounts400.ondemand.com/oauth2/token
      uli:
        url: https://ums.ums-stage.shoot.canary.k8s-hana.ondemand.com/graphql
        certificate:
          source: file
          file:
            path: /etc/idp/tls.crt
            format: binary
        key:
          source: file
          file:
            path: /etc/idp/tls.key
            format: binary
      orbital:
        name: spis
        port: 5432
        host:
          value: 127.0.0.1
        user:
          source: file
          file:
            path: /etc/spis/credentials/database/username
            format: binary
        secret:
          source: file
          file:
            path: /etc/spis/credentials/database/password
            format: binary
