resources:
  envoy-proxy-config:
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyProxy
    metadata:
      name: envoy-proxy-config
    spec:
      provider:
        kubernetes:
          envoyService:
            annotations:
              dns.gardener.cloud/dnsnames: ing.gc-cmk-p-glob.cmkc.kms.cloud.sap
              cert.gardener.cloud/dnsnames: ing.gc-cmk-p-glob.cmkc.kms.cloud.sap,ing.mesh.cmkc.kms.cloud.sap
              cloud.google.com/load-balancer-type: "External"
          envoyHpa:
            minReplicas: 3
            maxReplicas: 5
          envoyDeployment:
            replicas: 3
            pod:
              annotations:
                config.linkerd.io/skip-inbound-ports: 10001,10443

