apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: network-routing-system
spec:
  storageNamespace: envoy-gateway-system
  targetNamespace: envoy-gateway-system
  valuesFrom:
    # !! The sequence is important !!
    # Always first **base** and **overlay** (if necessary) later.
    ## base
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: echoserver-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: keycloak-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-config.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: gateway-class-ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: service-envoy-proxy-ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: registry-grpc-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: registry-reference-grant.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-test-jwt-provider.yaml
      # overlay
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: echoserver-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: envoy-proxy-config.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: registry-grpc-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: keycloak-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: cmk-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: cmk-security-policy.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: session-manager-http-route.yaml
