apiVersion: v1
data:
    csrf_secret: ENC[AES256_GCM,data:HvCTDy/zMxOAGsjpl7frFMHrBAxN42eajgNUNd/MQtIrp6UT+4x1IBVuurVclcIRHCzXfYzgMUGZzYIv,iv:79gP1e68osQV5/SqinpJ5BoiRZfGyu7c1musG0I2PXU=,tag:Ta15RHu4VGDWhzM2UqmASw==,type:str]
kind: Secret
metadata:
    name: csrf-secret
    namespace: services
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN3YvYkhDTk1vTjVKUHBZ
            NG54Qm9uM1hPRmdJMkhGMEZFWnFHQnFPd2hVCngvVjF4ZHRHM3ZNSTVMYzBKVXN0
            bi9PWkd3WUVIQzBvMUhYMEM0Skc1bTgKLS0tIHVSRkprVklsMUh0N0VPN0ZxZmd3
            L3VwZEgzbXdyNGxwSHhKWE1oRWFoOU0K25njzevBJz/T2h823sx4dDswuYj+g4Ix
            xe4f/lU1Jk0Q6OpVm6iAkVr8aNkrsIaHREehrn+DzaXYb/I7EMJQvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTGd1MndENXhuL2t2c0RZ
            NzRkaXpqaVlmT2lkWlE5dTkyeHZ5UDF0bEhNCkY5bStJM29MVGwvNWZnRTNrRnFS
            SEJySnYrY2VmRkxCeWRRUExnOUMvTE0KLS0tIEFnRWZvbEZua3EwYUtUc0IvV1Zu
            WkRJNmZlckVHZFc5WFlIbG5YYW5xS0UKctijlDQjLqQviqk/dETGj/+4L6es2apW
            p9CPztUH9pU8Bpy8ewWM73+19bxVcaQgKj6/RcxAQB3+AftK/SvgaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS3lkOVFmRjNPK3kyUWJQ
            NjRXWFJJQ0c5NVNtdkFUMWJ3RzhuWUc0OWcwClltdkQrbUp0RVloWmdId0VkQU41
            a0lhRnVjWUQvL3YxZ0ZlSEsvdE9QaVkKLS0tIHJFMmYzQzY0TjRFSDhPUksweTVM
            VElFUVVKbXppYU1HRFovTDBFUHJoUFEKVn1wb3tIvo+1rXNh5vrEfC41PGuc2Iff
            C0CmzdRQonuZSESC9sivLcmXV3Vq9cpl4tC/+oh7MIp/cGsYEcnqmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVDk4QzQxVk9FOHpFQmtG
            RWNyMk1peEkrK2pCWE54TEVMbVF0SXYvelRZCktFNjkrOW56MGRiY0t2NStNRUZ1
            Z2FRRDBFQTdIc3YybGlrT3YrR08xeFUKLS0tIEtySGQ2bVJqUWhCQkFGbjltYVQv
            R0NoR001Ly9saWxkWlNwTG9DaXJzRTAK41Lyh98mxogjizji3zM9R5t6z3GcHpDe
            lRsdZDyYcv3GrBx9p6mNkpw5gsEPGMAfDVj3Hen3Lfkh9Fq4HaCbNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:15:47Z"
    mac: ENC[AES256_GCM,data:u35DyaV14iACTnAugsjs7HKX9V24aeDzw93+G7VGJ8MStdKrs0t5LixoLipwQHmncYoBA37EBpbsTTpmBKrJd3ZNHjMccRmkSHYbhz6X0IWIWeyFBTnJsfxne35PV+qD5uUKl9ehl7Ek61OO017+Eu9s8oPuXw4nhGxJhltoibQ=,iv:Y+DdWn0LIVgffun5oG+IYeqEKj335XcND6tcMyYkAeg=,tag:zQ6oJiQc/Q6ho4S9+DBbJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
