apiVersion: v1
data:
    csrf_secret: ENC[AES256_GCM,data:X88iIlJvLTPQ393BN6zDn+fyOnrf08BqrPnpq8RJC0CakDoxeGEZvhVzxc8gKeBn0bMyKKrjxSiXze8m,iv:/7o8AK6e5p6wrv9rmP/EmUpL8s67Q2qiE3/nzRRaDuE=,tag:2U+VIHqyILSINh2wkY6ItQ==,type:str]
kind: Secret
metadata:
    name: csrf-secret
    namespace: services
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTlZQbkpxSmU5dkg3M0Qw
            c0NyNG5xam1xZERHOHljV2pvOWlHVHl2QVdRCkdTQVNBcHZUV05FODJ6dHhMS2Zz
            dldqVjhBZlNMSjQwNVV2c0J2WVdZNk0KLS0tIEFWei9MazAyK2ZlT0t5bmlydHIv
            UHpJYjFhUlRpdEpDcFFwSmxsQXMwUkEKLvajdOZZ98Xha2IVJCI56W3wwue2E3vm
            4MnsUtu9Q0adA/MUbsrDuERIb/qbmCvFfRZdkQPUhv5NQIj823W4tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSU1DejlnaFNLNy9sd3VV
            TWpFMkNWMjROYmtxemhvRkJzUHViUmszT3ljCnBnSE1HbE0rNjNqQktmSElMVWRG
            bEhydEFmeDl3aTEvNHgyR1dIN3hMbHcKLS0tIFpZNVNpSlpVaVFsenhZSXZyVnQ5
            ZW5BY21IL0lZdHVDZXZCcTI0Um9GOWsKnD2e+zHvuHOT0igH8H6qKdKh5UtwpSwz
            lnhMnjBoRViDhPufaJ9mldONhig17eft/tcvl7dHoJ97/qCq9mF9zQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadHArT09ncjJmRFZLODha
            K0FheXNVMHRzazdzOUI2L1hVQmlIcHliQzM4CmVoWnRnQzQ3YmxXMkx4VVRKRWNF
            Y0Z0bnlzQmUzenBlNGhEdXZEc1I3ZVUKLS0tIHN4TTU0MlRFSEhtcUJsQWNjSElU
            M1ZWSXZkbElzMGZLUk10dWFyRlRIcGsKGijWxa/JRYmbz/8v1IS9x4oLS2G1FdZC
            iIt7iEFVadnAkzxGJiOjhvW719dx0xjNZrPWv1GRTFRXkbAkh0vJNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEekdkdU4xY0JrM2wzeE1k
            OWw5UkdUZSs4SmVSMU41WVJFNTFHSnJENTBVCkVxTVlwNldXK2U5SmM2ajZaOFY1
            Y09FU0o5NUUvZmkzUzZZTU56VzZaLzAKLS0tIGM4OXhqZHFHS2dzR1Mxcm5CMkFQ
            WEtlenFzK1pmSitBbHd5VjFqUlAwZTQKINZ6Q6aATy1bH36bfawY59s/78ojAk0x
            rMTn4uSjWGzNR1Abv7KFJCIuDbnBb41YYAFvo0dEF1iKRaachbRcNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:17:30Z"
    mac: ENC[AES256_GCM,data:v7VhoLpNxBqdUV0OlJoCYLqzN3MUHaVHPoetxYk6uzh2Opw6Xp/eA1cx3YujIN2xIlqo71JhY66FaLbwTW4wZmiXYK09KtmYu8P1slSYu7WbTJIYQYkxxqHd05povHpMHo6z04Ge35Vknk1d+K86quPuW1gzn3j/FI9ScrZ1oW0=,iv:cYNpY4bhOZnBtKwrcFqHF2KG0HrD8QJQJdxvnjoG8Lg=,tag:D34lEu7X/RcRhx6vT8JHfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
