apiVersion: v1
data:
    csrf_secret: ENC[AES256_GCM,data:wYxX+09YTqssJq+0eV/LJolInq/IZx7OECr21IaaCRr7hQsE3f3JgCVvwzgFFzcTLA1d9+cHVyFllHhV,iv:LgaanM0zs04X6xjB7kvxuZhe9QZl3KSy0bS75m7Pojw=,tag:EA9K2pz1rNxV2eQQfaeJjw==,type:str]
kind: Secret
metadata:
    name: csrf-secret
    namespace: services
type: Opaque
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TzlqMU5NWTlrSENjVi8r
            SHI1ZXdOL1E5V1ZpOGc1Vkc4TVJBTEhvV3dRCmZsczdUUmN6YlVIM2tWdXFESllD
            MnBaNjM4Z284YzIrZy9oWDdjWXhSS2cKLS0tIHZjdFVEbXlwcGhOM05XaU1HQnVn
            d1k3Y1pDRjZnYkVhekxHTjRwUzdzWTAKpoFWVkDBN1KSzuHPZquwz8yUlmR9R1MN
            M05h7Qp2rLEz/AnSNlnnlrELADL1v/JvqDlu9/j4mby5SY6onUhbaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUFpTDQ4TkdnZnVVb2d3
            aXlMWitWcC9HcG5XTFlNZTAwM0dtSHdPQkZvCjNBSUtmUXdMNTBSVUVRQkw5KzhJ
            VHVHcjl6bTJxSDNFd1lGMWpWSGliTm8KLS0tIDBMbjJ3QXg3WCt4ZUNETC9QazVU
            RTVIc0lLVVhTWlp6U1doWWNwZHdiaHMKoMYal1i8gPgB+STNGIqdUIPXBpw/Ae2E
            Jq7VtXx16jd8cyXQABLEvwL7mnorMcFQjTBFiaB1WEJuyDZHa40tVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeWdCZTk4dENXNkU4Vkor
            TGlhSU9KNmRva09rNGNqcUU2N1VieXE3THhvCmE2TUpQYTFtT2ozM2FPQ3Z0M3Q3
            VDI1bHlJbThWT3EwWXRkZFhvRlN5YUEKLS0tICtTT2tub3FMR1dCVmZLV1VVcFF1
            MWo5VitlOUlYRndBWGlBenRHZmVaOHcKWj15Oozy/XYwMIYbZbBssnAE7bvwVulb
            HVgsRWkoSfEsmQXrNFWJO60OCvTycC+rNoasJAZ1+9n8h4egihholA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckg0TDBrS1NqektMcmRh
            S1U5MXdSWCtaZlQxblp3Q0cwZCtiZ3I0eGdFCkVLbUhOeTJPMFBOMkJ0RWp0dlFx
            aUQ2NnBoMTdXUHZ0S1E1UHpMTHZtNDQKLS0tIFo3cXRNd1Y5c2s0Z0x2Z1dpb3Vk
            N3NXQ1BQZ09yY2VVbE1MZEwzNE05OTAK0IHtDeYqgHYxkJntHR1mRXHm/MAGIsjx
            UAtCCWsjmjajtWl9v+HGxI50cV9BzSrlQYVlu+vJsyx5Qje6bwm9PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T14:41:30Z"
    mac: ENC[AES256_GCM,data:J1KGsZ3yJunNuj4LVwWP/3bQDpQU8k9Mg/EhyrWnXfx5/Fsnelw51b34G3HCLpEvFIekgPxZJ73Hk/dO9xT7MsPa8aXSGUg3AuntoGxIIlXl5qoJKzth3Lsh3sNU7cIGMVuA0aAZIuiyU/LJRqdyd0kMrZAsRhvz+njoYT+KbE0=,iv:DaNSQnBv7J0zSL7HJM605YGQvEWPTWHnTVvXBxOe2E4=,tag:In6qgPM41AtctuVE6KkBng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
