apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echoserver
spec:
  storageNamespace: services
  targetNamespace: services
  dependsOn:
    - name: echoserver--pre-release
  values:
    resources:
      deployment-echoserver:
        spec:
          template:
            spec:
              containers:
                - image: gcr.io/k8s-staging-ingressconformance/echoserver:v20220815-e21d1a4
                  imagePullPolicy: IfNotPresent
                  name: echoserver
                  ports:
                    - containerPort: 3000
                  env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
