apiVersion: v1
kind: Secret
metadata:
    name: postgresql-openbao-role
    namespace: storage
data:
    user1: ENC[AES256_GCM,data:aMec04gtcKqNrpAR,iv:XYPAhO6irZfeJ1gWgUbe7OyLvo5esho5DZLuMvxsogE=,tag:JgUdX0ZXw5sIAfrshVs3eA==,type:str]
    password1: ENC[AES256_GCM,data:U93AqQNVkNnpdgDU55yA+gX/fuGRVglQxyvzBA==,iv:w+OMzpk38VtDVMGShFWdUfGAfrpJKlnE/YDa4nld2mU=,tag:8Ppinglg0a2hpaW0GcrSgA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcWdiWlVycmRhUktKRnlm
            anIyZThXalZvZmxza2x4UHk3K0ZnZ1RKMkdJCkVDeUl2MFpvRXMzNGFZbm51S0Rv
            eHRBaTM3Q1JrYUxtMDNPTTNyeHplWWsKLS0tIFgyTjRFckxqTnZzdWlNOUtEaGVP
            bUZJaVUxTTE1L0tiNms1b3dYVXBWS00KiFm1AsI2pdzuBF6f8lU2Dv62oJ8a6kQE
            5IWQFleYA4xGEiShUpBAbZmFXBgaghjUr2qN9ImCdbz07gv527uMng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL3NKbnk2OWpVbUQyL1RC
            SDU4Z25SNFJvTGJtNUNyUmFUWWpJeVJXQWp3CnVkUWRyVnZYWExyOW5jdmZMcits
            ZWxiYm9Qd1dHT0Z2V1gwQWNMdTZnZHMKLS0tIFVPQXFLOGRhSkZjMEZ3S0xnejFu
            QTBDYlBkcDNnejE3Q0hBZFZ3ZGtma0UKm/1GE13yxRJqsp+9rI+eNxc7hej9X6u0
            9o4uqCrz/U45XJnXSFUAeD1++WRhZmgkchBcWH9oFhU16x42MX7vBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RmEwYXRGemwwNEsyZmRy
            RDhYeWRieVJNV0M1b0NtRHJKNUJTUWZJU0hFCmF0a2NSdExqZlNtanB1VzVQU2RY
            MnRiZEVsMTFBTDk3K1NndTE2WnBiOFUKLS0tIFJWejQxVnhqUGkybGxlZkRqYmpo
            enFSczgyTHZKNVFrM1ZzT21IcUpnNGMKdWERB+Uc5asjdRPTUDWimo1LVA04sqsb
            NOMCs7WaMus/v7HKpOtdEyH+nONM6KHLHZZ6y4CcPlikp3brpz1uHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckh3SUdxL0cvZDRlQTZQ
            WWFQRTJMYjBMUDV6U2hXSDNSRnpGSEgyYXcwCkt0L3cxVGRGYzVyZGJnZ2lJWldv
            L01NbkJxVWtnRENNbEdiTEppVEQxVTAKLS0tIDVzZlgvdVJycCs1RHBsUDVRVCs3
            cVpFbGJFZllBbnZYdkVUdFltd0RwT3cK/mL2nkB0eDWVdlF11s2ER0jKMuwhSgJO
            JPHuh4AHnEmueASV++Szt6CXk5XXeLAanyFyZkpfXNF6oeTfdfiqJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T07:22:24Z"
    mac: ENC[AES256_GCM,data:vwXGA3TCq5/USQKlF4Nrys5+ZaIkc7uHnMIQDQAGl/rHhc50E4jFMLxkakD1EmqyvQsNdwDoz2YboDkGggCCxPyDV34sjiSeag9Jo5t74A39rU6buhyrad/dF6aSHCHyAE+lxUnLJpGPZjh+x8G3j9a2Yh3mEef18NjOHw0g37g=,iv:OBIxQgFLWS8stPzZeu97t9wtsGlRRhQ3u62WlA6tnVo=,tag:wFzcWhK330bjRnHDbsKrPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
