apiVersion: v1
kind: Secret
metadata:
    name: postgresql-openbao-role
    namespace: storage
data:
    user1: ENC[AES256_GCM,data:FAeIhz0ITpjGeqvn,iv:A59a3ULUuWbxsbKyhWxbIyAwBZHiops2XE6QgeXYFJo=,tag:uEXsDa1fRhD5NTuF2TqaXg==,type:str]
    password1: ENC[AES256_GCM,data:zpT3AOPa2zV/C0rIiKncUbYSuxtCTNvI6vQdIQ==,iv:f1D9mgS57QGa6dqPGiwdEnbE3nBMgvGK4QIkEe46vQM=,tag:gykNOH0gaLgX+Oe6RsD0Hw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYklaL1BkWGFhaUtKRDhk
            dlRtWDduMW56MDRISTlsNERsMW9iVWJjUm5zCnh1cUpPckpwUHU2cEplVDMvclJV
            N0w0L1UxVy9kZUhtMEIvNHJLR0UvbTgKLS0tIHlYMnVNZEV2ZmpzaFE0bEkvUHhN
            R3JOQlBsV0ptWnVBVzBtanRBNWErRDgKj5ZVb0qc4ZjexmIW42YzTGOjrCa70prm
            x9pEZGVhnx7cPBajOxrBExGmB8b44PZJkEr6KUzMuJQYtunYp6z6Yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMXZWZVBadEJVRTk0R0dN
            UG9Tam90Z051aTNDYWRUM3JNelhzQ3NnR1NrCmYvbWN6VXVZV0lCUTFUYjBnTXh5
            L0w2a1QyNDFqb3V2SDZDcVVOcm8yS3MKLS0tIFhGREJpamg0QzlrRFhSZWo4TkZk
            QjNnVVFsd0ZjaGxvYi9Wa0tHZTdoOGsKTZmPbRIamcYSXDLofrrEqN3fh8O7fDEc
            LmfxN/oCYnOBiVQtuefVb2VThClILfe4QihhGPrn0EOOnGxHRRCvGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM1FCNEJMMUxTVnZpeGhG
            MG8xK2wzek9jemhweThLQ1RUTllQWXpZYXprCktzRWJQNlN6OWo0SGtuNHpJMjFW
            czU1K1l3ZERvT3JzMUtXN09tNmJyRHcKLS0tIDQzVTQwbWdsM0hLaCt2dXF0ZkF3
            VTRveUgxeStBMnlaQ1FXQ3NLbFUwblEKktgxPnyKyWpDhMsCd5y0cCuFsRZcEyCT
            gzpgq9zwnIH/Wc2U4h6J53DXvU73RHz1HjGdrSwrZiMevvk68hS8jQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5akZmSk9oK3VNTWViRmE3
            dWRFRUhzN3l4QnY5NjI2NktTY0xNOERqb3lzCjZxZzZmS0JlaUJmYSt6Y2I4Zm5D
            UGdmbHBkM2tJOTRscHowdUlJcGlTMGsKLS0tIGhwVmFtanlyN1VhRk1aWjcvOU9n
            VFN1bi95WG1LRFJKOGYvK0NPUUJLMzQKGSJCRJT7i3aw+n256Wo1Bfcg9fNTb/67
            BkrkKEYQqfLnRJjp3+b2f7zrRfcRkjtwjD5MEemoh5vRLqG12MIR5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T08:17:30Z"
    mac: ENC[AES256_GCM,data:ipCxvsovwj6XLj09/tjmYRFBCOQsUQAa+52cOO9uMitQIxFkg3SYYjitGa70mLQesu1cYfmShF40THc/ZFx0Ur/OIGwiQmZkOor0mrwa8jVEQwzQYmhkOGprurYGX8O7X8SIxq6a6pG/GmC/ukNb+P6orUcVK4CANp7upUf/WTE=,iv:p0uHipCfhKY7SsZbLUWHDDFbh4gZkWmiyOTwx0ysdvA=,tag:qu8fJQ1NNbP5EhKl1cFNsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
