apiVersion: v1
kind: Secret
metadata:
    name: postgresql-openbao-role
    namespace: storage
data:
    user1: ENC[AES256_GCM,data:Erra6xKuQ4M3R5xB,iv:AK5ffdwN8+eaD+ETfijcO1r4GGsl0zga7AuRmprWwaA=,tag:WWGm0vTViXsFwVUq2SzxYg==,type:str]
    password1: ENC[AES256_GCM,data:gK0zQjqjMYatU5KalKWKSVbPVdrsTsozNJ6JaQ==,iv:jq3Qo2Lbuimdz91kPBr/07RJXhCDC+0nBaI5bqa3smY=,tag:gcw5/8beL/sEqjgAuJGIlw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTS9VWHI1NTVYR3AwWW9x
            aHNJUzRrOHJvcUlmWlhzdFI0Z1Q3ZXlWNkRrCllhWkc4bzVNOTdOR2tKM2t5T0dM
            L2E1N3oveWx5S0gwbnlaVE11TE1kVDAKLS0tIGRIREcvNkxsQjZORFh0ZW4vOW5q
            RWNmQVVUVjg1RG1IVzVlQjdLZXBHejgKj8I1DPXzfJXkUYCI7Tr8IiuycYhzjOPV
            S7FEUpTRq/jGXoy2VDfURGHr4oCfCpespnteLdZYGt8fzLnl/2ylWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdXdxRk54b1dtR1RxbmZk
            ZHE3RXpmejR3ejRSU0pKaUhGVGtQdGRLR2hnCkR4UWdRSDh6c09ZWlpIQkdpaEpk
            M2tWV0dKcElNa2tSenJjcXhxU2dFazgKLS0tICtKcE5tb3pmVnNRSHo1Ty9kaStM
            a2NoemgveVpSemtDdHEraWNEWWpPMGcK29EXwchkRIYP1z62Atuq2ynF/nnIB8ou
            sr7OX0I7cRHS6yBm6jzZF0mElvCuw4heJ7l5zOLL0bzPuJjaZzECPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZG5GWGJ0ajkxUUZlN2Zy
            OG5mVjBRbUdQcVVaQWtSYUZwM0xCbGQvUHhZCkgvd0tqWmFnYjlmNUhrSmdueUZl
            YThDM0wvU2g0VTMzQ1NjaXQ5VlRNcTQKLS0tIFVsRmlNTER1QjBBMTR3ZHhrQkV4
            cWhheS85RUk2R1ppWWhCNXV5MExqK0UKiBEkBgTsFKgkfgYBYVd3v8Pb9ZwWoT+s
            PahraZRn139e0FheZ6bxlz7OzR4FXAkWql0IR5UQz1QbWYFf8mAEpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YU5nRU1RazQyQTdtcWdl
            VktwR3NOQzI0MDBucnlDTytoQUVkVTBwMUJFCmo3MS9TNHdtVHpJRi9tanBMcThF
            aTlLTUtsZmp4bWNsaDBPeDNsZzRZYVEKLS0tIGpTaU5mWE52djdWR1hzL2srRzdY
            YUhxNDRuSmVoRkozZDhVamQ2Y005NkkKk652Wr64Kjq4gMkKpmhzdFHGWgeWU7fL
            zo8TGFbj+W4V90q5i0vwdfyotttDzZNfYvb27LD4LVVJUWB3Y7PgMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:43:12Z"
    mac: ENC[AES256_GCM,data:u36koACoum5Ml44YAa3xVQvKudiTNIYn6wQqS1r5+jM2G7p2+vVECv3k73HrONmLf6kGoaxisPGXhjO6AEqvn8xifSqdOFjrIa5NOiOMyby4Ovwd8iYgBrAxjEZSrGMZVbOr7UB9H8f3dH5hfCRCBK3U3RVPe4XcCg/BUZIeXCg=,iv:ZCOWR8q2lBjGs6CWaRaZbtUUBaJTw192WLzP9Oq7BGE=,tag:FDaOoCjYUO/ujQk1c7Gv7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
