apiVersion: v1
kind: Secret
metadata:
    name: postgresql-openbao-role
    namespace: storage
data:
    user1: ENC[AES256_GCM,data:a6xa+ujN+2u2x53d,iv:UGjCqdZkUrtueOL7j+fWPiBvVCT9dF4nWKBNTeARLA8=,tag:MYTI9XZP7V6oVZ//mN0Vjw==,type:str]
    password1: ENC[AES256_GCM,data:gCbB3YphEW2YW1vjFXaRg+sfXorqFpzqD4sJyw==,iv:eZ+ujZnJAGDhpwJ44wmoBEHkTaD3gaYW3jLrrTPCSVw=,tag:c1WL1mQTVqZsYsYl37XzEw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTkRQSXltbk9oM1BoYjlZ
            S0ZDd21BWHpZaGtmZlRHZThxdnZ2TS9vRnpRCm5BWmNJb1JhVXRLMTdlU1pneDcz
            aWwweUdFU0hjZjRiVWlWc3YweXhOaVkKLS0tIEFMUzVROE9HbHV1TkFxZFpuaVpN
            M3RVTGJNUHhxSllncEkzOE1WVkpjOEkK2v654BqxqE0jyrsa7dkSliHSXkYvA7EV
            8bbWnpYIuoiao38r/h+3Tm4J20AkDAak36u/XVsL7gniZ46sttuOug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva3hiZ0F0Sm9ycWFPSThz
            SHVqQU5MTU5FTldHMmVOZXR4eFhhalRmVUEwCmdNMWNocGlLYzhHa3lvWHV3U3Mv
            dU1tUjRVeU4zdFJuakV6WGdTQ082akUKLS0tIFBsSmYvd0RZWHNEVitwUHQ5Zm9S
            L0d2cGxkdXZRVWQrV1RHNzlUSGRFWXMKDp0ejVKYxUBpG6Izrq9QTD/8SBvS8CCO
            yyyrk7qKu3YH7aoZy5WY+kpgpkOOgfFncOAmrnpPvuVQR4UWpJruwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VnUzUDQyNW1PbHhVK1dK
            M0JlNUQ0T0p4VVI0TUd1L2VmSUdDWHNYOEQ4CldQL21KVlJiZTczUGVpd01OcTRC
            cTVkSE1STHJoZytsSFVYNU1UUURjc2MKLS0tIENXOHRQemZqQzhiMEtnQzZjUncr
            YkNtcGRGOEVid05xRGUwdEFRVGtmTTAKqOKnEysezJqOiQY5enK68k2h/skoZr6o
            sFDQyODwHADwkT3+EKS0sqeGn7bQDamttOFm1L6W4Orl7KEOEnJghA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MC9KSXh2Ny9sOTdRWFB0
            YTAxaDhNQkw5TlZGa3VlSlhNeHhqeDJHMkhJCmRHY3NHWFE2VVQ1WkJXdnBYTkNL
            YzZzZ1NUVzNIalB3SDJKRzh6c21ZQ00KLS0tIG9HUDNPNW5VOHBKSnVNeXNKNEdi
            Um1HQ0pJWlNZZTluRm1CdmtySzVQU1EKJvVPNQU+7IoWri+kmVvftWzjGz9akT8U
            cA7yORRXCoT6kFikcG/T2JPn/bOWa8W5ssBqkRNGrB0OSKYiKcG3PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T07:24:26Z"
    mac: ENC[AES256_GCM,data:/KBxVy6RKOuo1Pgrl3izGJFLU99D6jRlyxovVKVbe+Na0nwtsXIwPbaXRG3ffUD8zl9nv/cm29eU8+kyW+B07TSVGrplFQy9iCXOkU7pcjA0kY1e79vQIbPOvltQafSnA0fYU6zMBgChyFZJvsQ14g4AaqaqluoVSY56cNWgY0s=,iv:C0e3YhdO7lLbBVUmrWH5oK5ZHT2xchlQtIXHTzC3www=,tag:xBrjl078kBLHuuctqKMdug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
