apiVersion: v1
kind: Secret
metadata:
    name: postgresql-openbao-role
    namespace: storage
data:
    user1: ENC[AES256_GCM,data:GUN6HXaeLvdBUPUH,iv:ChO02BvXgP6bCsOXaRZDOyhCQUoaZtwcik6bbkz2Gqo=,tag:H32axA/Xau0O5E6nUAGjZw==,type:str]
    password1: ENC[AES256_GCM,data:zCqscQPCVa7xzH/LjaXY00blH/L8X9Tey2ay9A==,iv:Irk9lo75elRenvNUidb9NhHp/7sVBgLOsW9hFD1nboo=,tag:7bdkW6WL0Ow4cZ49WOfbig==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M1JvM3NFNXgwSHd1U05r
            Q29ZQ3oyZGUyU2ZVRnA2L3RaUHAyL1ZjYVJjClIwMlBQVUdGQnhvem5ZSjFlcnNz
            TUdTS2o5WWdlMWNWQUdUWjNScnBSaFEKLS0tIEJnSFhySmFSdWZDQTJBYVZlM3lO
            c2YrOHdFM3hld21sOGFOdFc5bFNWTGsKSly1zNfdT9hfAvwZVVQ476poIVhGF35J
            kssdZ7SNQ/Le78ymRFdAcOIqnDr4jb2mKB2RDsa/OZ1OvAjIjBsfuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRmlpQWk2ZTExTHRSc1Jt
            b3ZoenJnTEpvcVJlMkljU2J3TExsVWxZWkNjCmQ2bWJoUWdnR29Halh5bHBDaHhF
            a3l3eGpmRTNRS0UyQnNxWUFGWG4ydGMKLS0tIGNMWWYrWDQ1Uy8yY2VkMGRLZ2ZF
            T29lc21FZXVxWUR0Uy9ialVESy9HTWsK2lG77m8h+kaRk1FR7/RGcPjhjriAZoM2
            ODewOUPvfvai4kuNwNFoMfhjYhflgMlmXgs46KFy1ntaxdkV8xJqvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NXFrZDBOUVRuVzd1N0tB
            RDJjM3E4Vlc3eDRzYmtoQ25iMFcvS1loV2lnCkF5V09ta0N6N2laMzFDRUN0NVJB
            UFFLQVVDUXBsbFQ1ajUzd0tJdUc2VE0KLS0tIDhLNVpjbFpvZUtpRVdheGxjM2hm
            N1hiblJORG5wd0M1M25IdGxsVlRBb2cKBEwxT6b8AxFC3wPkNHAqJ/TRZtz6OgTz
            6vPxHfAFoizs0i76M4BC54ycICFIhwmCVVb5VzSjKCJBA49ndFgcuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTGcrZ1BwaEhLV21ETU9z
            ZldpQm5JSVdJdnYxYkY4VDNQQldSRW5SQ0Y0CnVyVlhCbWdTVS9DaXFrZEgrQk9R
            SWFRaGx6U0I2R0ZUT0J2Z1FVY1FMOW8KLS0tIFhuZy85VjhXVEFseWsvbDRlWkVp
            RGVmRnFUUng4WXFPemlXSThaRS9JVHMKGN1s0dzJF6MXJGRfDjjzGO1ogwC4C5HW
            Guv4HNlfK73G6Lao+sIfgWO8gFfqXhbaAjVALTbx8wUtK6j2B6LcSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:09:10Z"
    mac: ENC[AES256_GCM,data:OlvcUP7BIW9lrHbs4rUzqxnsocN5PXZrkEIqf0tEhfBgEYPYaLKSVv0ne6YI85ju8zMQbN6i4bvII6P/5sRqYjSwlKDmFJkdUFT+mXMPm/efvSzc9r677tfg+8FlP83V+aqpYiu3mNFTRjqWWb+AKBmZG1LmB7gXWVWx8SWcqZo=,iv:JGB2tuVwv4L94K4ALlnlEQEP249mXgXGoWgSVNJgeHc=,tag:B29H8TK6v4FkhVGPGfU4gQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
