apiVersion: v1
kind: Secret
metadata:
    name: postgresql-openbao-role
    namespace: storage
data:
    user1: ENC[AES256_GCM,data:g65i3ncW7mjhzQWJ,iv:c9Vc8nSGrBaWJCB5i6Ii9uS46601qx+xDlYVfvEq77s=,tag:VeoCr/rTlBaIAQbsgRm6Jw==,type:str]
    password1: ENC[AES256_GCM,data:xMFEyHhBfPlK0rmlaTGvM5C9ViFz7pcdzUN6Ig==,iv:fk070TXNYRSC84GQbFjSDuzjhdKsXnFDYOQQmkxa8Kk=,tag:fflEQDcrtq2Rd1uRcTnxZA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGblB6MGNoZ1FURjhobXF5
            dnJLOGdhT2ZJZmlwRVZQYjQ4b0JlMDFHVlFBCnczRnBBenFpamxKSmhpODNUUWRu
            emQ0ZE1HYXV6YmxQemtDZ2QxcjZHMXcKLS0tIGJhMVkrbUtIZUNwRThIOG9leG1J
            L2tCdW8xbWw2Z2s5aERPRUZKWFp4TWsKqsfNrYUbcXMra1xCswBi393wuZuMZejA
            FfFAbkMkYqPjOTm9tBf1h5EvgoZo77pEF9OiotygHlfjMC6GO643uQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV3BsRXlscFNlV08yM3Rw
            QUZON3lGR2Y3dHB4elBIa3FReXlBRzkxbURzCkEva0QxNnF4ckNlc2dvSnVCM0pY
            NkN1Z0ZwTFFXWi9Ob3FiOUQzSmcwV1kKLS0tIFNCeStoTWN1VTEzaG5CcEx0b0JQ
            ekpEY0N1V2graUpJRkRVQ1RKT01NdTQKsRZUTXQtWINmqM+YKTntQ5QZGHagd1vP
            zAS1+eB4RXoRqF5VCZselDxC9XB9DqKP7hbwU1RRHPTSEu0UENIS6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cThzRDNtUXhIajFZLzV5
            WHlkemlGenJ5b0N3VGFhVGRwbmFOWG1qQWxrClpHN0xaMHpaR0QvK1RxWVpwbkFP
            UlZnR1J4ZVB2emNwWFBmVVptVk1vZDgKLS0tIDhRdUc5STBzNTBZeHgrSlpOdFhw
            OFlxSnluTWZLWEc5VTV3RmRuZ09YL28K4o3oSjnwqzAZg20wy3ypiS2i7gqB83x7
            PqAuIfonkZLCUg/DiKon08L5m2I1uqceSFLEUrIjvR6cDr3kAji+pQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSDFjOWZ2RW52S1BJamVV
            VEk2UU5qckxmazB2VHBlMmh0TTgxbTFWNFRNCmdMNXV3WVc0SEJOalZNVWpXWU9r
            ZjlrcWVIcENuSy85dkNaTWM1Z1ZtSTAKLS0tIGVNVmJmdk5jUEc2MmEwVXJ3SjNt
            VEpWTkNXSGE2K2dMZUJMQVR1eEdONDAKuiO8qrXVAIUhYjtgctoijadXJjmNBzwA
            y1Jq5l/1uAH0st/rPo2RFhPYdmky9ZHuiDjxVMKFgT2uFX9BRtKEfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T13:01:23Z"
    mac: ENC[AES256_GCM,data:RA8At/JzS1YZfs71Tqd8VRt422AfPK3IEom38ZWWa94FGECPmTCGva/18F3qcH0QxkaAJeqhMu0My1bJ1SZiqsYNMnw6sye4kny5djuc6Lq3W2LytHxDkByljg05vO3FKohmAMXBdd58+yNewth9cRNEnZyzVLrhglDVgtkHjYk=,iv:7FuDx09m6DiWUSr9Vdpm6ayC7PNKqPElpjMVgpciYXs=,tag:RCP3dBw4q0b0ftPjuwtKcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
