apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-viz
spec:
  storageNamespace: linkerd
  targetNamespace: linkerd
  dependsOn:
    - name: linkerd-control-plane
  chart:
    spec:
      version: 2025.7.2
