apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:MYBN0DervIn03Brgi/qnrFWZi+09YDlMtOkXj6/WcX9vlgU43Q==,iv:A962iA3NxepsqKXH7uU/71Fmbfn9tImXXa9rFvRU6bY=,tag:npdPlaCINmBiwLR7b77VOQ==,type:comment]
    token: ENC[AES256_GCM,data:Y4kqf3p05Jn0,iv:ZyYDo0Vy8KkMFntuFt6XuUjD+6g29Yt+kvza9XsYl5A=,tag:RGLtH7qXAN0XNs1MR33HsA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOUJmSElVenBhQ2t5dUdE
            bXdRekhJRkJSb3FsNVpaUEJHVnY4Z3ZXVmxnCkdMbHV1dUhpbHZkQzJmVUhyUllQ
            eVovcWZiaW5XNVVyM1d4VTQ4TnI1MncKLS0tIEJZeFZ5WWkvaGpVS0lzUzM4d2RT
            UFZJdVlNOEFZd2YrTlZ3RmYxN3lXS2MKe/pLZdAeUc+TMkfyvrbYBxzdOsybQcDw
            UdLt9uUybzElFlRzrCp/bPlQesKMP+/dLHUWrZA+4k8KsviNHNxwMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3M2JCZ2RWczZJVzJUMGZL
            eE5sOVZwZVFWNGd6QTI0T2ZPMTl5SGNwT0RvCmxmNWdmWVpaQ1lPU3RESzlRMUlQ
            eG9kQ1BSdHNXYnREVXQ0QzVxUGswL0kKLS0tIGo1amdWQW9qSlBLMzlkaG5lTlcv
            VzYvZGtFVnREZTcxMlZjd0djTVlOZFkKU7z2lw1nFwS2XveTBmoAr5xNJIDpnk4y
            MeHG8DxIcKhVkQ/nqoNRd9WafRok9LPKFlX6IDI1NZOKMrH4OR1SSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbXRTYitwbEpmVk5lTG0y
            dDEyUVlEektiZCtmOTVvUDkweWhrYUJnaWtjCk9XYm1VQkUzZy95ODhIYjcxRk9E
            UWxxb2tIRWR2VnlYWnkzTW5QMC8zZ3MKLS0tIEJpaXVrR2lzaGpzSS9HQVlmRWU0
            YjduVGNzbm1rZXNjdXNUbkwydkVJZTgK9BSr6WJIcDluBIGt1OyuWPWZIfnDN9aT
            DfnsVHbk1jQUpCxILHbDIuTkZgfAiJvgFzOeya9RekGMKsMh2GcKfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWWxKZEZSWUQ0d2YwdFpp
            YmlGaHpwdDYrRXRhZVkyOTJ0VmQ4TGQ3MzNvCnZScm93bkhNUDRqMStPd3hxTWE1
            RnhENHFZYk5QOW5udDdsbVhGUDloKzQKLS0tIGlaRmw1b2xjVGIreVlUUTZONEo5
            RStDS0tYcXcyUkNhNGJRYmI5aG1BQ2MKe0v46o/AXeQkf1GRMqAiQIeOKZEkvIuE
            sX0+kFa3OlCL0jz7U6JbQ/gTjxgj4UEl6jIKgOKL8ItaePsX9s2Cog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T07:22:24Z"
    mac: ENC[AES256_GCM,data:6i8f0Nm69wsJ2SKk+VJry/aqEO1olHOYYeMN7teT1PmzxgWWH6ntdJiYgPIA1lTT4RthAxCSd/7wKF4szfHK86kjYjdZKRd02ljsf45PHdR/LrGLm5Y2fjNVj2gBpIgtvYLunsL4ayJ2lZhgpBw0ywhfYtPDqb02XNCcz0DnMcA=,iv:96TQAzB2wEZgEks6RVT/Q2LmPTxkCwciqUSywmetk48=,tag:Hw1F31CJVa2XDIs8ld42yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
