apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:CXJTanhOgkZQbMIm4d7qtIu8AWeP+38exZdqqetnXwUrF7yEGQ==,iv:QduBbOBTORt0FY90ozTfVO+/F/didMIpYR0BOln+HyQ=,tag:KVjpwbnNQY7dFY7vk4Xf2Q==,type:comment]
    token: ENC[AES256_GCM,data:W/WFgVBcFe24,iv:EUNdhjdgNIeQs4+pbAtUOh8CLyhtfWl/JParsd3Sur8=,tag:cC1kuXhHPldRN5R8ApTOSg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeUhWN20wZ3FFZDVrcUho
            U2Y4TDZBT2M5WE1KSWUxT2dLQ3VWblV4cGdjClFGMFVtK1V6VDVmUk1zckY5UER6
            TmZlWitsRWszWllQN0h2MVZ3ZVRNVTAKLS0tIE1Va1pVNG5DYyszZFRWNzl5blg3
            NExnMFU0c2p2cUF0L0xZMXhlTUF4MXcKp9jEJYHw8nE8vALqcYmPBUpAMBZ8T67N
            xSUx7Lo4n7bzmfIkEn+2F6qqfXztJqzoR6G/ffUECSkQDjEK25gCTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U3FIMlliY1A1R0EvQUlT
            QkwraTlpZkUvNnlqb00wOUhhY0l3eXFBR1M0CmRyekgvY3V1c096VzhmeHJ0UmJH
            aXNSWlI5dW10bzcrM3VBR05USTFuOE0KLS0tIERZRjhSNThNMUg4RS9EQU41dGpP
            WnQxVnBBbGtRM0hhZDQ2eU95bU95VWMKok3OA9StbK+NaKFxFYKHYz6tHZKe5bQe
            /j/SgZZkRFZfNNRW8CwhQ8qOQ4iWi+uNIJDOBXpBBHGWH0fdBrgi3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYVF2UXA3SE4wUHViemUv
            Wjk3ZWd1amN5NTdtWlYyTmpScHRzWFpJNVJFCmN6d2Zkb1pkRVREdzc4Nzl1UnVV
            TzZCY0NPVTVvdGpYY1BUN0Z2emtvMVkKLS0tIHRqTnpIZGxFcTJ1TUtKWTNHOTFr
            YzNnTkh0NEdESG4wVlp2ZC9Xd21VTFkKt6Qv2d0n32k9IaLFWRLhQYyGb3VDqep4
            LxFOi0/aRVgY1sY7gtED6oW/1ll1T2KaxtD4NEsYckSwrWDwYe40cQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0LytrL2lTYnhKczNlaElQ
            SXpCMC9Ha3FkWU5xRjBPQXBrVllOcm9qa1RZCjZBemhzVmoyV2R6b3UvL2VLdnhJ
            RjRWZWtXN01qMUJISlV2bXdmYmtYZEUKLS0tIDdMbHM0K1dPTXNVQzNmenYwUXlY
            NktrM0dtdCtsbVVsYjBkeGJTSVFSWkEK9v8uZCd68MRSpuFBJPA0ePnfCjWXHUSV
            x4w0rGrvsiDpIlOkDUCHmK8PH/JPZu16FcXEk/hfy0QTTfIZeo4NpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T06:06:52Z"
    mac: ENC[AES256_GCM,data:ERTTWPhlAzbYuKU43BipHKwtceGUlJ3LM/r7AAptsnys4WcFVU8F5OWlGBJg9jipHwYa62HYPzu68uZITFOahNqbX97y0Gcl3FNtxKW1RUIKI9QybFbZjRK5nDCKScaynoPaN6BlHB/u5FtJwMZIv9Zz+3nQTZY2ln9wOU1SiVc=,iv:Ega5ZeCPHiXxsr3aBS2l6q3OanECu9YaYVeG56+CcWc=,tag:0DtID8VheNcbKqMg3xgN3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
