apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:7vczA//tMJtO5tysGmMMeJCkUBiKxaxoC5JRyxzbUwkHbCET4w==,iv:2LYg4X5BC7ojzHq7URf4tmEVSrR3DQ7FA9wiKxEGoXY=,tag:gCH9iTPif0Qdy9lTnp1HhA==,type:comment]
    token: ENC[AES256_GCM,data:2CCaCrjEddmI,iv:nRhCqFycRGCcx9bhPts7YAV/LS7TGMDL5lJb+eVpHnE=,tag:yDopaQ31Ekcsg/hSR5UypA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcEkrNnpnVTduQTBsWFZQ
            dUUyNEhhRVVaTExIQ01ma25GS1cvUnIrNFZRCm9WbUQvTFd5T1RzbkZBZFh6QXFm
            TEhURU1HOGpkTHEra1BxUjBpUFRNMkUKLS0tIGVPQUZpVnpQNk8wY1pFVkRoajZn
            NUZqWk81WXhzdVRRZXFrUENRbWRuVzQK5Y3TsXHmW7LUHgd7/rLEF28boUs8Wo9C
            KIMc30Dft6naqenGDkoqVvVbgVuuyoIWoBiPeu2+bWVfpCRvfb/7CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVHJRelJUV0FMcUxaTGRp
            em9HVHVsYnpQeXY5dmFLeDRkb2dzVTNVcURrCnNpQk9waUVlRXgrR0Z2b1lVOHk5
            VjVVd0xyZjZRdjFEMXcvY0tYQjhwcHMKLS0tIHJyYURxWWdhVkRsb1Z2c3ZBRzIx
            bXl3ZUdIL3ZMdmQzb25IL2lPdTlKeFkKWGVzyy9fdj9JlxOETvBDOPkkwUHvewCG
            EaIVkLV+c/ORXDrMc8zwLaPtXpoHZsvgY5XySrScHMSwFbbPXk0I6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZHpvV1NnY3kya0VkRVZP
            L2hTRldUTUdtczlURmpTeW5VUXh5V0RmVjJ3CkxBSTNndmxtenhUcGRWQVdGMHBH
            cVhnQ0thRko0R1JXUloxa1BvWEZJK28KLS0tIGNLZlE1Mm4vZlJVSGhPS0czNFVN
            TFBNWVhQV3RmQnVndFdxM0lObWJOWkkKx6JbHDbDaUnU/2L9eARpXUKJYD8LZBdP
            KLuyfaiD7jo8Lb4DDLXb9dHy7Pnet8AXKpNovNfhP876DFC6Wf42Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSjBJSDB1clpvVHovblo4
            dW9mc0RJRWJGOGdEc1RyYUwxajZ1ZFlWbDJzCjRHR3J3WThyYVpkUmdmbzhJanRt
            KzlJcHNPUDhBVmhHTENNbXZyVlhaUUEKLS0tIHFPYW5PYThVRzAydjk1UGplaWZj
            NjJieDhiMk81NkowZ1prMzlYWDk4NDgKhkFelpbo4wAI1iUkdebe+jxcYFbT1I3o
            Gkl/0GeaXJU9nqLUxbFn05AeyO06/qa0onAGtQNf9BbrrMh3gRkPLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T06:28:46Z"
    mac: ENC[AES256_GCM,data:rPuEP3Ry0vDIitBCBUQWiaxDqkbV5CswA5cro/YsWsuWwJ+1AHZP8Eh3k1u0YX0owPVzLLpvscUTnNjM0H9b4V3eFRSTh7Gxcb7RmA2bVSchRJHZnLnzUnVPYrWNOW2KtImyc0G+tcfQ1i7Ezeu3taJ+uuKQqNYypo2mryiCgLk=,iv:8TKFyZRRhNnJ6x36IAbigp41z0XIIfSRME3tbY5ngMQ=,tag:uXVO2rWAHXiKA8gkq+IidA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
