apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:ELTqf3EMekJS/yI7+ME2tLweHGJ+fC0f1CppUj0chsLDpjxEfw==,iv:/za/0NuYIi5CqrTUMsmBhof5fxOVUljJ/W9kObprLIU=,tag:viSjhpyqbBtqZeO1sXRhtQ==,type:comment]
    token: ENC[AES256_GCM,data:cCfA0y5aBdVs,iv:wahA+P+sZTgAYeQ4Lzeb0CgFZaOHoJxjPfQyxwzYFGc=,tag:A5Kokuhp4AorfKt/j/dQtQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUUFBQUF6eVF1YkZDZnh1
            MDh0SEFoWnZUcjlSUzYvQ2RaZkFpQjRLdVJNCkhpYjNWZGNXdjdiNmh1L0VkYTZD
            SGtXWG9uS1F5QkJKL3VKWkNFRWdVSDAKLS0tIFZhYlF2Z1J1WnpXMUFKNktzaFlE
            V1dQSG80RDZMcFVwQS9iaWdCbG5zUlkKEtWyZunwmpJdbUD46PZj3WSuS+CSbfXu
            5yBjMbaE7hzwIigCjQTzg6LEqB4h7RRxujk7bPilCg/3KmJ7TYub0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NEFkWVNTeXdmV2kwV1pF
            NVdGSkZ1Q2x3S3ZyUDlmN25NSkJhZjZHbzJ3CnlZd1lkWGNJQVh3OTNabHVWTEtS
            NCs5aElJOEZWd1BaZTgvZlM5T3phTFUKLS0tIFpXQlIrdFZ0eG04VFhxWjBwRzhZ
            NTlZcXkxWWhES2l5QWdJMllEejlYKzAKh44DaOqydaoLpknTVeJUD+NX9MWgiRmI
            8n3RzBJ9Bti9YO6YOA78qbcN+LpGpWAB9QeGC/+683HCLyHm5MQseA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaURmaEZ5V3BtUXpxV1Bu
            MHcwU2dZYjJuckJpWlpQRFFQenI5RDV4QzFzCnhZcXNrQ3E0a1FiVHR5aEVGMGdD
            WU51ZkpTUEZtcDRuTTVtS2kxdy9KOGsKLS0tIFJGT0QxeDk1QWhaMW1IQTh3aVor
            SFhVdlprN090S3JIWlFRRUluU1RHNWcKZepCZxFcKyOxW7wqtOkpZZ1q2jQUykTU
            l0IqZVTBCUAmlBuYQULnYAxX8lLWuUHwFJHaqmjxl0ZW5CqTKSdbvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T10:51:47Z"
    mac: ENC[AES256_GCM,data:FJWxZYLD186HDXcGepsWqEokPh4CwzGce8dkF/ewK32XYvb9VEXujpQJ963vLN+0+5GQLAkjG+4YUB8sSe24HgZJfpBzcP+YxUFtG7OauNwg1G1n+2d7Q1+Jhcvz3KRs8r20Fn2fjfWiaBdWy7xojPuj9bS0z44nh/+s+RXovg8=,iv:9H6lLJ85E/gOvEvMr/wi7xB07UwguAQwU5jPWPHErfo=,tag:aAsfTHL9pylGvIJ2P6rbMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
