apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:SaISUmXSCFNoTnre2xLibT4IVXk73pvXakW1GLkE3zXfEh2JeQ==,iv:TR9cxEao0+SXIfBk2poFsP63inD19X5l9gkL4KSNISE=,tag:jDoaAs/rGrvT4iPSt4CXvA==,type:comment]
    token: ENC[AES256_GCM,data:sP/oWigptrGQ,iv:PDI211p+Z8kOpXbaU19aZQyU2PKsVMRDU2ipA2bAYtg=,tag:rKa7EYisq1+h2+qBmao1lQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMmNFUDBHMklGckhjNlpo
            WFl2S1dPdHliUmMrOHgxUlZZOG1EQTVTdVNvCkhqWElIZXNSUW9VTmI2TGRoUCtV
            SFlXNUs1bE9mbVdHZU1xKy9vTnBYYXMKLS0tIGtTQUtKc3h1Y1YxaXdla3MwOXRo
            aS9XNDhvcS8xYTFmWW4zSTFCcHNaTUkKu6Np3HAyrVC/r9A1o4x6ar3JxjlNWw6M
            BbkDAGFtBZGAVUbR4sqywFVj8AzyU3pUaEnlilEdy5cIdeqs76MWcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y2lIODY0QkRDTHI5Z0or
            ZXRSUW9SOExmMTV6ZDBQajRmekxnMHBuZHdnCkxTTGxBb0JtL3VEYzd2Y2JSRU05
            MnpqV0FKT3Zxd1VUVCtuZGRkZXg5MG8KLS0tIE8wWjJFeFF3L25TVW1ZNGE3QkdP
            K2F4VUhxM09IclYyaStaWmJlQnAvVDgKms/twE1oD+PMIU0QnZJ5CR9JwqvbmBWY
            46wja8wCIRBtJ6SaeH0CzVs/EkeVVuL/3c9x8QAmJPRZwgahvuNnwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeTlLU0kxdmp2MWcrdnUv
            Q1lzOVk1bmk0WTM0Q2ZZbmRqaFdNbVJwcUFZCkNmNWFSRVVQTUZRODdPVEZzRWpn
            elM5YkdldllrSGR3WCsyb25GcXgxWmcKLS0tIEtrVEU2SVRRV1hwUXJHeldxanBF
            TXZoQ2RWVnN0SHZZU2JpNnE3UTlBQlEK3M6DRj58Ipm4gaO32MaAtrPTml9lH9jS
            KYNX1//sN/Qx00lCCrOpQYsOJlzXqT1t4C16ghhPj3+LK0eHM8RBaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN2pFMkpTMUI1SkluOEx0
            NExmZHByTGdlcTRhY0NxdExHUVNWRVhxcFU4CmtCMEF5NGR5dCs2TzU3WURXQlZX
            Q3VwRTVUdWdhWjM1RjhRQVJVbXp4d0UKLS0tIFdzMEIyMkdlY0w0QzNqZng0WXJj
            L0VIOFhwMkp2ZE1RYVJYdGVpNnU1WDQKSTHGWQfcQFM5S04vxOGleV8g9NemMUQd
            NQmeA4f+43eekSU/1nmcGAp52aC75J8y+7yV7+Ii2SakKmzSeJyy/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T11:38:39Z"
    mac: ENC[AES256_GCM,data:NuZoLosjbYSitsYJV2hG0BWTUHBxNi9iQUuF50yLlg3Y/c3GMRpt9s8NjSIhmq8M9yfgWqUexZjSKi+M9q72+8/bMcOsIuRfWSqZ2w4zjm+NhYL8e4nI9pRJu1T9Ocdqq8Py06TrScY4BAIdiUBBw88+Q/rvxj/zipXsYNCi8ls=,iv:eQgIp4BYOwCIcDWROaDN69fyd6zbr9PcQ/3IG7e4vEI=,tag:ExTFSeO+tEefjgKruj009w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
