apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:l3WMq3YSdVajgQ237UPcHmpIVknT2AvxZ3iWrmLKdICcayOQbg==,iv:rjGoCfnFqqpwkNtXlgd5bF1blyGtqOdauz54vAuDJVI=,tag:ZGbWe4JySTdobXQD1TL8Eg==,type:comment]
    token: ENC[AES256_GCM,data:5H3Wbv7pkYvO,iv:pLdLXOys4yQAO0d2//vy72U/p1ki7Aev6wbZjBvJ/pI=,tag:FQEdR3vz97XbPKTRM3zbhA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc3k1OU1Sb3VERXB2OExj
            Q3RQR0FCSG1YeGNuM0RLY0VDMWo3OVB4NlY4CnUzaUZOWXhyMUd4UnBSbVp4RVdD
            WDg0U25DVkh5RVpBSThRY2JsSytuLzAKLS0tIHRMdW9tcUV3MktmZUpVZmJ6SnhL
            V1JRTFJhOWxyL3lYTGdrbFM2Rkh6c1EK7/geEBtc7OBX16riLe8nE4xtQUVQYSB8
            n6UL+dqkWuFWjlqwpJjStxs9K+zaKkdLboXFzchFZtD1pA8xVF4Atw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQTRxWlhvQ1NHcGRVQ09x
            ZHVMK0VjWmZvUHJ4c3JSRjJjUWNCSTNya2tJCkZPVnU5QlZWeWZnTEFRa0JoZTRh
            bElxU2lTdFNubkIwd2kzTDVTQUdpTk0KLS0tIHRNSnNNbElpUWJ1ZmgzSTN5Ukcz
            eHM0RkZEQkdQSUxnMytaN05TdFNKUUUKH3O2+958ukT02Moym2o+qoITP+EMCkKc
            U1SitS4yXbefu4mdT7Cq+cyd15QvK61qcMiGsfHYeBzhQS9PfDtACA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUFJ4bU10RFVwYmVTUThj
            ZlBscENLM3lnRGJoYnN1bkplRkRjQms4Sno0CmtXdDQrTzM4YlBydlRuVWtqUDIy
            V3YvWEFQS3JBYUhkZ0xYUTE3MUROQWcKLS0tIHFyT0ZEbFo1RXByU2VJUzdDaXJK
            MFA2OW1JOW9nVUlaS0lWUllMUlBSYlkKnL84GL9CFdFWsZcEAtsKiVvBB2YmLKpX
            HkOtSzYmcpQTU4ctH0WNWeUK4Cgwgyxs4MJ+n7VhdXGNYYoJP+CF4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TFk4SEZHeWJaOWltWDMr
            VVBhbXVOMEFwRlFubzJRYkFIaEd2ZEUzOGhrCmttcGJNeHFyUmZzQ0VqR2V1SWt1
            NmgxOFI5YjhSN2Q4TnVuaWdmY2JXUG8KLS0tIDU3eFpsbW43Rnp3cUloM2xrdlUx
            d3l1MFg5RFlvQyt0Q25ncm5PQlZ5TE0K+3JieizqPInZ+X18vTyPTp4/cDCpDfL0
            AfVcJEK+ax89HET7c/Q86EIlyP4s5VGh+UpZZuU3isDXyPweXkhdkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T06:46:42Z"
    mac: ENC[AES256_GCM,data:33Vqtf1EnmNJf8TV3kr8Y2jYixxFgxEHirq8swybwMdWKDTXOK5fkS/2kE4mDh+Yqt2v6AV66LSIDucKW6q7RLGeI2yFKFZTvzehs8CiuDXoexUXQIasQxdhV1KggLaRuw5cAU5z9Nh8JV04C91uIQtBOiXWUS9TprNrnsEqHg4=,iv:LT+YbrH286MfJ07Fmvccg6LmDgZp1SuI6fCOxDaiyPI=,tag:8YsBAPastN39TNd53ziO8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
