apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:Dgn8HrHJfHgSQ9UjDXKa2kOfzfNmMtH4gS0GNmkpyZJpxkqm3g==,iv:dUz85dnSi30fV+OBngezIDmYRvbmlGEBJ9ST5aN+Mc4=,tag:r/kILKmdW75tWGe2vv+I/Q==,type:comment]
    token: ENC[AES256_GCM,data:rSDIiAHuhFaA,iv:AiLPv7KJnHsEG2nZsOtNloM3r5lOv6h0QKFP8HHSZ3w=,tag:5101MB7Nr3mazD4WEj1sRg==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV0JwdDgvZ3FDSmZ5bjZ6
            T3RtVlcyd1RvalE4VjJuL3RuTHpicXVIT0g4ClRaVzI2bUpxN2k5TXFoUUZ0cWpB
            cVpFOWhHOGpZRDJsRC93OUdBU3FYclkKLS0tIHRvU3I4dXI0MFQ1VC9rLzlMVVZN
            eDJ0eFJObkpzdk14dDNJRzZvcG9CaHMKbU2w3YrmAvF+yxGtvPjSyuWTx3eeoePN
            KWIbwfy1b3OYKoP+z3iA+ERa5TKaZPSAstIM8NTI4YldJFqAtS1BOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T07:10:27Z"
    mac: ENC[AES256_GCM,data:NDqlOZcjaqjCcOIqHbAFQHAodueDSb87N4xwmJrulqbp8jYK9PROIsIHDLjfoysmLgcZ/kbuwCVN2n4BOpe5qO1iaO+3aNDax1n/g3n9W1nZLP6dsSIc20ZL06GzV7IRCoOG/guR81XdA6Y9bKIVthDV2/kUeqmUr57Kc4FtzJE=,iv:ntcNezI+1DZ7kq5WwyfGa/BnptFCSrGO+UE4l7QE0EU=,tag:+yYwE6SBhR2MYXd4QTzQ6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
