apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:zgQBCAwVEub3xS8wjda397NXhJiJXGCCwPHzJ+DG2jNiJ9oCSw==,iv:ItzURVP6qYpYxcoDSvC4wrVyj2runELf8A0mPTEwGiA=,tag:H3VBh5Hl1IVIjk3bCs5OZg==,type:comment]
    token: ENC[AES256_GCM,data:fVc8DnX+JPpK,iv:jkJ+advpqVPJ9MjttL8k1Ij6h5RFv0yBLeMJhlzqS/A=,tag:+8uBFaiVM/FvoQBKQj9yJQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ3dPbmZMODY1SlErYmRX
            blFSWlYzbTJ6cGx5VmduanV6bm45NHZOR3dVClN6a2MzLzh0cUNTbFMvYVZqWUls
            S0JPSXl3MXVmeTZWQ1BhL0VYYmllRGsKLS0tIE9iUW81UGdQdlIwcDVCRWE0SUtw
            OFpod1JvU0R3Q1BueTVWTldId2xDbU0K0RRhu0bamASvk8OjsXEFh0tCFjbtDnA8
            7S+UoGCbb3ugc9OH07gnojHLYzKDbxacMiqFskUaR5I43YW0KDaZBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMGJIekRnWE5wU010Qkcw
            cWZjSjBPWUpBaHBFZXhBNnUwNGwxYndNcG5rCllZZmt5NEVxdkVBbmJLVzgvOHkr
            VjhLalJodVhSOVVpY056YnltVzY5aHcKLS0tIFRlUGJiSGJ3SVFkSVc2TEhmbmo3
            TGFxSW0xck1wZHFSVXd0cTZWb1FINGcKGdXr9cM8Qgh2L5n1jhzrXyC/RAGkdGJM
            24zwKoYAqP0UFEs8NS/yx6AJYb/alIv8tBRwlN3VJFv5tvAk1ZNC4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNldES2N4TWpRWnBsQjc4
            Q1N0WWx3V1AwSmQyQXhPYWFsRk1FYVhkbTNjCkJOZXF6akI4ZEQxVmdORjAveTZT
            VS9ueCtPZ3ZYMjZONTQ3QWxiOGpPTFUKLS0tIHExWHVXS0NuZEpoRTRVVThJajFl
            M2c0a3Q4R0wxZGFqOWxnSzlXbS9Uc28KhHemlIZxxT/Jum2+pTPucxUVC6ptTaRG
            +vLr1BjmYKRMWJM+QurtbaBb67n9OEY8Zdi/aliZqzmkvQE9NBKRMQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByKzZrNFNSZVBTTkoyK3VB
            VVRhbWVlTE9yVlRJalRHalEzSytMb1pJY200ClBWMzMweDZUK1hCdmFGMERsM0pC
            UTh1WEVmN0hnaFpvSFhUMTBidzh5ZVkKLS0tIHZEbnA4SWV0S0xuMFkydE95ZjEx
            TkxodnBnZzAyeS9qYVRPaXRKQ2xZak0K899nTCkEoZiIyQSzNDurrsOQPHXByJ9P
            UxxNgfQJDe3f5xFOsmFkMETgGeF5+WhFcbTqLDhRo7jP+qZLFm4QLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T12:39:51Z"
    mac: ENC[AES256_GCM,data:S1p8dtpnTXGIGAIv/yjk1bp0xPT5To2Y21XBTrFygLTibq8o4Ls+onY8BxtiAikeEB86bnnlAvE3fpEVfyJIFXUy12/520DzAL8dzGmZMW35VGZBn/WQtxBhIdv5bN/FYgq8vFQ411jI1kvMhoF+G1+PehryYroXfa0v/gKKLcI=,iv:NZE3CPw63Y9dK3lx9QyyYIcKoDpPIDsNy49pa+S++H8=,tag:Zt7F1NzqK+amaznVLEe2JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
