apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:r/2SNWsYyXA+xEpAScVveyXREyTUV91yWNSUAmvasZIMMmscYA==,iv:2Fs6jCpmM52PDf27BqkyQsNPRI0vjjXyFky0lcvr5XY=,tag:BiCc/o9nw8WyVuO7Lm8Vww==,type:comment]
    token: ENC[AES256_GCM,data:7zmkjWgiovYr,iv:IT7wo2zmsiAY4W8UfDqHIDOGOWG8geHBhUvCaf0W+3Q=,tag:9VGCWHkYmAHiwXwzSNPqAQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML1BWWnhwL0VId1haY2xY
            cldLZFIwR2JqL1VaV3M0MDBjM3FVN2xVMWdjCkFuUmt0L1pBUytsM25ZTG43QURt
            K2F4bUNmVTU1VUJNYndxd1RlRWdmeGMKLS0tIHI0N3E5aVN0MmpreGptK3JGMDY1
            MzBLK1ZYeUJlcktvMW0raml6T25qajAKlV2EV/aVXDs69LWren3ueltx7jthCGkM
            kczApkNw5oK5MtksL/iK1a70+Lo1KlqdMDYKwc97Xa1tYB0VDLBavw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGpmY3pQZXpSbUdPRjMv
            SG0xTmxyRnFlMlFFczJMMFE5b1BidUZqSmtRCkVsWndkRjc0aHora2RLdkw1dEp5
            S0hubGUwRTdMY0MxL1RCUG8yNVcxTHcKLS0tIENlc2oxSk90cDI4SVZZaStZSHJY
            cUo4MHZQQmtyaVpRcWE5eGZQSVBUNDAKXE+x9YC1ElnoQWlTkRQq9eceibpvbMZ0
            seXdlJt2pOG/cc5WwV2CmGrWkmNtAJI32347qF139oXrFAsA2tafEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVjlYTTROd3pnT3BtNlhN
            QWZzWFc1cVpCaEtxOFpNd1dXUHN5NGhVZG5FCmVMdWVGRm5NeFljRlBwL3FaNjdm
            ZnRmNDRHQ3VaakFhWFBiQ2thbFVFS0UKLS0tIE1mcFNFYzM0cnBOY085TDRKTVh6
            OEx4R1FPNVNoWW1Da0l0NW1Md0d2NUEKtFvSVuUxeMcUyxJKWAJeLK5a7X+zupe1
            I6mMqG1vEw8ygEpaZC0HbyTF143SjcT8jnwv3Yn3pR7O/Bu26apeag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRnIyZGZTbk5BTEJGeVEw
            a29rTUdMdVdlREdBUVRXMFlIRHF2eXBaWXdvCnpTeG9JWVRMZWloM0RLZ3M4T3dm
            VVRtZXBCY2xmTmJQa2dVN01YVHNKYUUKLS0tIHp1dldLU3piRjVOV2JwTjlPbWNz
            UE9wVjRKdi9zc1MrbnBEb0JtcFg0OWcKo4tIf3aZftRof0lzxO7QVjNflbcgd6rf
            KBVtIVhIumxa55pf+ZYAfqDtD6g0mG3bbhkw7XzKI6qN67As2jW8uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T07:49:10Z"
    mac: ENC[AES256_GCM,data:lmgzuJRvZB4cL/Jl3zklnUHPQUIJq4jsnJO4vUmeEqxtLp+rUvZl1Z/A6CU4HSrW8vdqjqXq+pe5uf4Fxbn6ATfBc7DSJQiPEM5b9I+McqawSUFJ/5Ul19cXyyvACL2CPoJLecLQW2WbPmzTVJ6mLJG+K5i0q4fowyD8XnHU+W0=,iv:CGV/QNGPTriyJBEH9qbaLitgXuxkeRN8J9lbqU1Nrtw=,tag:n7SasHD2Sv9yBXyY40yMwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
