apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:lYGyeBtENvD7IfNoxqmk9jj+9a3mykRHd8V+wxi4GvwtldekCQ==,iv:nckWTetXW+ZBnAOUZ7F3NvWKQ8Y1yl5REit74N4OLHU=,tag:Ryh+7T6S+DMG1cWR/P81Zw==,type:comment]
    token: ENC[AES256_GCM,data:lcUH0CIkGTum,iv:hnfeXpx+o4tVGgQRu6qW+tPZHNODeIwZZz2/xemsrwM=,tag:8iFo0G4HapU0zZsUIIUYDA==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMDBCeWFoMENvdHE0dHpS
            NkY2L2FMc0hhU09Ob3MxeEprZHpJMGwyVVJJCjVKeExNUTJDMnZpQjlUbG5Ickhw
            RkI2ZlNMMTdUZ1BOZEI1M015U0luOG8KLS0tIEtHWForTjNTVVlzVERJaHllblh1
            RE5jZnBOeWI4VWV3REZXV0pDRzFqdkkKIMwb4+EUWcjLB5H1IcQunss0DbM77+q1
            4gHphLHM6a6dUilgHdvNDH/JRE34MSW7hd0TTkSZpInQvosRq1cuwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVjllQlBWaFA0aDU2bGhD
            WmFieGpzc0pYbVJWV2RMTHdPdG5ZU2FGRzI4CjV4L0lZSTNvTjN6TWw0MHR3dU5k
            emhGYkxKS1Z4Qis2SmpLb0JSaFBtSGsKLS0tIHBFL3ZDYmN3QlZZNVdOZzFRUUdK
            Y0FyeE5acEtqMkFseXp1eHZ6QlNFeTgKXTrtRNkV/2ZrPHS/yOctJr4LOy1yU0mD
            ViWIMTQnSqNjgo9YXtV8CW+EwYv3S0zkio7UiKKm6H8+59CuQZm81Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Sk43UnZxRTAzK2J4Ly9x
            SllyMWJkQmtTcXp2S2RoU2p0eDlzbUQ2cmtnClFSSmE2WXdkZ2liRVMwanVkalFj
            V3BTQzA3aUJ6WWpVbnBGM2xnckNXcWsKLS0tIDI1TW5SSXNxY2I3S2ZobTVFbGV4
            LzI5Nm5EeTFSZ2QrdVBOVGZIMEJjM0EKnr9+SzNtPCKNOfnIuakTT9FCPht7uP9Z
            pKV2IZV8DYoWaHtOm3AUYN9Z+rdH/G0t0ZTjXXDjgrMuCxNlPu6WxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTVBnUnMyWU54YTZReHIw
            bHpDVDREanNSeFFsRVVnaUVlOEFKKzBrSzFvCngwTUhVR0ZoS1ljL2lySlBMS3p5
            QXBuTldCOXJHRjNMa0ZGRVVHMVd3TnMKLS0tIFNHbXhWZit6U0pmWHZPSWFjUW5I
            TTJKSUVaNld5aE5STktpY1J3OU53dFkKBdQ0rponh4NMK7FXDBtCteBpuORihDdf
            p9ItpcG0D6jhQcu7gkqOgDTVjmTL/6toz7H9exqgEVWRpY54BdNGGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T07:46:15Z"
    mac: ENC[AES256_GCM,data:9VTFfERf+9jG02TDLrA/5hduZ/ybee+XBx8LYIqUKCZdVnbnK3kP5nh/LUG+CiLMaEly2IwvjYdgdlOMYwMn4vJP4mHTs/loa+cDTNrPYjIwD2CaGpZFFqjY1gOhb43i6KdHycInnNdRFS/I6igFs+qS8kCYq2Tqojmxg+OFOfg=,iv:W1a+S8/l5LodoHokWDtXMZcqvhvwhcj/Ah7SUs0bTy0=,tag:D31gEUOq7hlPS64C1H+4Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
