apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret-enviroment
    namespace: default
    labels:
        app.kubernetes.io/managed-by: sops
stringData:
    #ENC[AES256_GCM,data:5E0zRle0GcKwUWNNkP3OdgUSd0QIqQAJ+XWn7I/U3nVaSSehbw==,iv:ft/Hi9znwXs29lU1/5Pw0JQiunMH2HgVyHtpT4QBMVs=,tag:W4FT7mFED8atCpYGlnmufg==,type:comment]
    token: ENC[AES256_GCM,data:9METm/eRI7Db,iv:DrBW8D0DUIGuoWN6M3jm6Sp//bz88XyWe6aLrE9jGw4=,tag:d4NrR/17utSNB8PmcZo9pw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcUtXS212SHhVK296bXMx
            bmVBa1VFWG5HMUNxVkg2aHBFSmJOUUowR2hFCkdIV2xlT1kveENDdUFGSDR6MGxi
            Skp3dS9qQkxvNjlpR1hucjVaQ2c1YkUKLS0tIFFMcE5semhaNEFsbjhOb2dGTkFX
            cWZGWTdpdGE2VHk4ckRISVdldy9qRFUKcq3Q//F5H0KuyTA6+407xj1EfPWR5wFa
            +2r+JkE+zjcpHILCR8YSudXp+iSLRTYMkuvZHpJ6QsPWP/vz74A/qQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ1RrcUhvc2FMOWlxT21z
            U3p3eWpnZ3p2Q2I3NVVJMEIrVWtsSkk0QVhvCmRQR3ZmSHRvQVRReVNGblN6YjBn
            Y3QrK1BTK0ZnYmU1U285ckx5Z0YvQW8KLS0tIDJLTm0rOFJDSWhkdjZrYmJpL3ZG
            aG04VHJEYTJVSnl5d29ET3BYcjQ4MmsKpwoS0KZSreNhnRtz27FdJhaeLpJxTGat
            uu18zfBWkk1nCrwiA+WhMZ34vWVsZj6GFINlOp1b+h46QdANFPQF6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbERJU2Z3MXJRWHJCZU5m
            Nmc5OC8xT3VqM3lCd0l1R2xLemJhTU1DYkE4Cml4b3JacFNKSXVMVEFHb2RSRUts
            WTB2cW9mVVlHdk5UbFBlV2ZBZU9QVVUKLS0tIFFsVTk1QTUyRDNlSkNVbkpJaDdu
            ZmthYjlYTXBtdS9SSDJkWEZYdk9SaUUK1BqRLNJZpJz0Qec6ciaaWgFwgFBsOfIA
            pvFXXf8RvstbP+kwiOwE+R78BAnGXTsLMkK5zX5TN/tciz+JEUlD0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SVo4MlUrL2U0UHdMdUQ5
            R1lSeUs3ekNkMkFaV3hZYjdXdWVKZ0xlTm5NCkt5TTBQZDh4NzUwWVhHcWtYeDhm
            VXJuVkFFWDZwQWp5cU9oYkIxWkxoaGMKLS0tIG5GMlRuOG1tbk9zQkFsa0VBbkNv
            WGxoQStidjFBRmZhMHB6Q0hacXRULzAKOo8+Yv/U8PPQmWN3NCNCJXr1OWtM+r76
            30EK9PFkT8QkfWv+19lGJ4xgVCBzG5vO9XYfDiDmT1t2r3eFQrK6iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T07:34:04Z"
    mac: ENC[AES256_GCM,data:kYHBs2Q3O84Ag+yb//GOhw+GatPyR6+Br2IEnNziqdgwsDXZ1s182bPFGm4uuL1IdOiPaYZTkgmyWoEAemHOMkKjwAj7a4PghfFxgAngV9Q4RzDbJmlRuCiJ4dAmrW5d7OMfli9wiceFGcarb/KjubLjyrVJ7I1fLU2IJlml3IA=,iv:Z0tMQ0eZ3dSQuyts2eXaWgsW2Zs1NqApBstSdmN46hQ=,tag:/4Rh8MdfhZWkATg2JsPZMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
