apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: network-routing-system-base-post-release-values
    files:
      - ./resources/ingress-gateway.yaml
      - ./resources/ingress-certificate-gateway.yaml
