apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: network-routing-system
spec:
  interval: 1m
  releaseName: network-routing-system
  chart:
    spec:
      chart: ./tools/charts/generic
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: -1
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: true
  valuesFrom:
    # !! The sequence is important !!
    # Always first **base** and **overlay** (if necessary) later.
    ## base
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: echoserver-certificate-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: echoserver-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-certificate-config.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-config.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: gateway-class-ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: gateway-class-ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: service-envoy-proxy-ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: service-envoy-proxy-ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: registry-certificate-grpc-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: registry-grpc-route.yaml
