apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../base/envoy-gateway/extauthz/release
patches:
  - path: release-values.yaml
  - path: source-values.yaml
