apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: extauthz
spec:
  storageNamespace: envoy-gateway-system
  targetNamespace: envoy-gateway-system
  dependsOn:
    - name: extauthz--pre-release
  values:
    image:
      tag: v0.13.0
      digest: sha256:b369229b806b822787ed7ff3e9ed832f797377a84b47d99c5d37ddf40a66264f
    hpa:
      minReplicas: 1
