apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: keycloak-base-values
    files:
      - ./resources/deployment-postgres.yaml
      - ./resources/service-keycloak-discovery.yaml
      - ./resources/service-keycloak.yaml
      - ./resources/service-postgres.yaml
      - ./resources/statefulset-keycloak.yaml
