apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kms-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/production/workers/gc-cmk-p-glob/kms-system/
  prune: true
  wait: true
  force: true
  timeout: 5m0s
  dependsOn:
    - name: external-secret
    - name: namespaces
