apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
spec:
  force: true
  interval: 10m
  path: ./apps/canary/workers/gc-cmk-p-glob/namespaces/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m
  wait: true
  kubeConfig:
    secretRef:
      name: kubeconfig
