apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
spec:
  chart:
    spec:
      version: 2025.4.2
  storageNamespace: linkerd
  targetNamespace: linkerd
  values:
    controllerReplicas: 3
