apiVersion: v1
kind: Secret
metadata:
    name: krypton-secret
    namespace: services
type: Opaque
stringData:
    root-key: ENC[AES256_GCM,data:829spB9+dTlkCPZdbfsj4KQf/bHFLLrcYhDTjdOUNsr+/59G,iv:/Yh5IRuJAg3VcbFnnHFXZ5p9yAYmfd2c8vfuUBixWN4=,tag:egUeGL5OozBCpMwlxPMQtw==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc3NjbmxVMWUwS0FhcXJp
            U0R0ODVQUGlRZVgrejhmaklRQmFSYTk5QUNNCkNvWmJwYjd4bTRCN2hQMnBrYlZl
            ak5XVmY2bW0yZEluQ25rUVh1ckhyQUUKLS0tIHZQeDVzb3N5SHJ2OGhPSjZTUU5k
            c3RSTEhqaUhCcit5MEh0OS9CcmpEd1kKkG34NKny9l38wfKPjLTTvfXT13p5hXyx
            n1vt89UqqVl2qLdKvg2Lt3VzwnQwGFBkBbop+tJlJuALaK/Doe8lkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUGl5c3YvN0dLNTRoLzlv
            aXpUV3QyOGdqQTZ3Vy90SUVuSGVCQ1lJZlZVCmRpSjZ2djBKcW00amNIM2JJeWVT
            RERwZm5VYjJRaU9KcTZkT3BTMmJrc1UKLS0tIGp2U1gydzg4OHZBYzR1ZEtaTXUv
            N092eXk5am5JNGxwSk5YOHNaS1VUMlUKpby40ZZyV8Sl484HU6rknSm01wbXRa9r
            PRbvcm5UqxAhLItgGUrFg9b/hXaFboR9HF5juIsydgn0dzhVGzdvEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMlVaQVVYc2N0Wk9KenpN
            ZlVyOVZ4aUl6RTNGMjUyeWt6WTZFRDA1M25FCllROWRmMHZSUU4vVkwrZndFbi9Y
            bmFCTkxMWTFQYS9GU1NycmI3bUl3UE0KLS0tIFpFZEpTVHpTSDdWdHNtVkVva0py
            YTcvRmxtS2VIL1AyRnFFNEIrTFBOWHMKyH9FR9nWdw9l73fgw2+szVMYUomcSrCr
            fSnPRslE8O7oX8A9vGtNTmVzTQniZYt/R5PrQGuskd2Z3mYeT63Yvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNTl5VjB4WEFxWEU4YTAz
            eUFqREJWcUVvRnhjTmhhL2RPeEZ1ZU1jV0JBCkR1c3Bxa2dtcW5jY3Z0S2ZpSjM2
            YnFtSmxsN056TjFqOWFaMzE4WWczNTAKLS0tIFdIc2ZNWEhQNjEzc0ZMUWRKTFdW
            WmhMaWhiRXFjVFVKei9ZQ2U5NUpBQTgKxph10bZrSzZ2q2/0KigKUI3vEnZQhFGK
            j8CyX6ByoGVZF7kKSsEhfAaViECAjMqCLQij7xo9+TYOKdP7R4ACuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdlY1VmlnczZYdHNiUzVE
            MHJVckxHMGdWUnJVdkIvL2pUbm9PWHRrV2xVCjZEYjFPUi9ZZDdJVXRQQnVCaWJS
            UkNTVHJPQzE2QTV4akhnTXMrU09lbkkKLS0tIE5CTE1aQ3QxWGdabHQ0ZnE3Z21G
            ejBaVHF3S2tKallUaFA1clFqNXdwMDQKHwVvDpucPQZ+RlIAIEopztj7uLwFhGZT
            lEB6IUHtMlwF2HVb2ZZIW5j9I5DDuVK5z2+gTNHw9tDXNRERdpc1LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T11:19:31Z"
    mac: ENC[AES256_GCM,data:AD5AHHUxo2NU1bqNkqoageRjMGAulZEQLscXNtJu2vQN3QgGtDkoGoRA/UiYrn/mlzyLUo9Re5l5s2W2QHU0FvFWURgvhVG648TrouKwXvlS5VbCRL9Sprv78QcoxS7Xm7W2BZ2z4h7WnK397qGaP0oElp2iPJ7pS4dEfVRL3lk=,iv:tJMHxaudKkDGSXd87bKE5Q96nT2MEEqWNVTnYJUp7Pw=,tag:zNKGQRKIebU+S5kyze3tFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
