apiVersion: v1
kind: Secret
metadata:
    name: krypton-secret
    namespace: services
type: Opaque
stringData:
    root-key: ENC[AES256_GCM,data:Iyjhj6iNBsCWiCQ8OFoROKBsXWvcDNf3Q4lxQaRZYp602So4buHtcWMxNMQ=,iv:SR4XG1v/st3ffeUcaMvi4wOweVsWrMZRSQXm0kbsThM=,tag:gJcmHCzAFD0kb7v2VjQtuQ==,type:str]
sops:
    age:
        - recipient: age1za89nwjqquwwhaxsddy2dcng7cpy8fzfdk92uuq6y3qqm98hr5pqhsyatq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZldQalIvcUdZQVU4WTIr
            VWNJN1U5NTJoQWVoL3QwRUpmcTU1VmhwNUVzCnI5NGh2VWhNQTY5VEcrdFpHeHJZ
            OEpKdlVHQkhHTlhqREx5WG03K05VdmcKLS0tIGRDZ01HWmVveld6NWUveC8wKy8y
            dGRoVElJOHZ1L3lZZmg2WHRTYVMrOW8KzE6ahaf3ZeBevRGsLN6Z7mv8GQHwlBQk
            Ib/dho4FcX8b6Ipe+8nbv2Z7q7Cp9Dq8KY3psE3Ft7NuLAWd6x9/YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15e9nr7zafzpp9whl3u6t28la92p9mm0npp9596ty0rs4x5pcdq0qx0uf52
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUGR1MitkNVJsY1Jrd1o5
            dWRHSFhqNllSTmozQUJjOFZmcEJjTGUydnpvCmJIKzVSNXMrcHZZaDFwcEcrSlAv
            c3h6NG5vRHp1Q3RVWkZ0RHdBWXpudkUKLS0tIFZrUG1UV1k0QVEzenE5ZldCTXkv
            TE93Q3JoY0EyKy9LNGp0Rm9FWnFVOUEKLduJEI+r5Hl1CuMlYWv9OdtuNEeuDPto
            SnqM/XURnuJ21LmSSu4QubWfWvR46vFg8DRIqjlI3b8mDE+k7H2PQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14ykmjz46nps5klsgdu64z7lqj7nec4g4xr68dekx3tge6ser5sjq5f4drq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYL3ZBZnl4SEpDcDR0RmYr
            ZENrWnZIZ3RXNlhwYVhkbTN1VUtVY3RRSzM4CmQwMnUwMi9jNzEvL0ZRTFBxSGlL
            WHZtaXlDaWdIaTlHS3UySGtBMHBWMTAKLS0tIFIwSExicFpCWGVjelhFNzZQL08y
            YVRkdHJGSFNCc2FoRUNNQk5QY0JKMlEKIjLRGOpBiwpmjM/n2I+8OJ2GM2EToLo+
            /sq2Jc1IsWcn+6fZxNilP5bttSDnAfvcjP4Om6+dZjgHrawlA6/rCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r0mzcgzm74jssdnvllpwzkj98d2eae8maxflsdgdwtt0d4ea5fnslp833d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydVk4enVuSXd3M0E0aWsz
            cFpBeFdDc1VDUHJBM291RHpDK1kzVFMxZGd3CnpneElVaUtiV3FaNUJsRlZRd3NJ
            VU1VckFlRlpRTXliU2FZS2lrS3RKQUkKLS0tIDQyYy8xOGdLTnFuckNHVnplbGVN
            Z2dpa0s4ZUdCY2xjcWZLVEI3eDYrMnMKLFUj9rh19vBWglBg7NpNBscO95aUSRbN
            hgBTa/pV8oN6aGdtRxNz5aR7vQwXRxwhsOUrAoCthuUugxGR/eb5/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1203z9r32ljp8rp7rjh02qzgkv4qf76g2yuc48k92lpkurhvj6awsxm70tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOFJsQ3RlR25RbnA3NGIx
            aWJTRDBKSVJ3cmRyZHEyN1dQSFZsazB0eWk0CmZvNWZwTHEycFUyODd0cWJub2d0
            aHJlOEl3WFlTS1ZvTFpIYU9ubVJCY2cKLS0tIEpVN2ZQbHFNWi9vYVhLMldWTSt2
            Qk9BU3hycDI2aERTaldWNkt6elpsbkEKfQw0OOIGwPnG9sD0yt5EUs3pI/yJ9sJc
            M6B3ksBdzPdyd2R/zPS/3dcMTONZxB8H37CT1yqSZP2+R24WaThvQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T13:11:22Z"
    mac: ENC[AES256_GCM,data:t/QEd+ioZIUIMMd/208BGQChyoJhI+799S15xXNtRomfHmhwDzBkaxZtlyHk+boWIvu6W3gRMu1PZX7s6nSp9mzLZvdkS6DbMjeAJ9RgNodS1yETDskM1Gz5yn7rsSjBQPJfQpNl7jFmEJ9h1Q1DK6PAAeY+Q7S0up/Ui+M4ptg=,iv:jsnmgja/anQYg5PHkAh79E0vGLJ9rwetdACkIpBa89A=,tag:2Q3jkDHO4ng0qo9opXeRjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
