apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: network-routing-system
spec:
  storageNamespace: envoy-gateway-system
  targetNamespace: envoy-gateway-system
  valuesFrom:
    # !! The sequence is important !!
    # Always first **base** and **overlay** (if necessary) later.
    ## base
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: client-traffic-policy-certificate-tls.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: client-traffic-policy-tls.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: echoserver-certificate-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: echoserver-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: echoserver-security-policy.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-certificate-config.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-config.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: envoy-proxy-kms20cmk1-jwt-provider.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: gateway-class-ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: gateway-class-ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: ingress-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: sap-cloud-root-ca.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: service-envoy-proxy-ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-base-values
      valuesKey: service-envoy-proxy-ingress-gateway.yaml
    ## overlay
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: cmk-certificate-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: cmk-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: cmk-security-policy.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: echoserver-certificate-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: echoserver-http-route.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: echoserver-security-policy.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: envoy-proxy-certificate-config.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: envoy-proxy-config.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: ingress-certificate-gateway.yaml
    - kind: ConfigMap
      name: network-routing-system-overlay-values
      valuesKey: ingress-gateway.yaml
